version: '3.9'

services:

  nginx-proxy:
    container_name: dtrafico_https
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./letsencrypt/certs:/etc/nginx/certs:ro
      - ./letsencrypt/vhostd:/etc/nginx/vhost.d
      - ./letsencrypt/html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - mynetwork

  letsencrypt:
    container_name: generador_certificados
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=dtrafico_https
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt/certs:/etc/nginx/certs:rw
      - ./letsencrypt/vhostd:/etc/nginx/vhost.d
      - ./letsencrypt/html:/usr/share/nginx/html
    networks:
      - mynetwork

  codeigniter:
    container_name: user_administrador
    image: bitnami/codeigniter:4.4.3-debian-11-r0
    ports:
      - "9000:8000"
    volumes:
      - ./codeigniter/app:/app  
    environment:
      - CODEIGNITER_PROJECT_NAME=myapp
      - CODEIGNITER_DATABASE_HOST=mariadb
      - CODEIGNITER_DATABASE_USER=myuser
      - CODEIGNITER_DATABASE_PASSWORD=mypassword
      - APP_ENV=production
      - APP_BASE_URL=panel.clinicalibre.cl/
      - VIRTUAL_HOST=panel.clinicalibre.cl
      - LETSENCRYPT_HOST=panel.clinicalibre.cl
      - LETSENCRYPT_EMAIL=clinicalibrechile@gmail.com
    depends_on:
      - mysql_6
    restart: always
    networks:
      - mynetwork

  php_clinica:
    container_name: php_clinica
    build:
      context: ./
      dockerfile: ./php_clinica/Dockerfile
    environment:
      - TZ=America/Santiago
      - APP_BASE_URL=https://clinicalibre.cl
      - VIRTUAL_HOST=clinicalibre.cl,www.clinicalibre.cl
      - LETSENCRYPT_HOST=clinicalibre.cl,www.clinicalibre.cl
      - LETSENCRYPT_EMAIL=clinicalibrechile@gmail.com
    ports:
      - "9025:80"
      - "9026:443"
    restart: always 
    depends_on:
      - mysql_6 
    volumes:
      - ./php_clinica/html:/var/www/html/
    networks:
      - mynetwork
  
  mysql_6:
    container_name: mysql_6
    image: mysql:5.7
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_spanish_ci
      - --init-connect=SET NAMES utf8mb4 COLLATE utf8mb4_spanish_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "ssprueba.210"
      MYSQL_DATABASE: ADMIN
      MYSQL_USER: ADMIN
      MYSQL_PASSWORD: "ssprueba.210"
      TZ: America/Santiago
    expose:
      - "9306"
    ports:
      - "9306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d/
    networks:
      - mynetwork          

  monitoreo_mysql:
    image: adminer
    restart: always
    ports:
      - 9100:8080
    networks:
      - mynetwork
  #backup_service:
    #build:
      #context: ./backup_service
      #dockerfile: Dockerfile
    #volumes:
      #- db_data:/var/lib/mysql
      #- ./backup_service/backup:/backup_service/backup
    #restart: always

secrets:
  mysql_root_password:
    file: ./secrets/root_password.txt
  mysql_user_password:
    file: ./secrets/user_password.txt

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
