version: "3.8"
services:
  mysql_6:
    image: mysql:5.7
    # Anulamos el command original y ejecutamos directamente mysqld:
    command: ["mysqld",
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_spanish_ci",
      "--init-connect=SET NAMES utf8mb4 COLLATE utf8mb4_spanish_ci",
      "--explicit_defaults_for_timestamp=1"
    ]
    # Quitamos las variables que disparan initialize
    environment: []
    # Montamos solo el volumen de datos (sin /docker-entrypoint-initdb.d/)
    volumes:
      - db_data:/var/lib/mysql
