SET TIME_ZONE = '-04:00';
ALTER DATABASE ADMIN CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci;
SET NAMES 'utf8mb4' COLLATE 'utf8mb4_spanish_ci';
SET collation_connection  = 'utf8mb4_spanish_ci';

CREATE TABLE ADMIN_AP_TTIPOATENCION (
  IND_TIPOATENCION VARCHAR(2),
  DES_TIPOATENCION VARCHAR(40),
  COD_USRCREA VARCHAR(60),
  FEC_USRCREA DATE,
  IND_ESTADO VARCHAR(1),
  COD_TPROFE VARCHAR(4)
);

Insert into ADMIN.AP_TTIPOATENCION
   (IND_TIPOATENCION, DES_TIPOATENCION, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    COD_TPROFE)
 Values
   ('19', 'QUIMICO FARMACEUTICO', 'ADMIN', TO_DATE('05/20/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    'QUIF');
Insert into ADMIN.AP_TTIPOATENCION
   (IND_TIPOATENCION, DES_TIPOATENCION, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    COD_TPROFE)
 Values
   ('01', 'MEDICO GENERAL', 'ADMIN', TO_DATE('12/29/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    'INTG');
Insert into ADMIN.AP_TTIPOATENCION
   (IND_TIPOATENCION, DES_TIPOATENCION, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    COD_TPROFE)
 Values
   ('02', 'ENFERMERA(O)', 'ADMIN', TO_DATE('12/29/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    'ENFE');
Insert into ADMIN.AP_TTIPOATENCION
   (IND_TIPOATENCION, DES_TIPOATENCION, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    COD_TPROFE)
 Values
   ('03', 'MATRON(A)', 'ADMIN', TO_DATE('12/29/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    'MATR');
Insert into ADMIN.AP_TTIPOATENCION
   (IND_TIPOATENCION, DES_TIPOATENCION, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    COD_TPROFE)
 Values
   ('04', 'PSICOLOGO(A)', 'ADMIN', TO_DATE('12/29/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    'PSIC');
Insert into ADMIN.AP_TTIPOATENCION
   (IND_TIPOATENCION, DES_TIPOATENCION, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    COD_TPROFE)
 Values
   ('06', 'NUTRICIONISTA', 'ADMIN', TO_DATE('12/29/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    'NUTR');
Insert into ADMIN.AP_TTIPOATENCION
   (IND_TIPOATENCION, DES_TIPOATENCION, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    COD_TPROFE)
 Values
   ('07', 'TECNOLOGO MEDICO', 'ADMIN', TO_DATE('12/29/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    'TMED');
Insert into ADMIN.AP_TTIPOATENCION
   (IND_TIPOATENCION, DES_TIPOATENCION, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    COD_TPROFE)
 Values
   ('08', 'TERAPEUTA OCUPACIONAL', 'ADMIN', TO_DATE('12/29/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    'TOCU');
Insert into ADMIN.AP_TTIPOATENCION
   (IND_TIPOATENCION, DES_TIPOATENCION, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    COD_TPROFE)
 Values
   ('09', 'ASISTENTE SOCIAL', 'ADMIN', TO_DATE('12/29/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    'ASOC');
Insert into ADMIN.AP_TTIPOATENCION
   (IND_TIPOATENCION, DES_TIPOATENCION, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    COD_TPROFE)
 Values
   ('10', 'ODONTOLOGO', 'ADMIN', TO_DATE('12/29/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    'DENT');
Insert into ADMIN.AP_TTIPOATENCION
   (IND_TIPOATENCION, DES_TIPOATENCION, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    COD_TPROFE)
 Values
   ('05', 'KINESIOLOGO', 'ADMIN', TO_DATE('06/10/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    'KINE');
Insert into ADMIN.AP_TTIPOATENCION
   (IND_TIPOATENCION, DES_TIPOATENCION, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    COD_TPROFE)
 Values
   ('11', 'EDUCADORA PARVULO', 'ADMIN', TO_DATE('06/10/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    'EPAR');
Insert into ADMIN.AP_TTIPOATENCION
   (IND_TIPOATENCION, DES_TIPOATENCION, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    COD_TPROFE)
 Values
   ('12', 'TECNICO PARAMEDICO', 'ADMIN', TO_DATE('06/10/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    'TPAR');
Insert into ADMIN.AP_TTIPOATENCION
   (IND_TIPOATENCION, DES_TIPOATENCION, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    COD_TPROFE)
 Values
   ('13', 'FONOAUDILOGO', 'ADMIN', TO_DATE('06/10/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    'FONO');
Insert into ADMIN.AP_TTIPOATENCION
   (IND_TIPOATENCION, DES_TIPOATENCION, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    COD_TPROFE)
 Values
   ('14', 'TECNICO PARAMEDICO DENTAL', 'ADMIN', TO_DATE('01/18/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    'TPAD');
Insert into ADMIN.AP_TTIPOATENCION
   (IND_TIPOATENCION, DES_TIPOATENCION, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    COD_TPROFE)
 Values
   ('15', 'MEDICO ESPECIALISTA', 'ADMIN', TO_DATE('03/14/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    'MEDI');
Insert into ADMIN.AP_TTIPOATENCION
   (IND_TIPOATENCION, DES_TIPOATENCION, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    COD_TPROFE)
 Values
   ('16', 'ODONTOLOGO ESPECIALISTA', 'ADMIN', TO_DATE('06/21/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    'ODON');
Insert into ADMIN.AP_TTIPOATENCION
   (IND_TIPOATENCION, DES_TIPOATENCION, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    COD_TPROFE)
 Values
   ('17', 'EDUCADORA DIFERENCIAL', 'ADMIN', TO_DATE('09/25/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    'EDIF');
Insert into ADMIN.AP_TTIPOATENCION
   (IND_TIPOATENCION, DES_TIPOATENCION, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    COD_TPROFE)
 Values
   ('32', 'TECNICO EN NIVEL SUPERIOR', 'ADMIN', TO_DATE('05/24/2023 11:42:41', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    'TNSU');
Insert into ADMIN.AP_TTIPOATENCION
   (IND_TIPOATENCION, DES_TIPOATENCION, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    COD_TPROFE)
 Values
   ('22', 'FACILITADOR INTERCULTURAL', 'ADMIN', TO_DATE('04/20/2017 19:36:48', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    'FAIN');

CREATE TABLE ADMIN_GG_TPROFESION (
  COD_TPROFE VARCHAR(4),
  NOM_TPROFE VARCHAR(30),
  COD_USUARI VARCHAR(60),
  FEC_AUDITA DATE,
  IND_ESTADO VARCHAR(1),
  FEC_USRCREA DATE,
  COD_USRCREA VARCHAR(60),
  COD_GRUPO VARCHAR(6),
  COD_ARPROF VARCHAR(6),
  DESC_PROFESION VARCHAR(30),
  IND_TIPOATENCION VARCHAR(2),
  COD_PRESTACION VARCHAR(15),
  NUM_ESPECIDEIS INT,
  TIPO_PROFESIONDEIS VARCHAR(3),
  TIPO_ESPECIALIDAD VARCHAR(3)
);


Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('ENDI', 'ENDOCRINOLOGIA INFANTIL', 'CAPACITA', TO_DATE('08/25/2017 12:14:59', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('08/25/2017 12:15:04', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'ENDI', 'MEDI', 'MEDICO CIRUJANO', 
    '15', '07-104-0', NULL, '01', '15');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('TMOF', 'TECNOLOGO MEDICO OFTALMOLOGIA', 'ADMIN', TO_DATE('11/07/2019 14:21:21', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('11/07/2019 14:21:26', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'OTROS', NULL, 'TECNOLOGO MEDICO OFTALMOLOGIA', 
    '28', NULL, NULL, '06', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('CTER', 'CLOWN TERAPEUTICO', 'CAPACITA', TO_DATE('09/25/2014 16:29:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('09/25/2014 16:29:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', NULL, NULL, NULL, 
    '18', NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('PEDT', 'PEDIATRA', 'CAPACITA ', TO_DATE('11/19/2002 09:14:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('11/19/2002 09:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'PEDI', 'MEDI', 'MEDICO CIRUJANO', 
    '15', '01-011-12', 71001, '01', '47');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('INTG', 'MEDICO GENERAL', 'CAPACITA', TO_DATE('11/19/2002 09:14:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('11/19/2002 09:14:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'MEDG', 'MEDI', 'MEDICO CIRUJANO', 
    '01', '01-011-01', 79001, '01', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('CIRU', 'CIRUJANO', 'CAPACITA', TO_DATE('11/19/2002 09:15:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('11/19/2002 09:15:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'CIRU', 'MEDI', NULL, 
    '15', '07-200-2', 72002, '01', '04');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('ANST', 'ANESTESISTA', 'CAPACITA', TO_DATE('11/19/2002 09:15:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('11/19/2002 09:15:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'ANES', 'MEDI', 'MEDICO CIRUJANO', 
    '15', '07-210-0', 72102, '01', '02');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('OTOR', 'OTORRINOLARINGOLOGO', 'CAPACITA', TO_DATE('11/19/2002 09:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('11/19/2002 09:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'OTOR', 'MEDI', 'MEDICO CIRUJANO', 
    '15', '13-02-029', 75009, '01', '46');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('RAYO', 'RADIOLOGO', 'CAPACITA', TO_DATE('11/19/2002 09:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('11/19/2002 09:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'MEDI', 'MEDI', 'MEDICO CIRUJANO', 
    '15', NULL, NULL, '01', '24');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('INTR', 'INTERNISTA', 'CAPACITA', TO_DATE('11/19/2002 09:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('11/19/2002 09:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'MEDI', 'MEDI', 'MEDICO CIRUJANO', 
    '15', '07-102-0', 71002, '01', '30');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('OBTR', 'GINECO-OBSTETRA', 'CAPACITA ', TO_DATE('11/19/2002 11:05:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('11/19/2002 09:16:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'OBST', 'MEDI', 'MEDICO CIRUJANO', 
    '15', '01-020-01', 73012, '01', '43');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('OFTL', 'OFTALMOLOGO', 'CAPACITA', TO_DATE('11/19/2002 09:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('11/19/2002 09:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'OFTL', 'MEDI', 'MEDICO CIRUJANO', 
    '15', '12-02-062', 74009, '01', '44');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('TRAM', 'TRAUMATOLOGO', 'CAPACITA', TO_DATE('11/19/2002 09:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('11/19/2002 09:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'TRAU', 'MEDI', 'MEDICO CIRUJANO', 
    '15', '21-04-167', 77002, '01', '53');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('PSIQ', 'PSIQUIATRA', 'CAPACITA', TO_DATE('11/19/2002 09:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('11/19/2002 09:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'PSIQ', 'MEDI', 'PSIQUIATRA', 
    '15', '07-117-0', NULL, '01', '48');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('TMED', 'TECNOLOGO MEDICO', 'CAPACITA ', TO_DATE('03/10/2003 10:36:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('11/19/2002 09:17:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'OTROS', 'MEDI', 'TECNOLOGO MEDICO', 
    '07', NULL, NULL, '06', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('DENT', 'ODONTOLOGO', 'CAPACITA', TO_DATE('11/19/2002 09:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('11/19/2002 09:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'ODON', 'MEDI', 'ODONTOLOGO', 
    '10', '09-007-0', 92000, '02', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('QUIF', 'QUIMICO FARMACEUTICO', 'CAPACITA', TO_DATE('11/19/2002 11:05:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('11/19/2002 11:05:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', NULL, 'MEDI', 'QUIMICO FARMACEUTICO', 
    '19', NULL, NULL, '09', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('KINE', 'KINESIOLOGO', 'CAPACITA', TO_DATE('12/11/2002 10:04:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('12/11/2002 10:04:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'KINE', 'MEDI', 'KINESIOLOGO', 
    '05', '01-020-06', NULL, '08', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('AUXI', 'AUXILIAR', 'CAPACITA', TO_DATE('03/10/2003 12:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/10/2003 12:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'OTROS', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('DADM', 'DIRECCION ADMINISTRATIVA', 'CAPACITA', TO_DATE('03/10/2003 12:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/10/2003 12:19:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('EPAR', 'EDUCACION DE PARVULOS', 'CAPACITA', TO_DATE('03/10/2003 12:20:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/10/2003 12:20:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', NULL, NULL, 'EDUCADORA DE PARVULOS', 
    '11', NULL, NULL, '33', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('INGE', 'INGENIERO', 'CAPACITA', TO_DATE('03/10/2003 12:21:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/10/2003 12:21:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', NULL, NULL, NULL, 
    NULL, NULL, NULL, '99', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('TOCU', 'TERAPEUTA OCUPACIONAL', 'CAPACITA', TO_DATE('03/10/2003 12:21:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/10/2003 12:21:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', NULL, 'MEDI', 'TERAPEUTA OCUPACIONAL', 
    '08', NULL, NULL, '13', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('TMAN', 'TECNICO DE MANTENCION', 'CAPACITA', TO_DATE('03/10/2003 12:22:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/10/2003 12:22:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('ASOC', 'ASISTENTE SOCIAL', 'CAPACITA', TO_DATE('03/10/2003 12:22:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/10/2003 12:22:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', NULL, 'MEDI', 'ASISTENTE SOCIAL', 
    '09', '01-020-01', NULL, '31', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('NUTR', 'NUTRICIONISTA', 'CAPACITA', TO_DATE('03/10/2003 12:22:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/10/2003 12:22:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', NULL, 'MEDI', 'NUTRICIONISTA', 
    '06', NULL, 71090, '11', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('OFAD', 'OFICIAL ADMINISTRATIVO', 'CAPACITA', TO_DATE('03/10/2003 12:23:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/10/2003 12:23:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('TPAR', 'TECNICO PARAMEDICO', 'CAPACITA', TO_DATE('03/10/2003 12:23:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/10/2003 12:23:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'OTROS', 'MEDI', 'TECNICO PARAMEDICO', 
    '12', NULL, NULL, '20', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('CHOF', 'CHOFER', 'CAPACITA', TO_DATE('03/10/2003 12:23:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/10/2003 12:23:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', NULL, NULL, NULL, 
    '26', '15-02-014', NULL, NULL, NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('ENFE', 'ENFERMERO(A)', 'CAPACITA ', TO_DATE('01/08/2009 11:10:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/10/2003 12:23:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'OTROS', 'MEDI', 'ENFERMERA', 
    '02', '01-020-01', NULL, '03', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('MATR', 'MATRON (A)', 'CAPACITA ', TO_DATE('03/20/2003 09:53:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/10/2003 12:23:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'OTROS', 'MEDI', 'MATRON', 
    '03', NULL, 73001, '05', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('CONT', 'CONTADOR', 'CAPACITA', TO_DATE('03/18/2003 12:49:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/18/2003 12:49:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('CARD', 'CARDIOLOGO', 'CAPACITA ', TO_DATE('04/13/2004 19:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('05/29/2003 16:03:00', 'MM/DD/YYYY HH24:MI:SS'), 'BERNARDA_FIGUEROA', 'MEDI', 'MEDI', 'MEDICO CIRUJANO', 
    '15', '07-103-0', 71032, '01', '03');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('PATO', 'ANATOMOPATOLOGO', 'BERNARDA_FIGUEROA', TO_DATE('05/30/2003 08:47:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('05/30/2003 08:47:00', 'MM/DD/YYYY HH24:MI:SS'), 'BERNARDA_FIGUEROA', 'OTROS', 'MEDI', 'MEDICO CIRUJANO', 
    '15', NULL, NULL, '01', '01');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('UROL', 'UROLOGO', 'CAPACITA', TO_DATE('04/13/2004 18:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('04/13/2004 18:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'UROL', 'MEDI', 'MEDICO CIRUJANO', 
    '15', '19-02-030', 78002, '01', '54');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('NEUR', 'NEUROLOGO', 'CAPACITA', TO_DATE('04/13/2004 19:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('04/13/2004 19:13:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'NEUR', 'MEDI', 'MEDICO CIRUJANO', 
    '15', '07-115-0', 71152, '01', '41');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('PSIC', 'PSICOLOGO', 'CAPACITA', TO_DATE('07/04/2005 09:49:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('07/04/2005 09:49:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', NULL, 'MEDI', 'PSICOLOGO', 
    '04', '01-020-04', NULL, '07', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('MEMC', 'CARDIOLOGIA', 'NORA_FAUNDEZ', TO_DATE('01/05/2006 11:25:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('01/05/2006 11:25:00', 'MM/DD/YYYY HH24:MI:SS'), 'NORA_FAUNDEZ', NULL, NULL, NULL, 
    '15', NULL, NULL, '01', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('TFAR', 'TECNICO EN FARMACIA', 'CAPACITA', TO_DATE('01/07/2008 09:35:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('01/07/2008 09:35:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', NULL, NULL, NULL, 
    NULL, NULL, NULL, '17', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('EDIF', 'EDUCACION DIFERENCIAL', 'CAPACITA', TO_DATE('01/25/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('01/25/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', NULL, NULL, 'EDUCADOR DIFERENCIAL', 
    '17', NULL, NULL, '32', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('FONO', 'FONOAUDIOLOGO', 'CAPACITA', TO_DATE('03/10/2003 12:23:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('01/25/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'FONO', 'MEDI', 'FONOAUDIOLOGO', 
    '13', NULL, NULL, '12', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('OTRO', 'OTRO PROFESIONAL', 'CAPACITA', TO_DATE('01/25/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('01/25/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', NULL, NULL, 'OTRO PROFESIONAL', 
    NULL, NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('FAIN', 'FACILITADOR INTERCULTURAL', 'CAPACITA', TO_DATE('03/05/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/05/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'OTROS', NULL, 'FACILITADOR INTERCULTURAL', 
    '27', NULL, NULL, '30', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('TPAD', 'TECNICO PARAMEDICO DENTAL', 'CAPACITA', TO_DATE('03/05/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/05/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'MEDI', 'MEDI', 'TECNICO PARAMEDICO DENTAL', 
    '14', NULL, NULL, '16', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('TENF', 'TECNICO', 'CAPACITA', TO_DATE('03/12/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/12/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'MEDI', 'MEDI', 'AUXILIAR DE ENFERMERIA', 
    NULL, NULL, NULL, '18', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('TNSU', 'TECNICO EN NIVEL SUPERIOR', 'CAPACITA', TO_DATE('03/12/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/12/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'MEDI', 'MEDI', 'TECNICO EN NIVEL SUPERIOR', 
    '32', NULL, NULL, '19', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('PODO', 'PODOLOGO', 'CAPACITA', TO_DATE('02/23/2009 09:25:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('02/23/2009 09:25:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'PODO', NULL, NULL, 
    '20', NULL, NULL, '23', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('PREF', 'PROFESOR DE EDUCACION FISICA', 'ADMIN', TO_DATE('01/21/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('01/21/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', NULL, NULL, 'PROFESOR DE EDUACION FISICA', 
    '25', NULL, NULL, '34', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('GAST', 'GASTROENTEROLOGIA ADULTO', 'CAPACITA', TO_DATE('02/27/2009 08:28:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('02/27/2009 08:28:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', NULL, 'MEDI', NULL, 
    '15', '07-105-0', 71050, '01', '18');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('NEFR', 'NEFROLOGO', 'CAPACITA', TO_DATE('06/07/2011 16:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('06/07/2011 16:51:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'NEFR', 'MEDI', NULL, 
    '15', '07-108-0', 71150, '01', '37');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('MEDE', 'ESPECIALISTA', 'ADMIN', TO_DATE('06/21/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('06/21/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'MEDI', 'MEDI', NULL, 
    '15', NULL, NULL, '01', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('DERM', 'DERMATOLOGO', 'ADMIN', TO_DATE('06/21/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('06/21/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', NULL, 'MEDI', 'DERMATOLOGO', 
    '15', '16-02-007', 71112, '01', '12');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('MEDF', 'MEDICO FAMILIAR', 'ADMIN', TO_DATE('06/21/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('06/21/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'MEDF', 'MEDI', 'MEDICO FAMILIAR', 
    '21', '07-900-1', 79001, '01', '28');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('ODON', 'ODONTOLOGO ESPECIALISTA', 'ADMIN', TO_DATE('06/21/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('06/21/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'ODON', 'MEDI', 'ODONTOLOGO ESPECIALISTA', 
    '16', '09-007-0', NULL, '02', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('NTRI', 'NUTRIOLOGA', 'ADMIN', TO_DATE('03/11/2019 15:47:01', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 15:47:07', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'MEDI', 'MEDI', 'NUTRIOLOGA', 
    '15', NULL, NULL, '01', '63');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('FISI', 'FISIATRA', 'CAPACITA', TO_DATE('10/16/2012 10:41:00', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('10/16/2012 10:41:00', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'MFRI', 'MEDI', NULL, 
    '15', '07-114-0', 71142, '01', '29');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('TEPA', 'TENS Y PARAMEDICOS', 'CAPACITA', NULL, 'V', 
    NULL, NULL, NULL, NULL, 'TENS Y PARAMEDICOS', 
    NULL, NULL, NULL, '19', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('PRSA', 'PROFESIONAL DE SALA', 'CAPACITA', NULL, 'V', 
    NULL, NULL, NULL, NULL, 'PROFESIONAL DE SALA', 
    NULL, NULL, NULL, '99', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('CIRI', 'CIRUJANO INFANTIL', 'ADMIN', TO_DATE('04/06/2017 12:28:07', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('04/06/2017 12:28:19', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'CIRI', 'MEDI', 'CIRUJANO PEDIATRICO', 
    '15', '07-200-1', NULL, '01', '09');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('SPED', 'PSICOPEDAGOGO', 'ADMIN', TO_DATE('12/02/2020 14:40:18', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('12/02/2020 14:40:25', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'OTROS', NULL, 'PSICOPEDAGOGO', 
    '29', NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('CIRV', 'CIRUJANO VASCULAR', 'ADMIN', TO_DATE('10/16/2017 15:17:10', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('10/16/2017 15:17:39', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'CIRV', 'MEDI', 'CIRUJANO PERIFERICO', 
    '15', '07-207-2', 72072, '01', '10');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('KINH', 'KINESIOLOGO EAR', 'ADMIN', TO_DATE('03/14/2018 14:14:52', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/14/2018 14:15:01', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'KINE', 'KINE', 'KINESIOLOGO EAR', 
    '22', '01-020-06', NULL, '08', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('URGE', 'URGENCIOLOGO', 'ADMIN', TO_DATE('04/07/2020 20:33:59', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('04/07/2020 20:34:07', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'URGE', 'MEDI', 'MEDICO URGENCIOLOGO', 
    '15', NULL, NULL, NULL, '36');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('TOCH', 'TERAPEUTA OCUPACIONAL EAR', 'CAPACITA', TO_DATE('04/24/2018 08:58:59', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('04/24/2018 08:59:03', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'TOCU', 'MEDI', 'TERAPEUTA OCUPACIONAL', 
    '23', NULL, NULL, '13', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('FONH', 'FONOAUDIOLOGO EAR', 'CAPACITA', TO_DATE('04/24/2018 09:02:25', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('04/24/2018 09:02:29', 'MM/DD/YYYY HH24:MI:SS'), 'CAPACITA', 'FONO', 'MEDI', 'FONOAUDIOLOGO', 
    '24', NULL, NULL, '12', NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('CICC', 'CIRUGIA CABEZA, CUELLO, MAXILO', 'ADMIN', TO_DATE('03/11/2019 11:10:43', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 11:10:49', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'CICC', 'MEDI', 'CIRUGIA CABEZA, CUELLO, MAXILO', 
    '15', NULL, NULL, '01', '05');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('CIRC', 'CIRUGIA CARDIOVASCULAR', 'ADMIN', TO_DATE('03/11/2019 11:15:57', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 11:16:01', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'CIRC', 'MEDI', 'CIRUGIA CARDIOVASCULAR', 
    '15', NULL, NULL, '01', '06');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('CIRT', 'CIRUGIA DE TORAX', 'ADMIN', TO_DATE('03/11/2019 11:17:08', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 11:17:13', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'CIRT', 'MEDI', 'CIRUGIA DE TORAX', 
    '15', NULL, NULL, '01', '07');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('CIPL', 'CIRUGIA PLASTICA Y REPARADORA', 'ADMIN', TO_DATE('03/11/2019 11:18:55', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 11:18:59', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'CIPL', 'MEDI', 'CIRUGIA PLASTICA Y REPARADORA', 
    '15', NULL, NULL, '01', '08');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('CIRP', 'CIRUGIA PROCTOLOGICA', 'ADMIN', TO_DATE('03/11/2019 14:16:30', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 14:16:35', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'CIRP', 'MEDI', 'CIRUGIA PROCTOLOGICA', 
    '15', NULL, NULL, '01', '11');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('DIAB', 'DIABETOLOGIA', 'ADMIN', TO_DATE('03/11/2019 14:23:49', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 14:23:54', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'DIAB', 'MEDI', 'DIABETOLOGIA', 
    '15', NULL, NULL, '01', '13');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('ENDC', 'ENDOCRINOLOGIA', 'ADMIN', TO_DATE('03/11/2019 14:24:52', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 14:24:55', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'ENDC', 'MEDI', 'ENDOCRINOLOGIA ', 
    '15', '07-104-0', NULL, '01', '14');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('BRON', 'BRONCOPULMONAR ADULTO', 'ADMIN', TO_DATE('03/11/2019 14:28:33', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 14:28:37', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'BRON', 'MEDI', 'BRONCOPULMONAR ADULTO', 
    '15', NULL, NULL, '01', '16');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('BROI', 'BRONCOPULMONAR INFANTIL', 'ADMIN', TO_DATE('03/11/2019 14:33:35', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 14:33:40', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'BROI', 'MEDI', 'BRONCOPULMONAR INFANTIL', 
    '15', NULL, NULL, '01', '17');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('GASI', 'GASTROENTEROLOGIA PEDIATRICA', 'ADMIN', TO_DATE('03/11/2019 14:35:20', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 14:35:24', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'GASI', 'MEDI', 'GASTROENTEROLOGIA PEDIATRICA', 
    '15', NULL, NULL, '01', '19');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('GENE', 'GENETICA CLINICA', 'ADMIN', TO_DATE('03/11/2019 14:36:35', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 14:36:40', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'GENE', 'MEDI', 'GENETICA CLINICA', 
    '15', NULL, NULL, '01', '20');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('GERI', 'GERIATRIA', 'ADMIN', TO_DATE('03/11/2019 14:37:35', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 14:37:45', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'GERI', 'MEDI', 'GERIATRIA', 
    '15', NULL, NULL, '01', '21');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('GINI', 'GINECOLOGIA INFANTIL Y ADOLESC', 'ADMIN', TO_DATE('03/11/2019 14:39:09', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 14:39:15', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'GINI', 'MEDI', 'GINECOLOGIA INFANTIL Y ADOLESC', 
    '15', NULL, NULL, '01', '22');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('HEMA', 'HEMATOLOGIA', 'ADMIN', TO_DATE('03/11/2019 14:40:05', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 14:40:10', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'HEMA', 'MEDI', 'HEMATOLOGIA', 
    '15', NULL, NULL, '01', '23');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('IMAG', 'IMAGENOLOGIA', 'ADMIN', TO_DATE('03/11/2019 14:40:58', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 14:41:03', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'IMAG', 'MEDI', 'IMAGENOLOGIA', 
    '15', NULL, NULL, '01', '24');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('INFE', 'INFECTOLOGIA', 'ADMIN', TO_DATE('03/11/2019 14:41:53', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 14:41:58', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'INFE', 'MEDI', 'INFECTOLOGIA', 
    '15', NULL, NULL, '01', '25');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('INMU', 'INMUNOLOGIA', 'ADMIN', TO_DATE('03/11/2019 14:42:42', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 14:42:47', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'INMU', 'MEDI', 'INMUNOLOGIA', 
    '15', NULL, NULL, '01', '26');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('LABC', 'LABORTATORIO CLINICO', 'ADMIN', TO_DATE('03/11/2019 14:44:12', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 14:44:05', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'LABC', 'MEDI', 'LABORTATORIO CLINICO', 
    '15', NULL, NULL, '01', '27');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('MEDL', 'MEDICINA LEGAL', 'ADMIN', TO_DATE('03/11/2019 14:47:47', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 14:47:52', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'MEDL', 'MEDI', 'MEDICINA LEGAL', 
    '15', NULL, NULL, '01', '33');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('MEDN', 'MEDICINA NUCLEAR', 'ADMIN', TO_DATE('03/11/2019 14:50:06', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 14:50:11', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'MEDN', 'MEDI', 'MEDICINA NUCLEAR', 
    '15', NULL, NULL, '01', '35');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('NEFI', 'NEFROLOGIA INFANTIL', 'ADMIN', TO_DATE('03/11/2019 15:10:18', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 15:10:24', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'NEFI', 'MEDI', 'NEFROLOGIA INFANTIL', 
    '15', NULL, NULL, '01', '38');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('NEON', 'NEONATOLOGIA', 'ADMIN', TO_DATE('03/11/2019 15:12:21', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 15:12:26', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'NEON', 'MEDI', 'NEONATOLOGIA', 
    '15', NULL, NULL, '01', '39');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('NECR', 'NEUROCIRUGIA', 'ADMIN', TO_DATE('03/11/2019 15:13:15', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 15:13:20', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'NECR', 'MEDI', 'NEUROCIRUGIA', 
    '15', NULL, NULL, '01', '40');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('NEUI', 'NEUROLOGIA INFANTIL', 'ADMIN', TO_DATE('03/11/2019 15:14:29', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 15:14:33', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'NEUI', 'MEDI', 'NEUROLOGIA INFANTIL', 
    '15', NULL, NULL, '01', '42');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('ONCO', 'ONCOLOGIA MEDICA', 'ADMIN', TO_DATE('03/11/2019 15:16:32', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 15:16:37', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'ONCO', 'MEDI', 'ONCOLOGIA MEDICA', 
    '15', NULL, NULL, '01', '45');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('PSII', 'PSIQUIATRIA INFANTIL Y ADOLESC', 'ADMIN', TO_DATE('03/11/2019 15:21:16', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 15:21:20', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'PSII', 'MEDI', 'PSIQUIATRIA INFANTIL Y ADOLESC', 
    '15', NULL, NULL, '01', '49');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('RAON', 'RADIOTERAPIA ONCOLOGICA', 'ADMIN', TO_DATE('03/11/2019 15:22:18', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 15:22:23', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'RAON', 'MEDI', 'RADIOTERAPIA ONCOLOGICA', 
    '15', NULL, NULL, '01', '50');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('REUM', 'REUMATOLOGIA', 'ADMIN', TO_DATE('03/11/2019 15:23:29', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 15:23:34', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'REUM', 'MEDI', 'REUMATOLOGIA', 
    '15', NULL, NULL, '01', '51');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('SPUB', 'SALUD PUBLICA', 'ADMIN', TO_DATE('03/11/2019 15:24:31', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 15:24:36', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'SPUB', 'MEDI', 'SALUD PUBLICA', 
    '15', NULL, NULL, '01', '52');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('CARI', 'CARDIOLOGIA INFANTIL', 'CAPACITA', TO_DATE('03/11/2019 15:27:13', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 15:27:18', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'CARI', 'MEDI', 'CARDIOLOGIA INFANTIL', 
    '15', NULL, NULL, '01', '55');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('CIRD', 'CIRUGIA DIGESTIVA', 'ADMIN', TO_DATE('03/11/2019 15:28:05', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 15:28:09', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'CIRD', 'MEDI', 'CIRUGIA DIGESTIVA', 
    '15', NULL, NULL, '01', '56');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('INFI', 'INFECTOLOGIA INFANTIL', 'ADMIN', TO_DATE('03/11/2019 15:32:35', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 15:32:40', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'INFI', 'MEDI', 'INFECTOLOGIA INFANTIL', 
    '15', NULL, NULL, '01', '60');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('MEFI', 'MEDICINA FAMILIAR DEL NIÑO', 'ADMIN', TO_DATE('03/11/2019 15:33:24', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 15:33:29', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'MEFI', 'MEDI', 'MEDICINA FAMILIAR DEL NIÑO', 
    '15', NULL, NULL, '01', '61');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('NTII', 'NUTRIOLOGIA INFANTIL', 'ADMIN', TO_DATE('03/11/2019 15:35:05', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 15:35:09', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'NTII', 'MEDI', 'NUTRIOLOGIA INFANTIL', 
    '15', NULL, NULL, '01', '64');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('REUI', 'REUMATOLOGIA INFANTIL', 'ADMIN', TO_DATE('03/11/2019 15:36:15', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 15:36:20', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'REUI', 'MEDI', 'REUMATOLOGIA INFANTIL', 
    '15', NULL, NULL, '01', '65');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('UROI', 'UROLOGIA INFANTIL', 'ADMIN', TO_DATE('03/11/2019 15:37:19', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 15:37:24', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'UROI', 'MEDI', 'UROLOGIA INFANTIL', 
    '15', NULL, NULL, '01', '68');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('TRAI', 'TRAUMATOLOGIA INFANTIL', 'ADMIN', TO_DATE('03/11/2019 15:38:55', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 15:38:59', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'TRAI', 'MEDI', 'TRAUMATOLOGIA INFANTIL', 
    '15', NULL, NULL, '01', '67');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('CIPI', 'CIRUGIA PLASTICA Y REP PEDIATR', 'ADMIN', TO_DATE('03/11/2019 15:39:43', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 15:39:47', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'CIPI', 'MEDI', 'CIRUGIA PLASTICA Y REP PEDIATR', 
    '15', NULL, NULL, '01', '57');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('HEMI', 'HEMATO-ONCOLOGIA INFANTIL', 'ADMIN', TO_DATE('03/11/2019 15:41:54', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 15:42:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'HEMI', 'MEDI', 'HEMATO-ONCOLOGIA INFANTIL', 
    '15', NULL, NULL, '01', '59');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('MFRI', 'MED. FISICA Y REHABILITA INFAN', 'ADMIN', TO_DATE('03/11/2019 15:44:10', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/11/2019 15:44:14', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'MFRI', 'MEDI', 'MED. FISICA Y REHABILITA INFAN', 
    '15', NULL, NULL, '01', '62');
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('ODGE', 'ODONTOLOGO GENERAL Y ESPEC', 'ADMIN', TO_DATE('11/11/2021 12:37:11', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('11/11/2021 12:37:18', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'ODON', 'MEDI', 'ODONTOLOGO GENERAL Y ESPEC', 
    '30', NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('CIMA', 'CIRUGIA Y TRAUMA. BUCO MAXILOF', 'ADMIN', TO_DATE('03/15/2022 10:24:08', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/15/2022 10:24:13', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'CIMA', 'ODON', 'ODONTOLOGO ESPECIALISTA', 
    '16', '09-007-0', NULL, NULL, NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('ENDO', 'ENDODONCIA', 'ADMIN', TO_DATE('03/15/2022 10:26:47', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/15/2022 10:26:52', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'ENDO', 'ODON', 'ODONTOLOGO ESPECIALISTA', 
    '16', '09-007-0', NULL, NULL, NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('IMOM', 'IMAGENOLOGIA ORAL Y MAXILOFACI', 'ADMIN', TO_DATE('03/15/2022 10:28:39', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/15/2022 10:28:47', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'IMOM', 'ODON', 'ODONTOLOGO ESPECIALISTA', 
    '16', '09-007-0', NULL, NULL, NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('IMBU', 'IMPLANTOLOGIA BUCO MAXILOFACI', 'ADMIN', TO_DATE('03/15/2022 10:30:38', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/15/2022 10:30:43', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'IMBU', 'ODON', 'ODONTOLOGO ESPECIALISTA', 
    '16', '09-007-0', NULL, NULL, NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('OPED', 'ODONTOPEDIATRIA', 'ADMIN', TO_DATE('03/15/2022 10:31:57', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/15/2022 10:32:01', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'OPED', 'ODON', 'ODONTOLOGO ESPECIALISTA', 
    '16', '09-007-0', NULL, NULL, NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('OROR', 'ORTODONCIA Y ORTOPEDIA DENTO M', 'ADMIN', TO_DATE('03/15/2022 10:33:35', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/15/2022 10:33:40', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'OROR', 'ODON', 'ODONTOLOGO ESPECIALISTA', 
    '16', '09-007-0', NULL, NULL, NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('PERI', 'PERIODONCIA', 'ADMIN', TO_DATE('03/15/2022 10:34:30', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/15/2022 10:34:38', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'PERI', 'ODON', 'ODONTOLOGO ESPECIALISTA', 
    '16', '09-007-0', NULL, NULL, NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('REOR', 'REHABILITACION ORAL', 'ADMIN', TO_DATE('03/15/2022 10:35:31', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/15/2022 10:35:36', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'REOR', 'ODON', 'ODONTOLOGO ESPECIALISTA', 
    '16', '09-007-0', NULL, NULL, NULL);
Insert into ADMIN.GG_TPROFESION
   (COD_TPROFE, NOM_TPROFE, COD_USUARI, FEC_AUDITA, IND_ESTADO, 
    FEC_USRCREA, COD_USRCREA, COD_GRUPO, COD_ARPROF, DESC_PROFESION, 
    IND_TIPOATENCION, COD_PRESTACION, NUM_ESPECIDEIS, TIPO_PROFESIONDEIS, TIPO_ESPECIALIDAD)
 Values
   ('TEMP', 'TRASTORNOS TEMPOMANDIBULARES', 'ADMIN', TO_DATE('03/15/2022 10:38:30', 'MM/DD/YYYY HH24:MI:SS'), 'V', 
    TO_DATE('03/15/2022 10:38:36', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 'TEMP', 'ODON', 'ODONTOLOGO ESPECIALISTA', 
    '16', '09-007-0', NULL, NULL, NULL);



CREATE TABLE ADMIN_GG_TPROFESIONAL (
  ID_PROFESIONAL INT,
  COD_PROMED VARCHAR(4),
  NOM_APEPAT VARCHAR(20),
  NOM_APEMAT VARCHAR(20),
  NOM_NOMBRE VARCHAR(25),
  COD_RUTPRO INT,
  COD_DIGVER VARCHAR(1),
  COD_TPROFE VARCHAR(5),
  COD_USUARI VARCHAR(60),
  FEC_AUDITA DATE,
  IND_ESTADO VARCHAR(1),
  COD_EMPRESA VARCHAR(5),
  EMAILMED VARCHAR(60),
  NUM_TELEFOMED VARCHAR(12),
  COD_TPROFENEW VARCHAR(4),
  COD_USRCREA VARCHAR(60),
  FEC_USRCREA DATE,
  COD_ESPECIALIDAD VARCHAR(5),
  IND_SEXO VARCHAR(1),
  FEC_NACIMI DATE,
  PRIMARY KEY (ID_PROFESIONAL)
);


CREATE TABLE ADMIN_AP_TPROFXESTABL (
  COD_RUTPRO INT,
  COD_EMPRESA VARCHAR(5),
  COD_USRCREA VARCHAR(60),
  FEC_USRCREA DATE,
  IND_ESTADO VARCHAR(1),
  IND_PROGRAMACION INT
);

CREATE TABLE ADMIN_AP_TPOLIXPROFESIONAL (
  COD_POLI VARCHAR(3),
  COD_RUTPRO INT,
  COD_USRCREA VARCHAR(60),
  FEC_USRCREA DATE,
  IND_ESTADO VARCHAR(1),
  COD_EMPRESA VARCHAR(5),
  COD_USUARI VARCHAR(60),
  FEC_AUDITA DATE
);


CREATE TABLE ADMIN_AP_TTIPATEXPOLI (
  IND_TIPOATENCION VARCHAR(2),
  COD_POLI VARCHAR(3),
  NUM_RENDIMIENTO INT,
  NUM_RENDMAX INT,
  COD_USRCREA VARCHAR(60),
  FEC_USRCREA DATE,
  COD_USUARI VARCHAR(60),
  FEC_AUDITA DATE,
  IND_ESTADO VARCHAR(1),
  IND_TIPORENDIMIENTO VARCHAR(1),
  IND_AGENDANUEVA INT,
  ID_TIPATEXPOLI INT
);

    

DELIMITER //
