Insert into ADMIN.GG_TSERVICIOXEMP
   (ID_SERDEP, COD_EMPRESA, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    IND_MED, AF_ID_AREAFUNCIONAL, IND_ARCHIVO, IND_MUESTRALAB)
 Values
   (215, '800', 'ADMIN', STR_TO_DATE('06/27/2013 16:10:32', '%m/%d/%Y %H:%i:%s'), 'V',  1, NULL, 1, 1);


Insert into ADMIN.GG_TSERVICIOXEMP
   (ID_SERDEP, COD_EMPRESA, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    IND_MED, AF_ID_AREAFUNCIONAL, IND_ARCHIVO, IND_MUESTRALAB)
 Values
   (112, '801', 'ADMIN', STR_TO_DATE('10/06/2025 16:10:32', '%m/%d/%Y %H:%i:%s'), 'V',  1, NULL, 1, 1);

Insert into ADMIN.GG_TSERVICIOXEMP
   (ID_SERDEP, COD_EMPRESA, COD_USRCREA, FEC_USRCREA, IND_ESTADO, 
    IND_MED, AF_ID_AREAFUNCIONAL, IND_ARCHIVO, IND_MUESTRALAB)
 Values
   (80, '801', 'ADMIN', STR_TO_DATE('10/06/2025 16:10:32', '%m/%d/%Y %H:%i:%s'), 'V',  1, NULL, 1, 1);

