CREATE TABLE ADMIN.PB_SOLICITUD_HISTO (
  ID_SOLICITUD_HISTO INT NOT NULL AUTO_INCREMENT,
  NUM_FICHAE INT,
  COD_USRCREA INT,
  FEC_USRCREA DATETIME,
  COD_EMPRESA VARCHAR(25),
  DES_SITIOEXT VARCHAR(255),
  DES_UBICACION VARCHAR(255),
  DES_TAMANNO VARCHAR(255),
  ID_TIPO_LESION INT,
  ID_ASPECTO INT,
  ID_ANT_PREVIOS INT,
  NUM_ANTECEDENTES VARCHAR(10),
  DES_BIPSIA TEXT,
  DES_CITOLOGIA TEXT,
  DES_OBSERVACIONES TEXT,
  IND_ESTADO INT,
  FEC_REVISION DATETIME,
  ID_TABLA INT,
  DES_TIPOMUESTRA VARCHAR(255),
  NUM_SUBNUMERACION INT,
  COD_USRCREA_TO_MUE INT,
  FEC_USRCREA_TO_MUE DATETIME,
  COD_USRCREA_ENV INT,
  FEC_USRCREA_ENV DATETIME,
  COD_USRCREA_RECEP INT,
  FEC_USRCREA_RECEP DATETIME,
  COD_EMPRESA_RECEP VARCHAR(5),
  COD_USRCREA_INFORMADA INT,
  FEC_USRCREA_INFORMADA DATETIME,
  COD_EMPRESA_INFORMADA VARCHAR(5),
  ID_ARCHIVO_SUBIDO INT,
  COD_USRCREA_RECH INT,
  FEC_USRCREA_RECH DATETIME,
  COD_EMPRESA_RECH VARCHAR(5),
  TIPO_RECHAZO INT,
  OBS_RECHAZO TEXT,
  ID_HISTO_ESTADO INT DEFAULT 1,
  AD_ID_ADMISION INT,
  ID_SERDEP INT,
  PA_ID_PROCARCH INT,
  IND_TIPO_BIOPSIA INT,
  IND_TEMPLATE INT,
  DATE_INICIOREGISTRO DATETIME,
  COD_RUTPRO INT,
  TXT_DIAGNOSTICO VARCHAR(500),
  NUM_PLANTILLA INT,
  IND_USOCASSETTE INT,
  IND_INFOPOST INT,
  IND_ESTADO_MUESTRAS INT,
  LAST_USR_AUDITA VARCHAR(50),
  LAST_DATE_AUDITA DATETIME,
  ID_NUM_CARGA INT,
  ID_UID INT,
  TXT_NAMEAUDITA VARCHAR(255),
  ID_ROTULADO INT,
  IND_NOTIF_CANCER INT,
  FEC_AUDITA DATETIME,
  USR_AUDITA VARCHAR(50),
  NUM_NOTIFICACION INT,
  ID_PROFESIONAL INT,
  DATE_CHEQUEO_SOME DATETIME,
  DATE_REVISION_BD DATETIME,
  DATE_REVISION_INFORME DATETIME,
  DATE_ARCHIVADA_EN_FICHA DATETIME,
  NUM_BENEFICIARIOS INT,
  IND_MES_CRITICO INT,
  DATE_IMPRESION_INFORME DATETIME,
  DATE_ENTREGA_INFORME DATETIME,
  ID_PROFESIONAL_RECIBE_INFO INT,
  ID_PROFESIONAL_ENTREGA_INFO INT,
  NUM_PLAZO_BIOPSIA INT,
  NUM_DIAS_ENTCANCER INT,
  NUM_ASIGNACION96HRS INT,
  DATE_INICIO_CANCER DATETIME,
  DATE_FINAL_CANCER DATETIME,
  IND_ESTADIO_OLGA INT,
  TXT_DIADNOSTICO_AP TEXT,
  DATE_FECHA_MACRO DATETIME,
  DATE_FECHA_CORTE DATETIME,
  IND_COLOR_TACO INT,
  IND_ESTADO_OLGA INT,
  DATE_INTERCONSULTA DATETIME,
  NUM_CP_INTERCONSULTA INT,
  NUM_FRAGMENTOS INT,
  NUM_AZUK_ALCIAN_S INT,
  NUM_PAS_SERIADA INT,
  NUM_DIFF_SERIADA INT,
  NUM_HE_SERIADA INT,
  NUM_LAMINAS_SERIADAS INT,
  NUM_HE_RAPIDA INT,
  NUM_TACOS_CORTADOS INT,
  NUM_EXTENDIDOS INT,
  DATE_TRASLADO DATETIME,
  ID_UID_TRASLADO INT,
  ID_USER_TRASLADO VARCHAR(50),
  ID_UID_TRASPORTE_OK INT,
  ID_UID_RECEPCIONA_OK INT,
  COD_SESSION_RECEPCIONA VARCHAR(50),
  ID_HISTO_ZONA INT DEFAULT 0,
  TXT_DESC_MACROSCOPICA TEXT,
  DATE_STAR_SALA_PROCESO DATETIME,
  DATE_END_SALA_PROCESO DATETIME,
  ID_UID_INICIO_SPROCESO INT,
  IND_SALA_PROCESO INT,
  ID_UID_FINAL_SPROCESO INT,
  IND_TEC_INCLUCION INT,
  IND_TEC_CORTE INT,
  IND_TEC_TINCION INT,
  IND_ALL_TECNICAS INT,
  ID_UID_RECHAZA INT,
  TXT_OBS_RECHAZA VARCHAR(256),
  ID_UID_CANCELA INT,
  FEC_CANCELA DATETIME,
  NUM_INTERNO_AP INT,
  DATE_AUDITA_ADMINISTRATIVO DATETIME,
  IND_GEST_ADMINISTRATIVO INT,
  ID_UID_ADMINISTRATIVO INT,
  DATE_FECHA_DIAGNOSTICO DATETIME,
  IND_CONF_CANCER INT,
  CI_ID_CITACION INT,
  IND_TIPOSECUENCIA INT,
  TXT_CITOLOGICO TEXT,
  NUM_CO_CITOLOGIA INT,
  NUM_CO_PAP INT,
  TXT_DIAG_CITOLOGIA TEXT,
  ID_PROFESIONAL_CITOLOGICO INT,
  IND_TIPO_INFORME INT DEFAULT 0,
  NUM_NOF_CANCER INT,
  IND_CONF_PAG INT DEFAULT 0,
  IND_DERIVACION_IC INT DEFAULT 0,
  ID_SIC INT,
  COD_ESTABLREF VARCHAR(50),
  IND_TIPO_PROCESO INT DEFAULT 0,
  IND_NOTIFICACANCER TINYINT DEFAULT 0,
  DATE_NOTIFICACANCER DATETIME,
  IND_TIPO_NOTIFICACION INT,
  ID_UID_NOTIFICA_CANCER INT,
  ID_UID_RC_NOTIFICA_CANCER INT,
  IND_SOLICITUD_EDITADA INT,
  IND_PROBLEMA_SOL INT,
  ID_UID_CUSTODIA INT,
  DATE_LAST_CUSTODIA DATETIME,
  ID_UID_TECNICAS INT,
  USR_TECNICAS INT,
  DATE_TECNICAS DATETIME,
  ID_ROTULADO_SUB INT,
  DATE_MACROSCOPIA DATETIME,
  USER_MACROSCOPICA VARCHAR(50),
  PRIMARY KEY (ID_SOLICITUD_HISTO)
);
CREATE TABLE ADMIN.PB_INFOROTULADO (
  ID_ROTULADO INT NOT NULL AUTO_INCREMENT,
  COD_EMPRESA VARCHAR(50),
  TXT_OBSERVACION VARCHAR(255),
  IND_ESTADO INT,
  IND_GESPAB INT,
  IND_ZONA_GESPAB VARCHAR(50),
  ID_SERDEP INT,
  IND_ESTADISTICA INT DEFAULT 0,
  PRIMARY KEY (ID_ROTULADO)
);

CREATE TABLE ADMIN.PB_MAIN_BLG_ANATOMIA (
  ID_MAIN INT NOT NULL,
  ID_SOLICITUD_HISTO INT,
  COD_EMPRESA VARCHAR(50),
  SIZE_BLG INT,
  CONTEXT_TYPE VARCHAR(100),
  MAIN_BLOB BLOB,
  IND_ESTADO INT,
  IMG_DATA TEXT,
  NAME_IMG VARCHAR(100),
  TXT_OBSERVACIONES VARCHAR(1000),
  BFILE BLOB,  
  NCLOB TEXT,  
  ID_UID INT,
  USR_CREA VARCHAR(50),
  DATE_CREA DATETIME,
  USR_AUDITA VARCHAR(50),
  DATE_AUDITA DATETIME,
  ID_HISTO_ZONA INT,
  PRIMARY KEY (ID_MAIN)
);

CREATE TABLE ADMIN.PB_IMG_APMUESTRAS (
  ID_MAIN INT NOT NULL,
  ID_SOLICITUD_HISTO INT,
  ID_HISTO_ZONA INT,
  ID_NMUESTRA INT,
  ID_CASETE INT,
  COD_EMPRESA VARCHAR(50),
  SIZE_BLG INT,
  CONTEXT_TYPE VARCHAR(100),
  MAIN_BLOB BLOB,
  IND_ESTADO INT,
  IMG_DATA TEXT, 
  NAME_IMG VARCHAR(100),
  TXT_OBSERVACIONES VARCHAR(1000),
  BFILE BLOB,  
  NCLOB TEXT, 
  ID_UID INT,
  USR_CREA VARCHAR(50),
  DATE_CREA DATETIME,
  USR_AUDITA VARCHAR(50),
  DATE_AUDITA DATETIME,
  PRIMARY KEY (ID_MAIN)
);

CREATE TABLE ADMIN.PB_FIRMAMEDICO (
  ID_FRMEDI INT NOT NULL AUTO_INCREMENT,
  ID_PROFESIONAL INT,
  IND_ESTADO INT,
  COD_CREA VARCHAR(50),
  DATE_CREA DATETIME,
  COD_AUDITA VARCHAR(50),
  DATE_AUDITA DATETIME,
  COD_EMPRESA VARCHAR(50),
  SIZE_BLG INT,
  CONTEXT_TYPE VARCHAR(100),
  MAIN_BLOB BLOB,
  IMG_DATA TEXT, 
  NAME_IMG VARCHAR(100),
  TXT_OBSERVACIONES VARCHAR(1000),
  BFILE_F BLOB,  
  NCLOB_F TEXT, 
  PRIMARY KEY (ID_FRMEDI)
);

CREATE TABLE ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (
  ID_AUTOCOMPLETADO INT NOT NULL AUTO_INCREMENT,
  TXT_CHARACTER VARCHAR(500),
  TXT_REALNAME VARCHAR(500),
  IND_ESTADO INT,
  PRIMARY KEY (ID_AUTOCOMPLETADO)
);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (1, 'ESÓFAGO DISTAL', '1', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (2, 'ESÓFAGO MEDIO', '2', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (3, 'ESÓFAGO PROXIMAL', '3', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (4, 'PÓLIPO', '4', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (5, 'CARDIAS', '5', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (6, 'ANTRO I', '6', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (7, 'ANTRO II', '7', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (8, 'ANGULO', '8', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (9, 'CUERPO I', '9', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (10, 'CUERPO II', '10', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (11, 'LESIÓN DE CUERPO', '11', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (12, 'OBS. NEOPLASIA', '12', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (13, 'ÚLCERA', '13', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (14, 'EROSIÓN', '14', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (15, 'ESÓFAGO DE BARRETT', '15', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (16, 'ILEÓN', '16', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (17, 'YEYUNO', '17', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (18, 'DUODENO', '18', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (19, 'PAPILA DUODENAL', '19', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (20, 'CIEGO', '20', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (21, 'COLON ASCENDENTE', '21', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (22, 'COLON TRANSVERSO', '22', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (23, 'COLON DESCENDENTE', '23', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (24, 'COLON SIGMOIDE', '24', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (25, 'RECTO', '25', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (26, 'PÓLIPO ADENOMATOSO', '26', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (27, 'PÓLIPO HIPERPLÁSICO', '27', 1);

INSERT INTO ADMIN.PB_NMUESTRA_AUTOCOMPLETADO (ID_AUTOCOMPLETADO, TXT_CHARACTER, TXT_REALNAME, IND_ESTADO)
VALUES (28, 'PÓLIPO GÁSTRICO', '28', 1);

CREATE TABLE ADMIN.PB_INFOROTULADO_SUB (
  ID_ROTULADO_SUB INT NOT NULL AUTO_INCREMENT,
  ID_ROTULADO INT,
  COD_EMPRESA VARCHAR(50),
  TXT_OBSERVACION VARCHAR(1000),
  IND_ESTADO TINYINT,
  DATE_CREA DATE,
  ID_UID INT,
  DATE_AUDITA DATE,
  ID_UID_AUDITA INT,
  PRIMARY KEY (ID_ROTULADO_SUB)
);

CREATE TABLE ADMIN.PB_HISTO_NMUESTRAS (
  ID_NMUESTRA INT NOT NULL AUTO_INCREMENT,
  ID_SOLICITUD_HISTO INT,
  N_MUESTRA INT,
  TXT_MUESTRA VARCHAR(50),
  IND_ESTADO INT,
  USR_CREA VARCHAR(50),
  DATE_CREA DATE,
  USR_AUDITA VARCHAR(50),
  DATE_AUDITA DATE,
  ID_TABLA INT,
  IND_ETIQUETA INT,
  IND_ESTADO_REG INT,
  IND_TIPOMUESTRA INT,
  NUM_ML INT,
  NUM_CASSETTE INT,
  ID_CASETE INT,
  IND_ESTADO_CU INT,
  ID_NUM_CARGA INT,
  TXT_DESC_MACROSCOPICA VARCHAR(4000),
  TXT_DESC_MICROSCOPICA VARCHAR(4000),
  USR_AUDITA_ANALITICO VARCHAR(50),
  DATE_AUDITA_ANALITICO DATE,
  DATE_MACROSCOPIA DATE,
  USER_MACROSCOPICA VARCHAR(50),
  PRIMARY KEY (ID_NMUESTRA)
);

CREATE TABLE ADMIN.PB_LINETIME_HISTO (
  ID_LINETIMEHISTO INT NOT NULL AUTO_INCREMENT,
  ID_NUM_CARGA INT,
  ID_SOLICITUD_HISTO INT,
  TXT_BACODE VARCHAR(1000),
  NUM_FASE INT,
  IND_CHECKED INT,
  USR_CREA VARCHAR(50),
  FEC_CREA DATETIME,
  IND_ESTADO INT,
  ID_NMUESTRA INT,
  ID_UID INT,
  TXT_MUESTRA VARCHAR(50),
  ID_CASETE INT,
  PRIMARY KEY (ID_LINETIMEHISTO)
);

CREATE TABLE ADMIN.PB_TABLAOPERATORIA (
  ID_TABLA INT NOT NULL AUTO_INCREMENT,
  NUM_FICHAE INT,
  ID_PROGRAMA_CIRUGIA INT,
  ID_TIPO_PACIENTE INT,
  ID_REINTERVENCION INT,
  ID_GES INT,
  ID_TIPO_OP INT,
  ID_SITUACION INT,
  ID_CANCELACION INT,
  ID_PROCEDENCIA INT,
  ID_CAMA INT,
  ID_REPROGRAMACION INT,
  COD_PABELLON VARCHAR(50),
  FEC_INICIO_SOLICITUD DATETIME,
  FEC_FIN_SOLICITUD DATETIME,
  TXT_HIPO_DIAG VARCHAR(500),
  TXT_POSTOPERATORIO VARCHAR(500),
  NUM_DURACION INT,
  COD_UNIDAD INT,
  ID_ANESTESIA INT,
  TXT_INTERVENCION_SC VARCHAR(255),
  ID_NEC_EVA_PREO VARCHAR(255),
  ID_PRD_SAN INT,
  ID_RESER_PRD_SAN INT,
  ID_RAYOS INT,
  ID_TORRE_LAPA INT,
  ID_POST_OPE INT,
  IND_PABELLON VARCHAR(500),
  IND_TXTSOME VARCHAR(255),
  ID_OPERADO INT,
  ID_ORIGEN VARCHAR(50),
  NUM_REFERENCIA INT,
  ID_ASA VARCHAR(50),
  ID_SUSPENSION INT,
  ID_ORIGENSOL INT,
  TXT_DATELLE_SOLICITUD VARCHAR(500),
  IND_COMPRASERVICIO INT,
  TXT_DES_INTERVENCION VARCHAR(500),
  TXT_ALUMNO VARCHAR(100),
  IND_RECUENTO_COMPRESAS INT,
  TXT_RECUENTO_COMPRESAS VARCHAR(100),
  ID_HERIDAS INT,
  TXT_PROFILAXIS VARCHAR(100),
  TXT_DESCRIPCION_QX VARCHAR(4000),
  ID_BIOPSIA INT,
  ID_CULTIVO INT,
  ID_ESTADO_TQ INT,
  COD_TESTABL VARCHAR(4),
  FECHA_CREATABLA DATETIME,
  USR_CREA VARCHAR(25),
  FEC_CREA DATETIME,
  USR_AUDITA VARCHAR(25),
  FEC_AUDITA DATETIME,
  COD_USUARIO_FIRMA VARCHAR(25),
  IND_ALUMNO INT,
  NUM_ORDEN INT,
  IND_MATERIALES INT,
  IND_RRHH INT,
  IND_INSUMOS INT,
  IND_INFOPACSUSPEN INT,
  TXT_OTROMOVSUSPENSION VARCHAR(255),
  TXT_INFOPACSUSPEN VARCHAR(255),
  IND_PAD INT,
  DATE_INGRESO_PAB DATETIME,
  DATE_INGRESO_QUIROFANO DATETIME,
  DATE_INICIO_ANESTESIA DATETIME,
  DATE_FINAL_ANESTESIA DATETIME,
  DATE_SALIDA_QUIROFANO DATETIME,
  DATE_FINAL_LIMPIEZA DATETIME,
  DATE_TERMINO_INTERVENCION DATETIME,
  DATE_INGRESO_RECUPERACION DATETIME,
  DATE_SALIDA_RECUPERACION DATETIME,
  TXT_HRSENFE VARCHAR(100),
  ID_ORIGEN_EGRESO INT,
  TXT_CIRUPROP VARCHAR(100),
  IND_TDESDESOL INT,
  IND_DERIVACION INT,
  IND_OSTEOSINTESIS INT,
  HRS_ANULACION INT,
  IND_CMA INT,
  IND_PREVIS VARCHAR(2),
  ID_SIC INT,
  AD_ID_ADMISION INT,
  AD_NUMFOLIO INT,
  ID_HOSPITALIZA INT,
  IND_TEMPLATEPROTOCOLO INT,
  IND_PACIENTE_POSICION INT,
  IND_EPISIOTOMIA INT,
  TXT_SUTURA_X_PLANOS VARCHAR(100),
  IND_LIQUIDO_AMNIOTICO INT,
  IND_DESGARROS INT,
  TXT_DESGARROS VARCHAR(100),
  TXT_SUTURA VARCHAR(100),
  IND_ALUMBRAMIENTO INT,
  IND_REV_INSTUMENTAL INT,
  NUM_PESO_PLACENTA INT,
  NUM_LONGITUD_CONDON INT,
  IND_RETRACTOR_UTERINO INT,
  TXT_RETRACTOR_UTERINO VARCHAR(100),
  MIN_EXTRACION_FETAL INT,
  IND_EMBARAZO_CONTROLADO INT,
  IND_TIPO_EMBARAZO INT,
  IND_MAIN_ACOPANANTE INT,
  IND_TIPO_ACOMPANANTE INT,
  IND_MEMBRANA_ROTA INT,
  IND_SDERIVADA INT DEFAULT 0,
  COD_EMPRESA_DERIVADA VARCHAR(50),
  PAR_IND_EPISIOTOMIA INT,
  PAR_IND_DESGARROS INT,
  PAR_PARTOACOMPANADO INT,
  IND_DESABHILITADO INT,
  PQ_IDSOL INT,
  SOL_IFRAME INT DEFAULT 0,
  PRIMARY KEY (ID_TABLA)
);

CREATE TABLE ADMIN.PB_SALA_PABELLON (
  COD_PABELLON VARCHAR(12) NOT NULL,
  IND_ESTADO VARCHAR(255),
  SALA_DESCRIPCION VARCHAR(255),
  COD_EMPRESA VARCHAR(50),
  IMPLEMENTACION VARCHAR(255),
  CUPO_PRV VARCHAR(50),
  NOM_CORTO VARCHAR(50),
  COD_CREA VARCHAR(50),
  DATE_CREA DATETIME,
  COD_AUDITA VARCHAR(50),
  FEC_AUDITA DATETIME,
  IND_ORDER INT,
  IND_TIPOPABELLON VARCHAR(10),
  IND_DISTRIBUCION_TABLA INT,
  IND_TIPOTABLA INT,
  IND_ZONA_PABELLON INT,
  PRIMARY KEY (COD_PABELLON)
);

CREATE TABLE ADMIN.PB_ANTECEDENTES_HISTO (
  ID_ANTECEDENTES_HISTO INT NOT NULL,
  ID_LINETIMEHISTO INT,
  ID_NUM_CARGA INT,
  ID_SOLICITUD_HISTO INT,
  ID_MOTIVO_DESAC INT,
  TXT_EVENTO_OBSERVACION  VARCHAR(256),
  ID_NMUESTRA INT,
  IND_ESTADO INT,
  PRIMARY KEY (ID_ANTECEDENTES_HISTO)
);

CREATE TABLE ADMIN.MOTIVOS_DESACTIVAR_M (
  ID_MOTIVO_DESAC INT,
  MOTIVO_TXT VARCHAR(20),
  DESCRIPCION VARCHAR(3000),
  IND_ESTADO INT
);

INSERT INTO ADMIN.MOTIVOS_DESACTIVAR_M (`ID_MOTIVO_DESAC`, `MOTIVO_TXT`, `DESCRIPCION`, `IND_ESTADO`) VALUES
(1,	'0', 'MUESTRA NO ENCONTRADA',	 1),
(2,	'0', 'MUESTRA EN MAL ESTADO',	1),
(3,	'0', 'MUESTRA RECHAZADA',	1);

CREATE TABLE ADMIN.PB_MUESTRAXTECNICA (
  ID_TECNICAXMUES INT NOT NULL AUTO_INCREMENT,
  ID_TECNICA_AP INT NOT NULL,
  ID_NMUESTRA INT NOT NULL,
  DATE_CREA DATETIME DEFAULT NULL,
  USR_CREA VARCHAR(50) DEFAULT NULL,
  IND_ESTADO TINYINT DEFAULT NULL,
  ID_SOLICITUD_HISTO INT DEFAULT NULL,
  DATE_AUDITA DATETIME DEFAULT NULL,
  USR_AUDITA VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (ID_TECNICAXMUES)
);

CREATE TABLE ADMIN.PB_TECNICASXMUESTRAS (
  ID_TECNICA_AP INT NOT NULL AUTO_INCREMENT,
  TXT_TECNICA_AP VARCHAR(256) DEFAULT NULL,
  IND_ESTADO TINYINT DEFAULT NULL,
  PRIMARY KEY (ID_TECNICA_AP)
);

INSERT INTO ADMIN.PB_TECNICASXMUESTRAS (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO) VALUES (1, 'DIFF', 1);
INSERT INTO ADMIN.PB_TECNICASXMUESTRAS (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO) VALUES (2, 'PAS', 1);
INSERT INTO ADMIN.PB_TECNICASXMUESTRAS (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO) VALUES (3, 'ACEN BLUE', 1);
INSERT INTO ADMIN.PB_TECNICASXMUESTRAS (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO) VALUES (4, 'HE', 1);
INSERT INTO ADMIN.PB_TECNICASXMUESTRAS (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO) VALUES (5, 'PAPANICOLAOU', 1);
INSERT INTO ADMIN.PB_TECNICASXMUESTRAS (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO) VALUES (6, 'GRAM', 1);
INSERT INTO ADMIN.PB_TECNICASXMUESTRAS (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO) VALUES (7, 'MASSON', 1);
INSERT INTO ADMIN.PB_TECNICASXMUESTRAS (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO) VALUES (8, 'VAN GEISON', 1);
INSERT INTO ADMIN.PB_TECNICASXMUESTRAS (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO) VALUES (9, 'OLI RED', 1);
INSERT INTO ADMIN.PB_TECNICASXMUESTRAS (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO) VALUES (10, 'ZIEHL NELSEN', 1);
INSERT INTO ADMIN.PB_TECNICASXMUESTRAS (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO) VALUES (11, 'GROCOTT', 1);
INSERT INTO ADMIN.PB_TECNICASXMUESTRAS (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO) VALUES (12, 'RETÍCULO', 1);
INSERT INTO ADMIN.PB_TECNICASXMUESTRAS (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO) VALUES (13, 'GORDON SWEET', 1);
INSERT INTO ADMIN.PB_TECNICASXMUESTRAS (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO) VALUES (14, 'WARTHIN STARRY', 1);
INSERT INTO ADMIN.PB_TECNICASXMUESTRAS (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO) VALUES (15, 'GIEMSA', 1);
INSERT INTO ADMIN.PB_TECNICASXMUESTRAS (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO) VALUES (16, 'MAY GRUNWALD GIEMSA', 1);
INSERT INTO ADMIN.PB_TECNICASXMUESTRAS (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO) VALUES (17, 'PERLS', 1);
INSERT INTO ADMIN.PB_TECNICASXMUESTRAS (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO) VALUES (18, 'ROJO CONGO', 1);
INSERT INTO ADMIN.PB_TECNICASXMUESTRAS (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO) VALUES (19, 'AZUL ALCIAN', 1);
INSERT INTO ADMIN.PB_TECNICASXMUESTRAS (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO) VALUES (20, 'VERHOFFS', 1);
INSERT INTO ADMIN.PB_TECNICASXMUESTRAS (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO) VALUES (21, 'FONTANA MASSON', 1);


CREATE TABLE ADMIN.PB_TPRESTAXANATOMIA (
    ID_TPRESTAXANATOMIA INT NOT NULL AUTO_INCREMENT,
    ID_SOLICITUD_HISTO INT NOT NULL,
    COD_PRESTA VARCHAR(50) NOT NULL,
    IND_ESTADO INT,
    USR_CREA VARCHAR(50),
    DATE_CREA DATETIME,
    USR_AUDITA VARCHAR(50),
    DATE_AUDITA DATETIME,
    PRIMARY KEY (ID_TPRESTAXANATOMIA),
    FOREIGN KEY (ID_SOLICITUD_HISTO) REFERENCES ADMIN.PB_SOLICITUD_HISTO(ID_SOLICITUD_HISTO)
);

CREATE TABLE ADMIN.PB_TORGANOXANATOMIA (
    ID_TORGANOXANATOMIA INT NOT NULL AUTO_INCREMENT,
    ID_SOLICITUD_HISTO INT,
    ID_ORGANO_AP INT,
    IND_ESTADO INT,
    USR_CREA VARCHAR(50),
    DATE_CREA DATETIME,
    DATE_AUDITA DATETIME,
    USR_AUDITA VARCHAR(50),
    PRIMARY KEY (ID_TORGANOXANATOMIA),
    FOREIGN KEY (ID_SOLICITUD_HISTO) REFERENCES ADMIN.PB_SOLICITUD_HISTO(ID_SOLICITUD_HISTO)
);

CREATE TABLE ADMIN.PB_TPATOLOGIAXANATOMIA (
    ID_TPATOLOGIAXANATOMIA INT NOT NULL AUTO_INCREMENT,
    ID_SOLICITUD_HISTO INT,
    ID_PATOLOGIA_AP INT,
    IND_ESTADO INT,
    USR_CREA VARCHAR(50),
    DATE_CREA DATETIME,
    USR_AUDITA VARCHAR(50),
    DATE_AUDITA DATETIME,
    PRIMARY KEY (ID_TPATOLOGIAXANATOMIA),
    FOREIGN KEY (ID_SOLICITUD_HISTO) REFERENCES ADMIN.PB_SOLICITUD_HISTO(ID_SOLICITUD_HISTO)
);

CREATE TABLE ADMIN.PB_TPRESTACIONXANATOMIA (
    ID_TPRESTACIONXANATOMIA INT NOT NULL AUTO_INCREMENT,
    COD_PRESTACION VARCHAR(7),
    DATE_CREA DATETIME,
    USR_CREA VARCHAR(50),
    IND_ESTADO INT,
    ID_SOLICITUD_HISTO INT,
    USR_AUDITA VARCHAR(50),
    DATE_AUDITA DATETIME,
    PRIMARY KEY (ID_TPRESTACIONXANATOMIA),
    FOREIGN KEY (ID_SOLICITUD_HISTO) REFERENCES ADMIN.PB_SOLICITUD_HISTO(ID_SOLICITUD_HISTO)
);




DELIMITER //

CREATE PROCEDURE ADMIN.CONSULTA_UNICA_ANATOMIA (IN `p_id_solicitud_histo` INT, IN `p_cod_empresa` INT)

BEGIN
    SELECT 


    P.IND_NOTIF_CANCER AS IND_NOTIF_CANCER,
    
    DATE_FORMAT(P.DATE_INICIO_CANCER,'%d-%m-%Y') AS DATE_FECHA_REALIZACION2,
    DATE_FORMAT(P.DATE_INICIO_CANCER,'%H:%i') AS DATE_FECHA_REALIZACION21,
    DATE_FORMAT(P.DATE_FINAL_CANCER,'%d-%m-%Y') AS DATE_FECHA_REALIZACION3,
    DATE_FORMAT(P.DATE_FINAL_CANCER,'%H:%i') AS DATE_FECHA_REALIZACION32,
    P.NUM_DIAS_ENTCANCER AS NUM_DIAS_ENTCANCER,
    P.NUM_ASIGNACION96HRS AS NUM_ASIGNACION96HRS,


    P.IND_TEC_INCLUCION AS IND_TEC_INCLUCION,
    P.IND_TEC_CORTE AS IND_TEC_CORTE,
    P.IND_TEC_TINCION AS IND_TEC_TINCION,
    DATE_FORMAT(P.DATE_FECHA_MACRO, '%d-%m-%Y') AS FECHA_FECHA_MACRO,
    DATE_FORMAT(P.DATE_FECHA_CORTE, '%d-%m-%Y') AS FECHA_FECHA_CORTE,
    P.IND_COLOR_TACO AS IND_COLOR_TACO,
    DATE_FORMAT(P.DATE_INTERCONSULTA,'%d-%m-%Y') AS DATE_INTERCONSULTA,
    P.IND_ESTADO_OLGA AS IND_ESTADO_OLGA,
    P.IND_ESTADO_OLGA AS IND_ESTADIO_OLGA_TEC,
    P.NUM_CP_INTERCONSULTA AS NUM_CP_INTERCONSULTA,
    P.NUM_FRAGMENTOS AS NUM_FRAGMENTOS,
    P.NUM_TACOS_CORTADOS AS NUM_TACOS_CORTADOS,
    P.NUM_EXTENDIDOS AS NUM_EXTENDIDOS,
    P.IND_TIPO_PROCESO AS IND_TIPO_PROCESO,   
    P.ID_HISTO_ZONA AS VAL_HISTO_ZONA,
    P.COD_EMPRESA AS COD_EMPRESA,
    DATE_FORMAT(IFNULL(P.DATE_STAR_SALA_PROCESO, NOW()), '%d-%m-%Y') AS TIME_DIA,
    DATE_FORMAT(IFNULL(P.DATE_STAR_SALA_PROCESO, NOW()), '%H:%i') AS TIME_HORA,
    DATE_FORMAT(IFNULL(P.DATE_END_SALA_PROCESO, NOW()), '%d-%m-%Y') AS TIME_DIA_FINAL,
    DATE_FORMAT(IFNULL(P.DATE_END_SALA_PROCESO, NOW()), '%H:%i') AS TIME_HORA_FINAL,
    CASE WHEN P.ID_ROTULADO_SUB = '' THEN '' ELSE CONCAT(' / ', (
        SELECT F.TXT_OBSERVACION 
        FROM ADMIN.PB_INFOROTULADO_SUB F
        WHERE F.ID_ROTULADO_SUB = P.ID_ROTULADO_SUB LIMIT 1 )) END AS TXT_SUBDIVISION,
    CASE WHEN P.COD_EMPRESA IN ('100','303','301','304','300','103','102','105') THEN 'H.MAURICIO HEYERMANN T.ANGOL'
        WHEN P.COD_EMPRESA IN ('106','318','104','108','107','302') THEN 'SAN JOSE DE VICTORIA'
        ELSE 'SERVICIO DE SALUD ARAUCANIA NORTE'
    END AS TXT_HOSPDERIVADO,
    CASE WHEN P.COD_EMPRESA IN ('100','303','301','304','300','103','102','105') THEN '100'
        WHEN P.COD_EMPRESA IN ('106','318','104','108','107','302') THEN '106'
        ELSE '029'
    END AS COD_EMPRESA_DERIVADA,
    CASE WHEN P.COD_ESTABLREF = p_cod_empresa THEN (
            SELECT G.NOM_RAZSOC
            FROM ADMIN.SS_TEMPRESAS G
            WHERE G.COD_EMPRESA = P.COD_EMPRESA LIMIT 1
        )
        ELSE ''
    END AS TXT_EMPRESA_DERIVADA,
    IF(P.IND_USOCASSETTE = '1', 'SI', IF(P.IND_USOCASSETTE = '0', 'NO', '--')) AS TXT_USOCASSETTE,
    P.IND_USOCASSETTE,
    P.IND_TEMPLATE AS TXT_PLANTILLA,
    DATE_FORMAT(P.DATE_NOTIFICACANCER, '%d-%m-%Y %H:%i') AS DATE_NOTIFICACANCER,
    (SELECT CONCAT(F.FIRST_NAME, ' ', F.MIDDLE_NAME, ' ', F.LAST_NAME) 
    FROM ADMIN.FE_USERS F
    WHERE F.ID_UID = P.ID_UID_RC_NOTIFICA_CANCER LIMIT 1) AS TXT_NOTIFICA_CANCER,
    (SELECT CONCAT(F.FIRST_NAME, ' ', F.MIDDLE_NAME, ' ', F.LAST_NAME) 
    FROM ADMIN.FE_USERS F
    WHERE F.ID_UID = P.ID_UID_NOTIFICA_CANCER LIMIT 1) AS TXT_RECIBE_NOTIFICA_CANCER,
    CASE
        WHEN P.ID_HISTO_ZONA = 8 THEN (
            SELECT F.IMG_DATA 
            FROM ADMIN.PB_FIRMAMEDICO F
            WHERE F.IND_ESTADO = 1 AND F.ID_PROFESIONAL = P.ID_PROFESIONAL LIMIT 1
        )
        ELSE NULL
    END AS CLOB_FIRMA,
    CASE
        WHEN P.IND_TIPO_BIOPSIA = 4 AND P.ID_HISTO_ZONA = 8 THEN (
            SELECT F.IMG_DATA 
            FROM ADMIN.PB_FIRMAMEDICO F
            WHERE F.IND_ESTADO = 1 AND F.ID_PROFESIONAL = P.ID_PROFESIONAL_CITOLOGICO LIMIT 1
        )
        ELSE NULL
    END AS CLOB_FIRMA_CITO,
    P.IND_CONF_CANCER,
    P.NUM_NOF_CANCER,
    P.IND_CONF_PAG,
    P.TXT_DIAG_CITOLOGIA,
    P.NUM_CO_CITOLOGIA,
    P.NUM_CO_PAP,
    IFNULL(P.NUM_INTERNO_AP, 0) AS NUM_INTERNO_AP,
    P.TXT_CITOLOGICO,
    
    (SELECT CONCAT(UPPER(PAT.NOM_NOMBRE), ' ', UPPER(PAT.NOM_APEPAT), ' ', UPPER(PAT.NOM_APEMAT), '<br>', PAT.COD_RUTPRO, '-', PAT.COD_DIGVER)
    FROM ADMIN.GG_TPROFESIONAL PAT
    WHERE PAT.ID_PROFESIONAL = P.ID_PROFESIONAL LIMIT 1) AS TXT_USER_PATOLOGO,

    (SELECT CONCAT(UPPER(PAT.NOM_NOMBRE), ' ', UPPER(PAT.NOM_APEPAT), ' ', UPPER(PAT.NOM_APEMAT), '<br>', PAT.COD_RUTPRO, '-', PAT.COD_DIGVER)
    FROM ADMIN.GG_TPROFESIONAL PAT
    WHERE PAT.ID_PROFESIONAL = P.ID_PROFESIONAL_CITOLOGICO LIMIT 1) AS TXT_USER_PATOLOGO_CITOLOGICO,

    P.TXT_DESC_MACROSCOPICA AS TXT_DESC_MACROSCOPICA,
    P.TXT_DIADNOSTICO_AP AS TXT_DIADNOSTICO_AP,
    '' AS TXT_DESC_CITOLOGICO,
    P.TXT_DESC_MACROSCOPICA AS TXT_DESC_MACROSCOPICA,
    (SELECT CONCAT(F.FIRST_NAME, ' ', F.MIDDLE_NAME, ' ', F.LAST_NAME, '#', F.USERNAME)
    FROM ADMIN.FE_USERS F
    WHERE F.ID_UID = P.ID_UID_TRASPORTE_OK LIMIT 1) AS TXT_USER_TRASPORTE_FIRMA,
    (SELECT CONCAT(F.FIRST_NAME, ' ', F.MIDDLE_NAME, ' ', F.LAST_NAME, '#', F.USERNAME)
    FROM ADMIN.FE_USERS F
    WHERE F.ID_UID = P.ID_UID_RECEPCIONA_OK LIMIT 1) AS TXT_USER_RECPCIONA_FIRMA,
    P.ID_UID_RECEPCIONA_OK,
    DATE_FORMAT(P.DATE_TRASLADO, '%d-%m-%Y') AS FECHA_TRASLADO,
    DATE_FORMAT(P.DATE_TRASLADO, '%H:%i') AS HORA_TRASLADO,
    P.ID_UID_TRASLADO,
    P.ID_USER_TRASLADO,
    (SELECT CONCAT(F.FIRST_NAME, ' ', F.MIDDLE_NAME, ' ', F.LAST_NAME) 
    FROM ADMIN.FE_USERS F
    WHERE F.ID_UID = P.ID_UID_TRASLADO LIMIT 1) AS TXT_USER_TRASPORTE,
    S.NOM_RAZSOC AS TXT_HOSPITAL_ETI,
    (SELECT CONCAT(F.FIRST_NAME, ' ', F.MIDDLE_NAME, ' ', F.LAST_NAME) 
    FROM ADMIN.PB_LINETIME_HISTO L, ADMIN.FE_USERS F
    WHERE L.ID_SOLICITUD_HISTO = P.ID_SOLICITUD_HISTO
    AND L.IND_ESTADO = 1
    AND L.NUM_FASE = 2
    AND L.ID_UID = F.ID_UID LIMIT 1) AS TXT_USER_TRASPORTE,
    (SELECT CONCAT(F.FIRST_NAME, ' ', F.MIDDLE_NAME, ' ', F.LAST_NAME) 
    FROM ADMIN.PB_LINETIME_HISTO L, ADMIN.FE_USERS F
    WHERE L.ID_SOLICITUD_HISTO = P.ID_SOLICITUD_HISTO
    AND L.IND_ESTADO = 1
    AND L.NUM_FASE = 3
    AND L.ID_UID = F.ID_UID LIMIT 1) AS TXT_USER_RECEPCION,
    (SELECT COUNT(M.ID_NMUESTRA) FROM ADMIN.PB_HISTO_NMUESTRAS M
    WHERE M.ID_SOLICITUD_HISTO = P.ID_SOLICITUD_HISTO
    AND M.IND_ESTADO = 1) AS N_MUESTRAS,
    DATE_FORMAT(NOW(), '%d-%m-%Y %H:%i') AS FEC_EMISION,
    CONCAT(L.COD_RUTPAC, '-', L.COD_DIGVER, ' ', L.NUM_IDENTIFICACION) AS RUTPACIENTE,

    L.COD_RUTPAC AS COD_RUTPAC,
    L.COD_DIGVER AS COD_DIGVER,
    L.NUM_IDENTIFICACION AS NUM_IDENTIFICACION,

    L.IND_TISEXO AS IND_TISEXO,
    FLOOR(TIMESTAMPDIFF(MONTH, L.FEC_NACIMI, NOW()) / 12) AS NUMEDAD,
    DATE_FORMAT(L.FEC_NACIMI, '%d-%m-%Y') AS NACIMIENTO,
    FLOOR(TIMESTAMPDIFF(MONTH, L.FEC_NACIMI, NOW()) / 12) AS EDAD,
    CONCAT(UPPER(L.NOM_NOMBRE), ' ', UPPER(L.NOM_APEPAT), ' ', UPPER(L.NOM_APEMAT), 
        CASE WHEN L.NOM_SOCIAL IS NULL THEN '' ELSE CONCAT(', social: ', L.NOM_SOCIAL) END) AS NOMBRE_COMPLETO,
    CONCAT(SUBSTR(L.NOM_NOMBRE, 1, 1), '.', UPPER(L.NOM_APEPAT), ' ', UPPER(L.NOM_APEMAT)) AS TXTNOMCIRUSMALL,
    CONCAT(UPPER(L.NOM_NOMBRE), ' ', UPPER(L.NOM_APEPAT), ' ', UPPER(SUBSTR(L.NOM_APEMAT, 1, 1))) AS TXTPRIMERNOMBREAPELLIDO,
    CASE
        WHEN P.COD_EMPRESA = 1000 THEN (
            SELECT E.NUM_NFICHA
            FROM ADMIN.SO_TCPACTE E
            WHERE E.NUM_FICHAE = P.NUM_FICHAE AND E.COD_EMPRESA = 100 LIMIT 1
        )
        ELSE (
            SELECT E.NUM_NFICHA
            FROM ADMIN.SO_TCPACTE E
            WHERE E.NUM_FICHAE = P.NUM_FICHAE AND E.COD_EMPRESA = P.COD_EMPRESA LIMIT 1
        )
    END AS FICHAL,
    
    (SELECT A.NOM_PREVIS
    FROM ADMIN.GG_TDATPREV A, ADMIN.SO_TTITUL B, ADMIN.GG_TGPACTE C, ADMIN.GG_TINSEMP D
    WHERE A.IND_PREVIS = B.IND_PREVIS
    AND B.COD_RUTTIT = C.COD_RUTTIT
    AND B.NUM_RUTINS = D.COD_RUTINS
    AND C.NUM_FICHAE = P.NUM_FICHAE
    AND A.IND_ESTADO = 'V') AS TXT_PREVISION,

    CONCAT(UPPER(G.NOM_NOMBRE), ' ', UPPER(G.NOM_APEPAT), ' ', UPPER(G.NOM_APEMAT)) AS PROFESIONAL,
    CONCAT(G.NOM_APEPAT, ' ', G.NOM_APEMAT, ' ', G.NOM_NOMBRE) AS PROFESIONAL_2,
    CONCAT(G.COD_RUTPRO, '-', G.COD_DIGVER) AS RUT_PROFESIOAL,
    G.COD_RUTPRO AS ID,
    G.COD_DIGVER AS DV,
    G.COD_TPROFE AS MEDI,
    DATE_FORMAT(P.DATE_INICIOREGISTRO, '%d-%m-%Y %H:%i') AS FECHA_SOLICITUD,
    DATE_FORMAT(P.FEC_USRCREA_RECEP, '%d-%m-%Y') AS FECHA_RECEPCION,
    DATE_FORMAT(P.FEC_USRCREA_RECEP, '%Y') AS FECHA_YEAR_RECEPCION,
    DATE_FORMAT(P.FEC_USRCREA_RECEP, '%H:%i') AS HORA_RECEPCION,
    DATE_FORMAT(P.DATE_FECHA_DIAGNOSTICO, '%d-%m-%Y %H:%i') AS DATE_FECHA_DIAGNOSTICO,
    DATE_FORMAT(P.DATE_IMPRESION_INFORME, '%d-%m-%Y') AS FECHA_IMREPSION_INFORME,
    DATE_FORMAT(P.DATE_ENTREGA_INFORME, '%d-%m-%Y %H:%i') AS FECHA_ENTREGA_INFORME,
    P.PA_ID_PROCARCH,
    CASE
        WHEN P.PA_ID_PROCARCH = '31' THEN 'PABELLÓN CENTRAL'
        WHEN P.PA_ID_PROCARCH = '63' THEN 'RCE ESPECIALIDADES'
        WHEN P.PA_ID_PROCARCH = '65' THEN 'MODULO ANATOMIA'
        ELSE 'NO INFORMADO'
    END AS TXT_PROCEDENCIA,
    CASE
        WHEN P.PA_ID_PROCARCH = '31' THEN (
            SELECT CONCAT(DATE_FORMAT(PP.FEC_INICIO_SOLICITUD, '%d-%m-%Y %H:%i'), ' - ', SS.SALA_DESCRIPCION)
            FROM ADMIN.PB_TABLAOPERATORIA PP, ADMIN.PB_SALA_PABELLON SS
            WHERE PP.COD_PABELLON = SS.COD_PABELLON AND PP.ID_TABLA = P.ID_TABLA LIMIT 1
        )
        ELSE 'NO INFORMADO'
    END AS INFO_GESPAB,
    '' AS TXT_SALAPAB,
    '' AS TXT_FECIRU,
    P.ID_SERDEP AS ID_SERVICIO,
    CASE
        WHEN P.COD_EMPRESA IN ('100','106','029','800') THEN (
            SELECT S.NOM_SERVIC
            FROM ADMIN.GG_TSERVICIOXEMP T, ADMIN.GG_TSERVICIO S
            WHERE T.ID_SERDEP = P.ID_SERDEP
            AND T.COD_EMPRESA = P.COD_EMPRESA
            AND S.ID_SERDEP = T.ID_SERDEP LIMIT 1
        )
        ELSE (
            SELECT S.NOM_SERVIC
            FROM ADMIN.GG_TSERVICIOXEMP T, ADMIN.GG_TSERVICIO S
            WHERE T.ID_SERDEP = P.ID_SERDEP
            AND T.COD_EMPRESA = P.COD_ESTABLREF
            AND S.ID_SERDEP = T.ID_SERDEP LIMIT 1
        )
    END AS NOMBRE_SERVICIO,
    P.ID_SOLICITUD_HISTO AS ID_SOLICITUD,
    P.TXT_DIAGNOSTICO AS TXT_DIAGNOSTICO,
    DATE_FORMAT(NOW(), '%d-%m-%Y %H:%i') AS FEC_EMISION,
    DATE_FORMAT(P.FEC_USRCREA, '%d-%m-%Y %H:%i') AS FECHA_SOLICITUD,
    DATE_FORMAT(P.DATE_INICIOREGISTRO, '%d-%m-%Y %H:%i') AS FECHA_TOMA_MUESTRA,
    CASE P.IND_TIPO_BIOPSIA
        WHEN '1' THEN 'SI'
        WHEN '2' THEN 'CONTEMPORANEA'
        WHEN '3' THEN 'DIFERIDA'
        WHEN '4' THEN 'BIOPSIA + CITOLOGÍA'
        WHEN '6' THEN 'CITOLOGÍA PAP'
        WHEN '5' THEN 'SOLO CITOLOGÍA'
        ELSE 'NO INFORMADO'
    END AS TIPO_DE_BIOPSIA,
    P.IND_TIPO_BIOPSIA AS IND_TIPO_BIOPSIA,
    CASE P.IND_ESTADO
        WHEN '1' THEN 'SOLICITUD ACTIVA'
        WHEN '0' THEN 'SOLICITUD DESHABILITADA'
        ELSE 'NO INFORMADA'
    END AS TXT_ESTADO,
    P.DES_SITIOEXT,
    P.DES_UBICACION,
    P.DES_TAMANNO,
    CASE P.ID_TIPO_LESION
        WHEN '1' THEN 'LIQUIDO'
        WHEN '2' THEN 'ORGANO'
        WHEN '3' THEN 'TEJIDO'
        ELSE 'NO INFORMADO'
    END AS TXT_TIPOSESION,
    CASE P.ID_ASPECTO
        WHEN '1' THEN 'INFLAMATORIA'
        WHEN '2' THEN 'BENIGNA'
        WHEN '3' THEN 'NEOPLASICA'
        ELSE 'NO INFORMADO'
    END AS TXT_ASPECTO,
    CASE P.ID_ANT_PREVIOS
        WHEN '1' THEN 'NO'
        WHEN '2' THEN 'BIOPSIA'
        WHEN '3' THEN 'CITOLOGIA'
        ELSE 'NO INFORMADO'
    END AS TXT_ANT_PREVIOS,
    P.ID_ANT_PREVIOS,
    P.NUM_ANTECEDENTES,
    P.DES_BIPSIA,
    P.DES_CITOLOGIA,
    P.DES_OBSERVACIONES,
    P.NUM_FICHAE,
    P.COD_USRCREA,
    P.FEC_USRCREA,
    P.COD_EMPRESA,
    P.DES_SITIOEXT,
    P.DES_UBICACION,
    P.DES_TAMANNO,
    P.ID_TIPO_LESION,
    P.ID_ASPECTO,
    P.ID_ANT_PREVIOS,
    P.NUM_ANTECEDENTES,
    P.DES_BIPSIA,
    P.DES_CITOLOGIA,
    P.DES_OBSERVACIONES,
    P.IND_ESTADO,
    P.FEC_REVISION,
    P.ID_TABLA,
    P.DES_TIPOMUESTRA,
    P.NUM_SUBNUMERACION,
    P.COD_USRCREA_TO_MUE,
    P.FEC_USRCREA_TO_MUE,
    P.COD_USRCREA_ENV,
    P.FEC_USRCREA_ENV,
    P.COD_USRCREA_RECEP,
    P.FEC_USRCREA_RECEP,
    P.COD_EMPRESA_RECEP,
    P.COD_USRCREA_INFORMADA,
    P.FEC_USRCREA_INFORMADA,
    P.COD_EMPRESA_INFORMADA,
    P.ID_ARCHIVO_SUBIDO,
    P.COD_USRCREA_RECH,
    P.FEC_USRCREA_RECH,
    P.COD_EMPRESA_RECH,
    P.TIPO_RECHAZO,
    P.OBS_RECHAZO,
    P.ID_HISTO_ESTADO,
    P.AD_ID_ADMISION,
    P.ID_SERDEP,
    P.IND_TIPO_BIOPSIA,
    P.IND_TEMPLATE,
    P.DATE_INICIOREGISTRO,
    P.COD_RUTPRO,
    P.TXT_DIAGNOSTICO,
    P.NUM_PLANTILLA,
    P.IND_USOCASSETTE,
    P.IND_USOCASSETTE
    
    FROM
        ADMIN.GG_TGPACTE L,
        ADMIN.GG_TPROFESIONAL G,
        ADMIN.PB_SOLICITUD_HISTO P,
        ADMIN.SS_TEMPRESAS S
    WHERE
        P.ID_SOLICITUD_HISTO = p_id_solicitud_histo
        AND P.NUM_FICHAE = L.NUM_FICHAE
        AND P.COD_RUTPRO = G.COD_RUTPRO
        AND S.COD_EMPRESA = P.COD_EMPRESA
        AND P.IND_ESTADO = 1
    ORDER BY
        P.DATE_INICIOREGISTRO;
END //

CREATE PROCEDURE ADMIN.CONSULTA_MUESTRAS_HISTO (
    IN p_cod_empresa INT,
    IN p_id_solicitud_histo INT
)
BEGIN
    SELECT 
        M.ID_SOLICITUD_HISTO AS ID_SOLICITUD_HISTO,
        '0' AS TOTAL_MUESTRAS,
        CASE p_cod_empresa
            WHEN '100' THEN 'H.MAURICIO HEYERMANN T.ANGOL'
            WHEN '106' THEN 'SAN JOSE DE VICTORIA'
            WHEN '029' THEN 'SERVICIO DE SALUD ARAUCANIA NORTE'
            WHEN '800' THEN 'CLINICA ANATOMIA'
            WHEN '1000' THEN 'HOSPITAL MILITAR'
            ELSE 'SERVICIO DE SALUD ARAUCANIA NORTE'
        END AS TXT_HOSPITAL_ETI,
        M.IND_ESTADO_CU,
        M.ID_NUM_CARGA,
        NULL AS ID_TABLA,
        M.IND_ESTADO AS ESTADO,
        M.ID_NMUESTRA AS ID_NMUESTRA,
        M.N_MUESTRA AS N_MUESTRA,
        UPPER(M.TXT_MUESTRA) AS TXT_MUESTRA,
        UPPER(M.TXT_DESC_MICROSCOPICA) AS TXT_DESC_MICROSCOPICA,
        UPPER(M.TXT_DESC_MACROSCOPICA) AS TXT_DESC_MACROSCOPICA,
        M.IND_ESTADO_REG AS IND_ESTADO_REG,
        M.IND_TIPOMUESTRA AS IND_TIPOMUESTRA,
        CASE WHEN M.NUM_CASSETTE IS NULL THEN 0 ELSE M.NUM_CASSETTE
        END AS NUM_CASSETTE,
        M.ID_CASETE AS ID_CASETE,
        CASE WHEN M.NUM_ML IS NULL THEN 0 ELSE M.NUM_ML
        END AS NUM_ML,
        CASE M.IND_ETIQUETA
            WHEN 1 THEN 'PEQUEÑO'
            WHEN 2 THEN 'MEDIANO'
            ELSE 'NO INFORMADO'
        END AS TXT_ETIQUETA,
        CASE WHEN M.IND_ETIQUETA IS NULL THEN 2 ELSE M.IND_ETIQUETA
        END AS IND_ETIQUETA,
        IFNULL(M.TXT_DESC_MICROSCOPICA, '') AS TXT_DESC_MICROSCOPICA,
        IFNULL(M.TXT_DESC_MACROSCOPICA, '') AS TXT_DESC_MACROSCOPICA
    FROM
        ADMIN.PB_HISTO_NMUESTRAS M
    WHERE
        M.ID_SOLICITUD_HISTO = p_id_solicitud_histo
        AND M.IND_TIPOMUESTRA = 1
        AND M.IND_ESTADO = 1
    ORDER BY
        M.N_MUESTRA;
END //


CREATE PROCEDURE ADMIN.CONSULTA_MUESTRAS_CITO (
    IN p_cod_empresa INT,
    IN p_id_solicitud_histo INT
)
BEGIN
    SELECT 
        M.ID_SOLICITUD_HISTO AS ID_SOLICITUD_HISTO,
        '0' AS TOTAL_MUESTRAS,
        CASE p_cod_empresa
            WHEN '100' THEN 'H.MAURICIO HEYERMANN T.ANGOL'
            WHEN '106' THEN 'SAN JOSE DE VICTORIA'
            WHEN '029' THEN 'SERVICIO DE SALUD ARAUCANIA NORTE'
            WHEN '800' THEN 'CLINICA ANATOMIA'
            WHEN '1000' THEN 'HOSPITAL MILITAR'
            ELSE 'SERVICIO DE SALUD ARAUCANIA NORTE'
        END AS TXT_HOSPITAL_ETI,
        M.IND_ESTADO_CU,
        M.ID_NUM_CARGA,
        NULL AS ID_TABLA,
        M.IND_ESTADO AS ESTADO,
        M.ID_NMUESTRA AS ID_NMUESTRA,
        M.N_MUESTRA AS N_MUESTRA,
        UPPER(M.TXT_MUESTRA) AS TXT_MUESTRA,
        UPPER(M.TXT_DESC_MICROSCOPICA) AS TXT_DESC_MICROSCOPICA,
        UPPER(M.TXT_DESC_MACROSCOPICA) AS TXT_DESC_MACROSCOPICA,
        M.IND_ESTADO_REG AS IND_ESTADO_REG,
        M.IND_TIPOMUESTRA AS IND_TIPOMUESTRA,
        CASE
            WHEN M.NUM_CASSETTE IS NULL THEN 0 ELSE M.NUM_CASSETTE
        END AS NUM_CASSETTE,
        M.ID_CASETE AS ID_CASETE,
        CASE
            WHEN M.NUM_ML IS NULL THEN 0 ELSE M.NUM_ML
        END AS NUM_ML,
        CASE M.IND_ETIQUETA
            WHEN 1 THEN 'PEQUEÑO'
            WHEN 2 THEN 'MEDIANO'
            ELSE 'NO INFORMADO'
        END AS TXT_ETIQUETA,
        CASE
            WHEN M.IND_ETIQUETA IS NULL THEN 2 ELSE M.IND_ETIQUETA
        END AS IND_ETIQUETA,
        IFNULL(M.TXT_DESC_MICROSCOPICA, '') AS TXT_DESC_MICROSCOPICA,
        IFNULL(M.TXT_DESC_MACROSCOPICA, '') AS TXT_DESC_MACROSCOPICA
    FROM
        ADMIN.PB_HISTO_NMUESTRAS M
    WHERE
        M.ID_SOLICITUD_HISTO = p_id_solicitud_histo
        AND M.IND_TIPOMUESTRA = 2
        AND M.IND_ESTADO = 1
    ORDER BY
        M.N_MUESTRA;
END //


CREATE PROCEDURE ADMIN.GET_LISTA_ANOTOMIAPATOLOGICA(
    IN V_COD_EMPRESA VARCHAR(255),
    IN V_USR_SESSION VARCHAR(255),
    IN V_LOADXZONA INT,
    IN VAL_FECHA_INICIO VARCHAR(255),
    IN VAL_FECHA_FINAL VARCHAR(255)
)
BEGIN
    DECLARE V_FECHA_INICIO DATETIME;
    DECLARE V_FECHA_FINAL DATETIME;

    SET V_FECHA_INICIO = STR_TO_DATE(CONCAT(VAL_FECHA_INICIO, ' 00:00:00'), '%d-%m-%Y %H:%i:%s');
    SET V_FECHA_FINAL = STR_TO_DATE(CONCAT(VAL_FECHA_FINAL, ' 23:59:59'), '%d-%m-%Y %H:%i:%s');

    CREATE TEMPORARY TABLE TEMP_VAR_LISTA_TIPOZONA (TIPOZONA VARCHAR(255));

    IF V_LOADXZONA = 0 THEN
        INSERT INTO TEMP_VAR_LISTA_TIPOZONA (TIPOZONA) VALUES ('65'), ('63'), ('31');
    ELSEIF V_LOADXZONA = 1 THEN
        INSERT INTO TEMP_VAR_LISTA_TIPOZONA (TIPOZONA) VALUES ('31');
    ELSEIF V_LOADXZONA = 2 THEN
        INSERT INTO TEMP_VAR_LISTA_TIPOZONA (TIPOZONA) VALUES ('65');
    END IF;

    SELECT
        NOW() AS TIME_NOW,
        V_FECHA_INICIO AS V_FECHA_INICIO,
        V_FECHA_FINAL AS V_FECHA_FINAL,
        V_COD_EMPRESA AS V_COD_EMPRESA,
        V_LOADXZONA AS V_LOADXZONA;

    SELECT
        CASE WHEN P.COD_ESTABLREF = V_COD_EMPRESA THEN 'SI' ELSE 'NO' END AS TXT_EMPRESA_DERIVADO,
        P.COD_ESTABLREF,
        P.ID_SIC,
        P.IND_DERIVACION_IC,
        P.ID_SIC,
        CONCAT(L.COD_RUTPAC, '-', L.COD_DIGVER) AS RUTPACIENTE,
        L.IND_TISEXO,
        L.COD_RUTPAC,
        TRUNCATE(TIMESTAMPDIFF(MONTH, L.FEC_NACIMI, NOW()) / 12, 0) AS NUMEDAD,
        DATE_FORMAT(L.FEC_NACIMI, '%d-%m-%Y') AS NACIMIENTO,
        TRUNCATE(TIMESTAMPDIFF(MONTH, L.FEC_NACIMI, NOW()) / 12, 0) AS EDAD,
        CONCAT(UPPER(L.NOM_NOMBRE), ' ', UPPER(L.NOM_APEPAT), ' ', UPPER(L.NOM_APEMAT)) AS NOMBRE_COMPLETO,
        CONCAT(SUBSTRING(UPPER(L.NOM_NOMBRE), 1, 1), '.', UPPER(L.NOM_APEPAT), ' ', UPPER(L.NOM_APEMAT)) AS TXTNOMCIRUSMALL,
        CONCAT(UPPER(L.NOM_NOMBRE), ' ', UPPER(L.NOM_APEPAT), ' ', UPPER(SUBSTRING(L.NOM_APEMAT, 1, 1))) AS TXTPRIMERNOMBREAPELLIDO,
        L.NUM_FICHAE,
        CASE
            WHEN P.COD_EMPRESA = 1000 THEN
                (SELECT E.NUM_NFICHA FROM ADMIN.SO_TCPACTE E WHERE E.NUM_FICHAE = P.NUM_FICHAE AND E.COD_EMPRESA = 100)
            ELSE
                (SELECT E.NUM_NFICHA FROM ADMIN.SO_TCPACTE E WHERE E.NUM_FICHAE = P.NUM_FICHAE AND E.COD_EMPRESA = P.COD_EMPRESA)
        END AS FICHAL,
        (SELECT A.NOM_PREVIS FROM ADMIN.GG_TDATPREV A, ADMIN.SO_TTITUL B, ADMIN.GG_TGPACTE C, ADMIN.GG_TINSEMP D
         WHERE A.IND_PREVIS = B.IND_PREVIS AND B.COD_RUTTIT = C.COD_RUTTIT AND B.NUM_RUTINS = D.COD_RUTINS
         AND C.NUM_FICHAE = P.NUM_FICHAE AND A.IND_ESTADO IN ('V')) AS TXT_PREVISION,
        CONCAT(UPPER(G.NOM_NOMBRE), ' ', UPPER(G.NOM_APEPAT), ' ', UPPER(G.NOM_APEMAT)) AS PROFESIONAL,
        CONCAT(G.NOM_APEPAT, ' ', G.NOM_APEMAT, ' ', G.NOM_NOMBRE) AS PROFESIONAL_2,
        CONCAT(G.COD_RUTPRO, '-', G.COD_DIGVER) AS RUT_PROFESIOAL,
        G.COD_RUTPRO AS ID,
        G.COD_DIGVER AS DV,
        G.COD_TPROFE AS MEDI,
        P.PA_ID_PROCARCH AS PA_ID_PROCARCH,
        CASE
            WHEN P.PA_ID_PROCARCH = '31' THEN 'PABELLÓN'
            WHEN P.PA_ID_PROCARCH = '63' THEN 'RCE ESPECIALIDADES'
            WHEN P.PA_ID_PROCARCH = '65' THEN 'MODULO ANATOMIA'
            ELSE 'NO INFORMADO'
        END AS TXT_PROCEDENCIA,
        P.ID_SERDEP AS ID_SERVICIO,
        (SELECT S.NOM_SERVIC FROM ADMIN.GG_TSERVICIOXEMP T, ADMIN.GG_TSERVICIO S
         WHERE T.ID_SERDEP = P.ID_SERDEP AND T.COD_EMPRESA = P.COD_EMPRESA AND S.ID_SERDEP = T.ID_SERDEP LIMIT 1) AS NOMBRE_SERVICIO,
        P.ID_SOLICITUD_HISTO AS ID_SOLICITUD,
        UPPER(P.TXT_DIAGNOSTICO) AS TXT_DIAGNOSTICO,
        DATE_FORMAT(NOW(), '%d-%m-%Y %H:%i') AS FEC_EMISION,
        DATE_FORMAT(P.FEC_USRCREA, '%d-%m-%Y %H:%i') AS FECHA_SOLICITUD,
        DATE_FORMAT(P.DATE_INICIOREGISTRO, '%d-%m-%Y %H:%i') AS FECHA_TOMA_MUESTRA,
        CASE P.IND_TIPO_BIOPSIA
            WHEN '1' THEN 'SI'
            WHEN '2' THEN 'CONTEMPORANEA'
            WHEN '3' THEN 'DIFERIDA'
            WHEN '4' THEN 'BIOPSIA + CITOLOGÍA'
            WHEN '6' THEN 'CITOLOGÍA PAP'
            WHEN '5' THEN 'SOLO CITOLOGÍA'
            ELSE 'NO INFORMADO'
        END AS TIPO_DE_BIOPSIA,
        P.IND_TIPO_BIOPSIA,
        CASE P.IND_ESTADO
            WHEN '1' THEN 'SOLICITUD ACTIVA'
            WHEN '2' THEN 'ESTADO 1'
            WHEN '3' THEN 'ESTADO 2'
        END AS TXT_ESTADO,
        P.DES_SITIOEXT,
        P.DES_UBICACION,
        P.DES_TAMANNO,
        CASE P.ID_TIPO_LESION
            WHEN '1' THEN 'LIQUIDO'
            WHEN '2' THEN 'ORGANO'
            WHEN '3' THEN 'TEJIDO'
            ELSE 'NO INFORMADO'
        END AS TXT_TIPOSESION,
        CASE P.ID_ASPECTO
            WHEN '1' THEN 'INFLAMATORIA'
            WHEN '2' THEN 'BENIGNA'
            WHEN '3' THEN 'NEOPLASICA'
            ELSE 'NO INFORMADO'
        END AS TXT_ASPECTO,
        CASE P.ID_ANT_PREVIOS
            WHEN '1' THEN 'NO'
            WHEN '2' THEN 'BIOPSIA'
            WHEN '3' THEN 'CITOLOGIA'
            ELSE 'NO INFORMADO'
        END AS TXT_ANT_PREVIOS,
        P.ID_ANT_PREVIOS,
        P.NUM_ANTECEDENTES,
        P.DES_BIPSIA,
        P.DES_CITOLOGIA,
        P.DES_OBSERVACIONES,
        P.NUM_FICHAE,
        P.COD_USRCREA,
        P.FEC_USRCREA,
        P.COD_EMPRESA,
        P.DES_SITIOEXT,
        P.DES_UBICACION,
        P.DES_TAMANNO,
        P.ID_TIPO_LESION,
        P.ID_ASPECTO,
        P.ID_ANT_PREVIOS,
        P.NUM_ANTECEDENTES,
        P.DES_BIPSIA,
        P.DES_CITOLOGIA,
        P.DES_OBSERVACIONES,
        P.IND_ESTADO,
        P.FEC_REVISION,
        P.ID_TABLA,
        P.DES_TIPOMUESTRA,
        P.NUM_SUBNUMERACION,
        P.COD_USRCREA_TO_MUE,
        P.FEC_USRCREA_TO_MUE,
        P.COD_USRCREA_ENV,
        P.FEC_USRCREA_ENV,
        P.COD_USRCREA_RECEP,
        P.FEC_USRCREA_RECEP,
        P.COD_EMPRESA_RECEP,
        P.COD_USRCREA_INFORMADA,
        P.FEC_USRCREA_INFORMADA,
        P.COD_EMPRESA_INFORMADA,
        P.ID_ARCHIVO_SUBIDO,
        P.COD_USRCREA_RECH,
        P.FEC_USRCREA_RECH,
        P.COD_EMPRESA_RECH,
        P.TIPO_RECHAZO,
        P.OBS_RECHAZO,
        P.ID_HISTO_ESTADO,
        CASE P.ID_HISTO_ESTADO
            WHEN '1' THEN 'NUEVA SOLICITUD'
            WHEN '2' THEN 'CUSTODIA'
            WHEN '3' THEN 'TRASPORTE'
            WHEN '4' THEN 'RECEPCIONADA'
            WHEN '5' THEN 'RECHAZADA'
            ELSE 'NO INFORMADO'
        END AS TXT_HISTO_ESTADO,
        P.AD_ID_ADMISION,
        P.ID_SERDEP,
        P.IND_TIPO_BIOPSIA,
        P.IND_TEMPLATE,
        P.DATE_INICIOREGISTRO,
        P.COD_RUTPRO,
        CASE P.ID_HISTO_ESTADO
            WHEN '1' THEN 'NUEVA SOLICITUD'
            WHEN '2' THEN 'EN CUSTODIA'
            WHEN '3' THEN 'EN TRASPORTE'
            WHEN '4' THEN 'RECEPCIONADA'
            WHEN '5' THEN 'RECHAZADA'
            ELSE 'NO INFORMADO'
        END AS TXT_HISTO_ESTADO,
        P.IND_ESTADO_MUESTRAS,
        P.ID_NUM_CARGA,
        P.ID_UID,
        P.LAST_USR_AUDITA,
        DATE_FORMAT(P.LAST_DATE_AUDITA, '%d-%m-%Y %H:%i') AS LAST_DATE_AUDITA,
        P.TXT_NAMEAUDITA
    FROM
        ADMIN.GG_TGPACTE L,
        ADMIN.GG_TPROFESIONAL G,
        ADMIN.PB_SOLICITUD_HISTO P
    WHERE
        P.DATE_INICIOREGISTRO BETWEEN V_FECHA_INICIO AND V_FECHA_FINAL
        AND P.COD_EMPRESA = V_COD_EMPRESA
        AND (P.COD_RUTPRO = V_USR_SESSION OR P.COD_USRCREA = V_USR_SESSION)
        AND P.PA_ID_PROCARCH IN (SELECT TIPOZONA FROM TEMP_VAR_LISTA_TIPOZONA)
        AND P.NUM_FICHAE = L.NUM_FICHAE
        AND P.COD_RUTPRO = G.COD_RUTPRO
        AND P.IND_ESTADO = 1
    ORDER BY
        P.DATE_INICIOREGISTRO, P.FEC_USRCREA;

    DROP TEMPORARY TABLE TEMP_VAR_LISTA_TIPOZONA;

END //


CREATE PROCEDURE ADMIN.GET_INFOPRESOLICITUD(
    IN V_COD_EMPRESA VARCHAR(50),
    IN V_USR_SESSION VARCHAR(50)
)
BEGIN
    -- Query for C_ESPECIALIDADES
    SELECT
        A.COD_GRUPO AS VALUE,
        A.ID_GRUPO AS ID_VALUE,
        A.NOM_GRUPO AS OPCION
    FROM
        ADMIN.GG_TGRUESP A
    JOIN ADMIN.SO_TMOTICIQ B ON A.COD_GRUPO = B.COD_ESPEC
    WHERE    
        A.IND_ESTADO = 'V' 
        AND A.COD_GRUPO <> 'NOAP'
    GROUP BY 
        A.COD_GRUPO,
        A.ID_GRUPO,
        A.NOM_GRUPO 
    ORDER BY A.NOM_GRUPO;

    -- Query for C_LISTADOSERVICIOS
    SELECT *
        FROM (
            SELECT  
                GG_TSERVICIO.ID_SERDEP AS ID, 
                GG_TSERVICIO.NOM_SERVIC AS TXT_DES
            FROM 
                ADMIN.GG_TSERVICIO
            JOIN ADMIN.GG_TSERVICIOXEMP ON GG_TSERVICIOXEMP.ID_SERDEP = GG_TSERVICIO.ID_SERDEP 
            WHERE 
                (GG_TSERVICIOXEMP.IND_MED = '1' OR GG_TSERVICIO.ID_SERDEP IN ('268', '266'))
                AND GG_TSERVICIOXEMP.COD_EMPRESA IN (V_COD_EMPRESA)
                AND GG_TSERVICIO.IND_SERDEP = 'S'
            UNION 
            SELECT 
                A.ID_SERDEP AS ID,
                A.NOM_SERVIC AS TXT_DES 
            FROM 
                ADMIN.GG_TSERVICIO A
            JOIN ADMIN.GG_TSERVICIOXEMP B ON A.ID_SERDEP = B.ID_SERDEP
            WHERE 
                B.COD_EMPRESA IN (V_COD_EMPRESA)
                AND B.IND_MED = 1
                AND (A.IND_SERDEP = 'S' OR A.IND_SERDEP = 'D')
                AND A.ID_SERDEP NOT IN (229)
        ) AS LISTADOSERVICIOS
    ORDER BY TXT_DES;

    -- Query for C_LISTADOMEDICOS
    SELECT 
        A.COD_RUTPRO,  
        A.ID_PROFESIONAL AS ID_PRO,
        A.COD_DIGVER AS COD_DIGVER,
        CONCAT(UPPER(A.NOM_APEPAT), ' ', UPPER(A.NOM_APEMAT), ' ', UPPER(A.NOM_NOMBRE)) AS NOM_PROFE,
        C.DES_TIPOATENCION AS DES_TIPOATENCION,
        B.COD_TPROFE AS COD_TPROFE,
        B.NOM_TPROFE AS NOM_TPROFE,
        C.IND_TIPOATENCION AS IND_TIPOATENCION
    FROM 
        ADMIN.GG_TPROFESIONAL A
    JOIN ADMIN.GG_TPROFESION B ON A.COD_TPROFE = B.COD_TPROFE
    JOIN ADMIN.AP_TTIPOATENCION C ON B.IND_TIPOATENCION = C.IND_TIPOATENCION
    JOIN ADMIN.AP_TPROFXESTABL D ON A.COD_RUTPRO = D.COD_RUTPRO
    WHERE     
        A.IND_ESTADO = 'V'
        AND D.IND_ESTADO = 'V'
        AND D.COD_EMPRESA IN (V_COD_EMPRESA)
    ORDER BY 
        C.IND_TIPOATENCION, 
        A.NOM_APEPAT;
END //


CREATE PROCEDURE ADMIN.GETACTIVETECHNIQUES() BEGIN
    SELECT 
        '' AS SELECTED,
        P.ID_TECNICA_AP AS ID_TECNICA_AP, 
        P.TXT_TECNICA_AP AS TXT_TECNICA_AP, 
        P.IND_ESTADO
    FROM ADMIN.PB_TECNICASXMUESTRAS P
    WHERE P.IND_ESTADO = 1;
END //

CREATE PROCEDURE ADMIN.GETTECHNIQUESBYREQUEST(IN V_ID_ANATOMIA INT)
BEGIN
    SELECT 
        P.ID_TECNICAXMUES, 
        P.ID_TECNICA_AP, 
        P.ID_NMUESTRA, 
        P.DATE_CREA, 
        P.USR_CREA, 
        P.IND_ESTADO, 
        P.ID_SOLICITUD_HISTO, 
        P.DATE_AUDITA, 
        P.USR_AUDITA
    FROM 
        ADMIN.PB_MUESTRAXTECNICA P
    WHERE
        P.ID_SOLICITUD_HISTO = V_ID_ANATOMIA AND P.IND_ESTADO = 1;
END //

DELIMITER ;

/*
 PROCEDURE   LOAD_ANALITICA_PAGINADO (
    V_COD_EMPRESA                              IN VARCHAR2,
    V_USR_SESSION                               IN VARCHAR2,
    V_OPCION                                        IN VARCHAR2,
    V_IND_FIRST                                   IN VARCHAR2,
    VAL_FECHA_INICIO                           IN VARCHAR2,
    VAL_FECHA_FINAL                            IN VARCHAR2,
    V_ARR_DATA                                    IN VARCHAR2,
    V_PAGE_NUMBER                              IN NUMBER,
    V_PAGE_SIZE                                   IN NUMBER,
    C_LISTA_ANATOMIA                         OUT SYS_REFCURSOR,
    C_NUM_RESULTADOS                        OUT SYS_REFCURSOR,
    C_STATUS                                       OUT SYS_REFCURSOR
) IS
    V_AUX NUMBER :=  1;
    V_FECHA_INICIO DATE :=  TO_DATE(VAL_FECHA_INICIO||' 00:00:00','DD-MM-YYYY hh24:mi:ss');
    V_FECHA_FINAL DATE :=  TO_DATE(VAL_FECHA_FINAL||' 23:59:59','DD-MM-YYYY hh24:mi:ss');
    VAR_LISTA_ID_ANATOMIA LIST_OF_NAMES_T := LIST_OF_NAMES_T(); 
    VAR_LISTA_FILTRO_ESTADOS LIST_OF_NAMES_T       :=   LIST_OF_NAMES_T(); 
    RETURN_LIST COL_LIS_ANATOMIAP    :=   COL_LIS_ANATOMIAP();
    V_START_ROW NUMBER;
    V_END_ROW NUMBER;
    V_TOTAL_COUNT NUMBER;
    V_NUM_PAGINAS NUMBER;
    
BEGIN
    -- filtos segun estado 
   IF V_ARR_DATA = '0' THEN
        FOR V_ROW IN 0..8 LOOP
            VAR_LISTA_FILTRO_ESTADOS.EXTEND();
            VAR_LISTA_FILTRO_ESTADOS(V_ROW + 1) := V_ROW;
        END LOOP;
    ELSE
        FOR FOO IN (SELECT REGEXP_SUBSTR(V_ARR_DATA, '[^,]+', 1, LEVEL) TXT
                    FROM DUAL
                    CONNECT BY REGEXP_SUBSTR(V_ARR_DATA, '[^,]+', 1, LEVEL) IS NOT NULL) LOOP
            VAR_LISTA_FILTRO_ESTADOS.EXTEND();
            IF FOO.TXT = '9' THEN
                VAR_LISTA_FILTRO_ESTADOS(V_AUX) := '0';
            ELSE
                VAR_LISTA_FILTRO_ESTADOS(V_AUX) := FOO.TXT;
            END IF;
            V_AUX := V_AUX + 1;
        END LOOP;
    END IF;
    
    V_START_ROW := (V_PAGE_NUMBER - 1) * V_PAGE_SIZE + 1;
    V_END_ROW := V_PAGE_NUMBER * V_PAGE_SIZE;

    OPEN C_LISTA_ANATOMIA FOR
        SELECT SOL_ANATOMIA.*, TOTAL_COUNT
        FROM (
            SELECT 
               ROW_NUMBER() OVER (ORDER BY ID_SOLICITUD_HISTO) AS RNUM,
               COUNT(*) OVER () AS TOTAL_COUNT,
               P.*  
            FROM 
                PABELLON.PB_SOLICITUD_HISTO P,
                ADMIN.GG_TPROFESIONAL A,
                ADMIN.GG_TGPACTE L,
                ADMIN.GG_TPROFESIONAL G
            WHERE
                P.DATE_INICIOREGISTRO BETWEEN V_FECHA_INICIO AND V_FECHA_FINAL AND
                A.COD_RUTPRO = P.COD_RUTPRO AND
                P.NUM_FICHAE =  L.NUM_FICHAE AND
                P.COD_RUTPRO =  G.COD_RUTPRO AND
                P.ID_HISTO_ZONA IN  (SELECT * FROM TABLE(VAR_LISTA_FILTRO_ESTADOS)) AND 
                P.ID_HISTO_ESTADO IN  (4) AND 
                P.IND_ESTADO IN  (1) AND
                (P.COD_EMPRESA IN (V_COD_EMPRESA) OR P.COD_ESTABLREF IN (V_COD_EMPRESA) )
            ORDER BY  
                CASE
                    WHEN V_OPCION = '0' THEN P.NUM_INTERNO_AP 
                    WHEN V_OPCION = '1' THEN P.NUM_CO_CITOLOGIA
                    WHEN V_OPCION = '2' THEN P.NUM_CO_PAP
                    ELSE P.NUM_INTERNO_AP
                END ASC
                       
    ) SOL_ANATOMIA WHERE RNUM BETWEEN V_START_ROW AND V_END_ROW;

        
        SELECT  
            COUNT(*) INTO V_TOTAL_COUNT
        FROM 
            PABELLON.PB_SOLICITUD_HISTO P,
            ADMIN.GG_TPROFESIONAL A,
            ADMIN.GG_TGPACTE L,
            ADMIN.GG_TPROFESIONAL G
        WHERE
            P.DATE_INICIOREGISTRO BETWEEN V_FECHA_INICIO AND V_FECHA_FINAL AND
            A.COD_RUTPRO = P.COD_RUTPRO AND
            P.NUM_FICHAE =  L.NUM_FICHAE AND
            P.COD_RUTPRO =  G.COD_RUTPRO AND
            P.ID_HISTO_ZONA IN  (SELECT * FROM TABLE(VAR_LISTA_FILTRO_ESTADOS)) AND 
            P.ID_HISTO_ESTADO IN  (4) AND 
            P.IND_ESTADO IN  (1) AND
            (P.COD_EMPRESA IN (V_COD_EMPRESA) OR P.COD_ESTABLREF IN (V_COD_EMPRESA) )
        ORDER BY  
            P.DATE_INICIOREGISTRO ASC,
            CASE
            WHEN V_OPCION = '0' THEN P.NUM_INTERNO_AP 
            WHEN V_OPCION = '1' THEN P.NUM_CO_CITOLOGIA
            WHEN V_OPCION = '2' THEN P.NUM_CO_PAP
           ELSE P.NUM_INTERNO_AP
        END ASC;

    V_NUM_PAGINAS := CEIL(V_TOTAL_COUNT / V_PAGE_SIZE);
    OPEN C_NUM_RESULTADOS FOR  SELECT V_TOTAL_COUNT AS V_TOTAL_COUNT, V_NUM_PAGINAS AS V_NUM_PAGINAS FROM DUAL;
    OPEN C_STATUS FOR  SELECT 
        V_PAGE_NUMBER AS V_PAGE_NUMBER,
        V_PAGE_SIZE AS V_PAGE_SIZE,
        V_START_ROW AS V_START_ROW,
        V_END_ROW AS V_END_ROW,
        VAL_FECHA_INICIO AS VAL_FECHA_INICIO,
        VAL_FECHA_FINAL AS VAL_FECHA_FINAL
    FROM DUAL;

END;
*/





