CREATE TABLE ADMIN.PB_SOLICITUD_HISTO (
  `ID_SOLICITUD_HISTO` INT,
  `NUM_FICHAE` INT,
  `COD_USRCREA` INT,
  `FEC_USRCREA` DATETIME,
  `COD_EMPRESA` VARCHAR(25),
  `DES_SITIOEXT` VARCHAR(255),
  `DES_UBICACION` VARCHAR(255),
  `DES_TAMANNO` VARCHAR(255),
  `ID_TIPO_LESION` INT,
  `ID_ASPECTO` INT,
  `ID_ANT_PREVIOS` INT,
  `NUM_ANTECEDENTES` VARCHAR(10),
  `DES_BIPSIA` TEXT,
  `DES_CITOLOGIA` TEXT,
  `DES_OBSERVACIONES` TEXT,
  `IND_ESTADO` INT,
  `FEC_REVISION` DATETIME,
  `ID_TABLA` INT,
  `DES_TIPOMUESTRA` VARCHAR(255),
  `NUM_SUBNUMERACION` INT,
  `COD_USRCREA_TO_MUE` INT,
  `FEC_USRCREA_TO_MUE` DATETIME,
  `COD_USRCREA_ENV` INT,
  `FEC_USRCREA_ENV` DATETIME,
  `COD_USRCREA_RECEP` INT,
  `FEC_USRCREA_RECEP` DATETIME,
  `COD_EMPRESA_RECEP` VARCHAR(5),
  `COD_USRCREA_INFORMADA` INT,
  `FEC_USRCREA_INFORMADA` DATETIME,
  `COD_EMPRESA_INFORMADA` VARCHAR(5),
  `ID_ARCHIVO_SUBIDO` INT,
  `COD_USRCREA_RECH` INT,
  `FEC_USRCREA_RECH` DATETIME,
  `COD_EMPRESA_RECH` VARCHAR(5),
  `TIPO_RECHAZO` INT,
  `OBS_RECHAZO` TEXT,
  `ID_HISTO_ESTADO` INT DEFAULT 1,
  `AD_ID_ADMISION` INT,
  `ID_SERDEP` INT,
  `PA_ID_PROCARCH` INT,
  `IND_TIPO_BIOPSIA` INT,
  `IND_TEMPLATE` INT,
  `DATE_INICIOREGISTRO` DATETIME,
  `COD_RUTPRO` INT,
  `TXT_DIAGNOSTICO` VARCHAR(500),
  `NUM_PLANTILLA` INT,
  `IND_USOCASSETTE` INT,
  `IND_INFOPOST` INT,
  `IND_ESTADO_MUESTRAS` INT,
  `LAST_USR_AUDITA` VARCHAR(50),
  `LAST_DATE_AUDITA` DATETIME,
  `ID_NUM_CARGA` INT,
  `ID_UID` INT,
  `TXT_NAMEAUDITA` VARCHAR(255),
  `ID_ROTULADO` INT,
  `IND_NOTIF_CANCER` INT,
  `FEC_AUDITA` DATETIME,
  `USR_AUDITA` VARCHAR(50),
  `NUM_NOTIFICACION` INT,
  `ID_PROFESIONAL` INT,
  `DATE_CHEQUEO_SOME` DATETIME,
  `DATE_REVISION_BD` DATETIME,
  `DATE_REVISION_INFORME` DATETIME,
  `DATE_ARCHIVADA_EN_FICHA` DATETIME,
  `NUM_BENEFICIARIOS` INT,
  `IND_MES_CRITICO` INT,
  `DATE_IMPRESION_INFORME` DATETIME,
  `DATE_ENTREGA_INFORME` DATETIME,
  `ID_PROFESIONAL_RECIBE_INFO` INT,
  `ID_PROFESIONAL_ENTREGA_INFO` INT,
  `NUM_PLAZO_BIOPSIA` INT,
  `NUM_DIAS_ENTCANCER` INT,
  `NUM_ASIGNACION96HRS` INT,
  `DATE_INICIO_CANCER` DATETIME,
  `DATE_FINAL_CANCER` DATETIME,
  `IND_ESTADIO_OLGA` INT,
  `TXT_DIADNOSTICO_AP` TEXT,
  `DATE_FECHA_MACRO` DATETIME,
  `DATE_FECHA_CORTE` DATETIME,
  `IND_COLOR_TACO` INT,
  `IND_ESTADO_OLGA` INT,
  `DATE_INTERCONSULTA` DATETIME,
  `NUM_CP_INTERCONSULTA` INT,
  `NUM_FRAGMENTOS` INT,
  `NUM_AZUK_ALCIAN_S` INT,
  `NUM_PAS_SERIADA` INT,
  `NUM_DIFF_SERIADA` INT,
  `NUM_HE_SERIADA` INT,
  `NUM_LAMINAS_SERIADAS` INT,
  `NUM_HE_RAPIDA` INT,
  `NUM_TACOS_CORTADOS` INT,
  `NUM_EXTENDIDOS` INT,
  `DATE_TRASLADO` DATETIME,
  `ID_UID_TRASLADO` INT,
  `ID_USER_TRASLADO` VARCHAR(50),
  `ID_UID_TRASPORTE_OK` INT,
  `ID_UID_RECEPCIONA_OK` INT,
  `COD_SESSION_RECEPCIONA` VARCHAR(50),
  `ID_HISTO_ZONA` INT DEFAULT 0,
  `TXT_DESC_MACROSCOPICA` TEXT,
  `DATE_STAR_SALA_PROCESO` DATETIME,
  `DATE_END_SALA_PROCESO` DATETIME,
  `ID_UID_INICIO_SPROCESO` INT,
  `IND_SALA_PROCESO` INT,
  `ID_UID_FINAL_SPROCESO` INT,
  `IND_TEC_INCLUCION` INT,
  `IND_TEC_CORTE` INT,
  `IND_TEC_TINCION` INT,
  `IND_ALL_TECNICAS` INT,
  `ID_UID_RECHAZA` INT,
  `TXT_OBS_RECHAZA` VARCHAR(256),
  `ID_UID_CANCELA` INT,
  `FEC_CANCELA` DATETIME,
  `NUM_INTERNO_AP` INT,
  `DATE_AUDITA_ADMINISTRATIVO` DATETIME,
  `IND_GEST_ADMINISTRATIVO` INT,
  `ID_UID_ADMINISTRATIVO` INT,
  `DATE_FECHA_DIAGNOSTICO` DATETIME,
  `IND_CONF_CANCER` INT,
  `CI_ID_CITACION` INT,
  `IND_TIPOSECUENCIA` INT,
  `TXT_CITOLOGICO` TEXT,
  `NUM_CO_CITOLOGIA` INT,
  `NUM_CO_PAP` INT,
  `TXT_DIAG_CITOLOGIA` TEXT,
  `ID_PROFESIONAL_CITOLOGICO` INT,
  `IND_TIPO_INFORME` INT DEFAULT 0,
  `NUM_NOF_CANCER` INT,
  `IND_CONF_PAG` INT DEFAULT 0,
  `IND_DERIVACION_IC` INT DEFAULT 0,
  `ID_SIC` INT,
  `COD_ESTABLREF` VARCHAR(50),
  `IND_TIPO_PROCESO` INT DEFAULT 0,
  `IND_NOTIFICACANCER` TINYINT DEFAULT 0,
  `DATE_NOTIFICACANCER` DATETIME,
  `IND_TIPO_NOTIFICACION` INT,
  `ID_UID_NOTIFICA_CANCER` INT,
  `ID_UID_RC_NOTIFICA_CANCER` INT,
  `IND_SOLICITUD_EDITADA` INT,
  `IND_PROBLEMA_SOL` INT,
  `ID_UID_CUSTODIA` INT,
  `DATE_LAST_CUSTODIA` DATETIME,
  `ID_UID_TECNICAS` INT,
  `USR_TECNICAS` INT,
  `DATE_TECNICAS` DATETIME,
  `ID_ROTULADO_SUB` INT,
  `DATE_MACROSCOPIA` DATETIME,
  `USER_MACROSCOPICA` VARCHAR(50)
);

DELIMITER //

CREATE PROCEDURE GET_LISTA_ANOTOMIAPATOLOGICA(
    IN V_COD_EMPRESA VARCHAR(255),
    IN V_USR_SESSION VARCHAR(255),
    IN V_LOADXZONA INT,
    IN VAL_FECHA_INICIO VARCHAR(255),
    IN VAL_FECHA_FINAL VARCHAR(255)
)
BEGIN
    -- Declaración de variables
    DECLARE V_FECHA_INICIO DATE;
    DECLARE V_FECHA_FINAL DATE;

    SET V_FECHA_INICIO = STR_TO_DATE(CONCAT(VAL_FECHA_INICIO, ' 00:00:00'), '%d-%m-%Y %H:%i:%s');
    SET V_FECHA_FINAL = STR_TO_DATE(CONCAT(VAL_FECHA_FINAL, ' 23:59:59'), '%d-%m-%Y %H:%i:%s');

    -- Crear una tabla temporal para almacenar los valores de VAR_LISTA_TIPOZONA
    CREATE TEMPORARY TABLE TEMP_VAR_LISTA_TIPOZONA (TIPOZONA VARCHAR(255));

    -- Población de la tabla temporal según el valor de V_LOADXZONA
    IF V_LOADXZONA = 0 THEN
        INSERT INTO TEMP_VAR_LISTA_TIPOZONA (TIPOZONA) VALUES ('65'), ('63'), ('31');
    ELSEIF V_LOADXZONA = 1 THEN
        INSERT INTO TEMP_VAR_LISTA_TIPOZONA (TIPOZONA) VALUES ('31');
    ELSEIF V_LOADXZONA = 2 THEN
        INSERT INTO TEMP_VAR_LISTA_TIPOZONA (TIPOZONA) VALUES ('65');
    END IF;

    -- Resultados temporales para los cursores
    SELECT
        NOW() AS TIME_NOW,
        V_FECHA_INICIO AS V_FECHA_INICIO,
        V_FECHA_FINAL AS V_FECHA_FINAL,
        V_COD_EMPRESA AS V_COD_EMPRESA,
        V_LOADXZONA AS V_LOADXZONA;

    -- Resultado principal de la consulta
    SELECT
        CASE WHEN P.COD_ESTABLREF = V_COD_EMPRESA THEN 'SI' ELSE 'NO' END AS TXT_EMPRESA_DERIVADO,
        P.COD_ESTABLREF,
        P.ID_SIC,
        P.IND_DERIVACION_IC,
        P.ID_SIC,
        CONCAT(L.COD_RUTPAC, '-', L.COD_DIGVER) AS RUTPACIENTE,
        L.IND_TISEXO,
        L.COD_RUTPAC,
        TRUNCATE(TIMESTAMPDIFF(MONTH, L.FEC_NACIMI, NOW()) / 12, 0) AS NUMEDAD,
        DATE_FORMAT(L.FEC_NACIMI, '%d-%m-%Y') AS NACIMIENTO,
        TRUNCATE(TIMESTAMPDIFF(MONTH, L.FEC_NACIMI, NOW()) / 12, 0) AS EDAD,
        CONCAT(UPPER(L.NOM_NOMBRE), ' ', UPPER(L.NOM_APEPAT), ' ', UPPER(L.NOM_APEMAT)) AS NOMBRE_COMPLETO,
        CONCAT(SUBSTRING(UPPER(L.NOM_NOMBRE), 1, 1), '.', UPPER(L.NOM_APEPAT), ' ', UPPER(L.NOM_APEMAT)) AS TXTNOMCIRUSMALL,
        CONCAT(UPPER(L.NOM_NOMBRE), ' ', UPPER(L.NOM_APEPAT), ' ', UPPER(SUBSTRING(L.NOM_APEMAT, 1, 1))) AS TXTPRIMERNOMBREAPELLIDO,
        L.NUM_FICHAE,
        CASE
            WHEN P.COD_EMPRESA = 1000 THEN
                (SELECT E.NUM_NFICHA FROM ADMIN.SO_TCPACTE E WHERE E.NUM_FICHAE = P.NUM_FICHAE AND E.COD_EMPRESA = 100)
            ELSE
                (SELECT E.NUM_NFICHA FROM ADMIN.SO_TCPACTE E WHERE E.NUM_FICHAE = P.NUM_FICHAE AND E.COD_EMPRESA = P.COD_EMPRESA)
        END AS FICHAL,
        (SELECT A.NOM_PREVIS FROM ADMIN.GG_TDATPREV A, ADMIN.SO_TTITUL B, ADMIN.GG_TGPACTE C, ADMIN.GG_TINSEMP D
         WHERE A.IND_PREVIS = B.IND_PREVIS AND B.COD_RUTTIT = C.COD_RUTTIT AND B.NUM_RUTINS = D.COD_RUTINS
         AND C.NUM_FICHAE = P.NUM_FICHAE AND A.IND_ESTADO IN ('V')) AS TXT_PREVISION,
        CONCAT(UPPER(G.NOM_NOMBRE), ' ', UPPER(G.NOM_APEPAT), ' ', UPPER(G.NOM_APEMAT)) AS PROFESIONAL,
        CONCAT(G.NOM_APEPAT, ' ', G.NOM_APEMAT, ' ', G.NOM_NOMBRE) AS PROFESIONAL_2,
        CONCAT(G.COD_RUTPRO, '-', G.COD_DIGVER) AS RUT_PROFESIOAL,
        G.COD_RUTPRO AS ID,
        G.COD_DIGVER AS DV,
        G.COD_TPROFE AS MEDI,
        P.PA_ID_PROCARCH AS PA_ID_PROCARCH,
        CASE
            WHEN P.PA_ID_PROCARCH = '31' THEN 'PABELLÓN'
            WHEN P.PA_ID_PROCARCH = '63' THEN 'RCE ESPECIALIDADES'
            WHEN P.PA_ID_PROCARCH = '65' THEN 'MODULO ANATOMIA'
            ELSE 'NO INFORMADO'
        END AS TXT_PROCEDENCIA,
        P.ID_SERDEP AS ID_SERVICIO,
        (SELECT S.NOM_SERVIC FROM ADMIN.GG_TSERVICIOXEMP T, ADMIN.GG_TSERVICIO S
         WHERE T.ID_SERDEP = P.ID_SERDEP AND T.COD_EMPRESA = P.COD_EMPRESA AND S.ID_SERDEP = T.ID_SERDEP LIMIT 1) AS NOMBRE_SERVICIO,
        P.ID_SOLICITUD_HISTO AS ID_SOLICITUD,
        UPPER(P.TXT_DIAGNOSTICO) AS TXT_DIAGNOSTICO,
        DATE_FORMAT(NOW(), '%d-%m-%Y %H:%i') AS FEC_EMISION,
        DATE_FORMAT(P.FEC_USRCREA, '%d-%m-%Y %H:%i') AS FECHA_SOLICITUD,
        DATE_FORMAT(P.DATE_INICIOREGISTRO, '%d-%m-%Y %H:%i') AS FECHA_TOMA_MUESTRA,
        CASE P.IND_TIPO_BIOPSIA
            WHEN '1' THEN 'SI'
            WHEN '2' THEN 'CONTEMPORANEA'
            WHEN '3' THEN 'DIFERIDA'
            WHEN '4' THEN 'BIOPSIA + CITOLOGÍA'
            WHEN '6' THEN 'CITOLOGÍA PAP'
            WHEN '5' THEN 'SOLO CITOLOGÍA'
            ELSE 'NO INFORMADO'
        END AS TIPO_DE_BIOPSIA,
        P.IND_TIPO_BIOPSIA,
        CASE P.IND_ESTADO
            WHEN '1' THEN 'SOLICITUD ACTIVA'
            WHEN '2' THEN 'ESTADO 1'
            WHEN '3' THEN 'ESTADO 2'
        END AS TXT_ESTADO,
        P.DES_SITIOEXT,
        P.DES_UBICACION,
        P.DES_TAMANNO,
        CASE P.ID_TIPO_LESION
            WHEN '1' THEN 'LIQUIDO'
            WHEN '2' THEN 'ORGANO'
            WHEN '3' THEN 'TEJIDO'
            ELSE 'NO INFORMADO'
        END AS TXT_TIPOSESION,
        CASE P.ID_ASPECTO
            WHEN '1' THEN 'INFLAMATORIA'
            WHEN '2' THEN 'BENIGNA'
            WHEN '3' THEN 'NEOPLASICA'
            ELSE 'NO INFORMADO'
        END AS TXT_ASPECTO,
        CASE P.ID_ANT_PREVIOS
            WHEN '1' THEN 'NO'
            WHEN '2' THEN 'BIOPSIA'
            WHEN '3' THEN 'CITOLOGIA'
            ELSE 'NO INFORMADO'
        END AS TXT_ANT_PREVIOS,
        P.ID_ANT_PREVIOS,
        P.NUM_ANTECEDENTES,
        P.DES_BIPSIA,
        P.DES_CITOLOGIA,
        P.DES_OBSERVACIONES,
        P.NUM_FICHAE,
        P.COD_USRCREA,
        P.FEC_USRCREA,
        P.COD_EMPRESA,
        P.DES_SITIOEXT,
        P.DES_UBICACION,
        P.DES_TAMANNO,
        P.ID_TIPO_LESION,
        P.ID_ASPECTO,
        P.ID_ANT_PREVIOS,
        P.NUM_ANTECEDENTES,
        P.DES_BIPSIA,
        P.DES_CITOLOGIA,
        P.DES_OBSERVACIONES,
        P.IND_ESTADO,
        P.FEC_REVISION,
        P.ID_TABLA,
        P.DES_TIPOMUESTRA,
        P.NUM_SUBNUMERACION,
        P.COD_USRCREA_TO_MUE,
        P.FEC_USRCREA_TO_MUE,
        P.COD_USRCREA_ENV,
        P.FEC_USRCREA_ENV,
        P.COD_USRCREA_RECEP,
        P.FEC_USRCREA_RECEP,
        P.COD_EMPRESA_RECEP,
        P.COD_USRCREA_INFORMADA,
        P.FEC_USRCREA_INFORMADA,
        P.COD_EMPRESA_INFORMADA,
        P.ID_ARCHIVO_SUBIDO,
        P.COD_USRCREA_RECH,
        P.FEC_USRCREA_RECH,
        P.COD_EMPRESA_RECH,
        P.TIPO_RECHAZO,
        P.OBS_RECHAZO,
        P.ID_HISTO_ESTADO,
        CASE P.ID_HISTO_ESTADO
            WHEN '1' THEN 'NUEVA SOLICITUD'
            WHEN '2' THEN 'CUSTODIA'
            WHEN '3' THEN 'TRASPORTE'
            WHEN '4' THEN 'RECEPCIONADA'
            WHEN '5' THEN 'RECHAZADA'
            ELSE 'NO INFORMADA'
        END AS TXT_HISTO_ESTADO,
        P.AD_ID_ADMISION,
        P.ID_SERDEP,
        P.IND_TIPO_BIOPSIA,
        P.IND_TEMPLATE,
        P.DATE_INICIOREGISTRO,
        P.COD_RUTPRO,
        CASE P.ID_HISTO_ESTADO
            WHEN '1' THEN 'NUEVA SOLICITUD'
            WHEN '2' THEN 'EN CUSTODIA'
            WHEN '3' THEN 'EN TRASPORTE'
            WHEN '4' THEN 'RECEPCIONADA'
            WHEN '5' THEN 'RECHAZADA'
            ELSE 'NO INFORMADO'
        END AS TXT_HISTO_ESTADO,
        P.IND_ESTADO_MUESTRAS,
        P.ID_NUM_CARGA,
        P.ID_UID,
        P.LAST_USR_AUDITA,
        DATE_FORMAT(P.LAST_DATE_AUDITA, '%d-%m-%Y %H:%i') AS LAST_DATE_AUDITA,
        P.TXT_NAMEAUDITA
    FROM
        ADMIN.GG_TGPACTE L,
        ADMIN.GG_TPROFESIONAL G,
        ADMIN.PB_SOLICITUD_HISTO P
    WHERE
        P.DATE_INICIOREGISTRO BETWEEN V_FECHA_INICIO AND V_FECHA_FINAL
        AND P.COD_EMPRESA = V_COD_EMPRESA
        AND (P.COD_RUTPRO = V_USR_SESSION OR P.COD_USRCREA = V_USR_SESSION)
        AND P.PA_ID_PROCARCH IN (SELECT TIPOZONA FROM TEMP_VAR_LISTA_TIPOZONA)
        AND P.NUM_FICHAE = L.NUM_FICHAE
        AND P.COD_RUTPRO = G.COD_RUTPRO
        AND P.IND_ESTADO = 1
    ORDER BY
        P.DATE_INICIOREGISTRO, P.FEC_USRCREA;

    -- Eliminar la tabla temporal
    DROP TEMPORARY TABLE TEMP_VAR_LISTA_TIPOZONA;

END //

DELIMITER ;
