ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = ADMIN;
/
CREATE TABLE ADMIN.GG_TGPACTE(
  NUM_FICHAE              NUMBER NOT NULL,
  COD_RUTPAC              NUMBER,
  COD_DIGVER              VARCHAR2(25 BYTE),
  NOM_NOMBRE              VARCHAR2(25 BYTE),
  NOM_APEPAT              VARCHAR2(20 BYTE),
  NOM_APEMAT              VARCHAR2(20 BYTE),
  FEC_NACIMI              DATE,
  IND_TISEXO              CHAR,
  IND_ESTCIV              CHAR,
  NOM_NPADRE              VARCHAR2(31 BYTE),
  NOM_NMADRE              VARCHAR2(31 BYTE),
  NOM_PAREJA              VARCHAR2(35 BYTE),
  IND_GRUCRO              CHAR,
  IND_TIPPAC              CHAR,
  COD_GRUSAN              VARCHAR2(10 BYTE),
  IND_ETN                 VARCHAR2(2 BYTE),
  OCUPACION               VARCHAR2(30 BYTE),
  LUGAR_TRAB              VARCHAR2(30 BYTE),
  NOM_DIRECC              VARCHAR2(100 BYTE),
  COD_COMUNA              VARCHAR2(15 BYTE),
  IND_URBRUR              VARCHAR2(1 BYTE),
  COD_PAIS                VARCHAR2(3 BYTE),
  COD_RUTTIT              NUMBER,
  COD_USRCREA             VARCHAR2(60 BYTE),
  FEC_USRCREA             DATE,
  COD_USUARI              VARCHAR2(60 BYTE),
  FEC_AUDITA              DATE,
  IND_ESTADO              CHAR,
  EMAIL                   VARCHAR2(65 BYTE),
  IND_FAX                 VARCHAR2(10 BYTE),
  IND_PERCETN             VARCHAR2(2 BYTE),
  COD_FACSAN              VARCHAR2(2 BYTE),
  IND_RECNAC              VARCHAR2(1 BYTE),
  COD_RUTREF              NUMBER,
  COD_DIGREF              VARCHAR2(1 BYTE),
  IND_REFER               VARCHAR2(1 BYTE),
  IND_RUT                 VARCHAR2(10 BYTE),
  IND_PERCAPITA           VARCHAR2(1 BYTE),
  EMP_PERCAPITA           VARCHAR2(3 BYTE),
  ALERGIAS                VARCHAR2(30 BYTE),
  CREDENCIAL              VARCHAR2(10 BYTE),
  INTG_PART_MULT          VARCHAR2(1 BYTE),
  NUM_TELEFO1_2           VARCHAR2(12 BYTE),
  NUM_TELEFO2_2           VARCHAR2(12 BYTE),
  NUM_CELULAR_2           VARCHAR2(12 BYTE),
  NUM_TELEFO1             VARCHAR2(12 BYTE),
  NUM_TELEFO2             VARCHAR2(12 BYTE),
  NUM_CELULAR             VARCHAR2(12 BYTE),
  COD_SISTEMA             VARCHAR2(10 BYTE),
  COD_SISTEMAUDITA        VARCHAR2(10 BYTE),
  COD_REGION              VARCHAR2(2 BYTE),
  COD_CIUDAD              VARCHAR2(15 BYTE),
  NUM_CASA                VARCHAR2(15 BYTE),
  COD_VIADIRECCION        VARCHAR2(2 BYTE),
  IND_CONDPRAIS           VARCHAR2(1 BYTE),
  NOM_RESTODIRECC         VARCHAR2(300 BYTE),
  CP_ID_CATOCUPAPAC       NUMBER             DEFAULT 0,
  IND_NIVELINSTRUC        NUMBER             DEFAULT 0,
  REP_LEGAL               VARCHAR2(300 BYTE),
  ID_EXTRANJERO           VARCHAR2(15 BYTE),
  IND_TIPOIDENTIFICA      NUMBER             DEFAULT 0,
  IND_EXTRANJERO          NUMBER             DEFAULT 0,
  NUM_IDENTIFICACION      VARCHAR2(30 BYTE),
  TIP_IDENTIFICACION      NUMBER,
  FEC_VENCEPASPORT        DATE,
  IND_CORTEINTERA         NUMBER             DEFAULT 0,
  COD_OCUPACION           VARCHAR2(5 BYTE),
  ID_FONASA               VARCHAR2(30 BYTE),
  FEC_IDFONASA            DATE,
  NOM_SOCIAL              VARCHAR2(50 BYTE),
  IND_TRANS               NUMBER,
  IND_SENAME              NUMBER             DEFAULT '0',
  COD_NACIONALIDAD        VARCHAR2(3 BYTE),
  EDAD_GESTA_SEMANA       NUMBER,
  EDAD_GESTA_DIAS         NUMBER,
  EDAD_CORREGIDA_SEMANA   NUMBER,
  EDAD_CORREGIDA_DIAS     NUMBER,
  IND_PREMATURO           NUMBER,
  ID_OCUPACION            NUMBER,
  IND_CATOCUPANEW         NUMBER,
  IND_NIVEL_EDUCACIONAL   NUMBER,
  IND_POBLACION_MIGRANTE  NUMBER,
  PESO                    NUMBER,
  TALLA                   NUMBER,
  IMC                     NUMBER,
  EDADGESTACIONAL         NUMBER,
  PRIMARY KEY (NUM_FICHAE)
);
COMMIT;
/

CREATE TABLE ADMIN.SO_TCPACTE (
  COD_RUTPAC              NUMBER,
  NUM_CORPAC              NUMBER,
  NUM_NFICHA              NUMBER,
  NUM_AFICHA              NUMBER,
  IND_ESTPAC              CHAR,
  COD_SERULA              VARCHAR2(7 BYTE),
  FEC_ULTASI              DATE,
  NUM_CORHOS              NUMBER,
  FEC_ULTSER              DATE,
  COD_ULTSER              VARCHAR2(3 BYTE),
  IND_ARCHIVO             VARCHAR2(1 BYTE),
  FEC_IMPRES              DATE,
  COD_USRCREA             VARCHAR2(60 BYTE),
  FEC_USRCREA             DATE,
  COD_USUARI              VARCHAR2(60 BYTE),
  FEC_AUDITA              DATE,
  IND_ESTADO              CHAR,
  COD_EMPRESA             VARCHAR2(5 BYTE),
  NOM_DIRECC              VARCHAR2(100 BYTE),
  NOM_CONTACTO            VARCHAR2(50 BYTE),
  DIRECC_CONTACTO         VARCHAR2(100 BYTE),
  NUM_FICHAE              NUMBER,
  IND_IMPRES              CHAR,
  NUM_TELEFO1_2           VARCHAR2(12 BYTE),
  TELEFO_CONTACTO_2       VARCHAR2(12 BYTE),
  NUM_TELEFO1             VARCHAR2(12 BYTE),
  TELEFO_CONTACTO         VARCHAR2(12 BYTE),
  COD_SISTEMA             VARCHAR2(10 BYTE),
  COD_SISTEMAUDITA        VARCHAR2(10 BYTE),
  COD_SECTOR              VARCHAR2(5 BYTE),
  COD_FAMILIA             VARCHAR2(15 BYTE),
  NUM_CASA                VARCHAR2(6 BYTE),
  COD_VIADIRECCION        VARCHAR2(2 BYTE),
  COD_COMUNAL             VARCHAR2(15 BYTE),
  COD_CIUDADL             VARCHAR2(15 BYTE),
  COD_REGIONL             VARCHAR2(2 BYTE)
);
COMMIT;
/

CREATE TABLE ADMIN.GG_TPACFALLECIDO (
  NUM_FICHAE              NUMBER NOT NULL,
  COD_RUTPAC              NUMBER,
  FEC_FALLECE             DATE,
  COD_USUARIINF           VARCHAR2(60 BYTE),
  FEC_INFORMA             DATE,
  COD_SISINFORMA          VARCHAR2(30 BYTE),
  COD_USRCREA             VARCHAR2(60 BYTE),
  FEC_USRCREA             DATE,
  COD_USUARI              VARCHAR2(60 BYTE),
  FEC_AUDITA              DATE,
  IND_ESTADO              VARCHAR2(1 BYTE)
);

CREATE TABLE ADMIN.GG_TSEXO (
  IND_SEXO              VARCHAR2(1 BYTE),
  NOM_SEXO              VARCHAR2(14 BYTE),
  IND_ESTADO            VARCHAR2(1 BYTE),
  IND_CODN820           VARCHAR2(2 BYTE)
);

CREATE TABLE ADMIN.GG_TETNIA(
  IND_ETN               VARCHAR2(2 BYTE) NOT NULL,
  NOM_ETN               VARCHAR2(30 BYTE) NOT NULL,
  IND_ESTADO            VARCHAR2(1 BYTE) NOT NULL,
  IND_INSCRITO          VARCHAR2(2 BYTE),
  COD_IFLETN            VARCHAR2(2 BYTE),
  COD_ETNIAEGRESO       VARCHAR2(2 BYTE),
  COD_ETNIAEGRNUEVO     VARCHAR2(2 BYTE)
);

CREATE TABLE ADMIN.GG_TESTCIV (
  COD_ESTCIV            VARCHAR2(1 BYTE) NOT NULL,
  NOM_ESTCIV            VARCHAR2(11 BYTE) NOT NULL,
  IND_ESTADO            VARCHAR2(1 BYTE) NOT NULL
);

CREATE TABLE ADMIN.GG_TPAIS (
  COD_PAIS              VARCHAR2(2 BYTE) NOT NULL,
  NOM_PAIS              VARCHAR2(25 BYTE) NOT NULL,
  IND_ESTADO            CHAR(1 BYTE)  NOT NULL,
  FEC_AUDITA            DATE NOT NULL,
  COD_USUARI            VARCHAR2(60 BYTE)  NOT NULL,
  COD_PAISEGR           NUMBER(3),
  IND_CODN820           VARCHAR2(3 BYTE),
  ID_PNTM               NUMBER
);

CREATE TABLE ADMIN.GG_TREGION (
  COD_REGION  VARCHAR2(3 BYTE),
  NOM_REGION  VARCHAR2(30 BYTE),
  COD_USUARI  VARCHAR2(60 BYTE),
  FEC_AUDITA  DATE,
  IND_ESTADO  VARCHAR2(1 BYTE)
);

CREATE TABLE ADMIN.GG_TGRUSAN (
  IND_GRUSAN  VARCHAR2(2 BYTE) NOT NULL,
  NOM_GRUSAN  VARCHAR2(7 BYTE) NOT NULL,
  IND_ESTADO  VARCHAR2(1 BYTE) NOT NULL
);

CREATE TABLE ADMIN.GG_TFACSAN (
  IND_FACSAN  VARCHAR2(2 BYTE) NOT NULL,
  NOM_FACSAN  VARCHAR2(7 BYTE) NOT NULL,
  IND_ESTADO  VARCHAR2(1 BYTE) NOT NULL
);

CREATE TABLE ADMIN.GG_TDATPREV (
  IND_PREVIS     VARCHAR2(4 BYTE),
  NOM_PREVIS     VARCHAR2(20 BYTE),
  NUM_PORCE      NUMBER(3),
  IND_ESTADO     VARCHAR2(1 BYTE),
  COD_USUARI     VARCHAR2(60 BYTE),
  FEC_AUDITA     DATE,
  COD_RUTINS     NUMBER(11),
  NOM_PREVISION  VARCHAR2(12 BYTE),
  IND_PREVISION  VARCHAR2(1 BYTE),
  IND_TIPCONT    VARCHAR2(4 BYTE),
  FAC_MEDIC      NUMBER(12,4),
  COD_EMPRESA    VARCHAR2(5 BYTE),
  COD_IFLPREVIS  VARCHAR2(1 BYTE),
  COD_PREVISION  VARCHAR2(3 BYTE),
  IND_CODN820    VARCHAR2(2 BYTE)
);

CREATE TABLE ADMIN.GG_TINSEMP (
  COD_RUTINS       NUMBER(10),
  COD_DIGVER       VARCHAR2(1 BYTE),
  NOM_INSEMP       VARCHAR2(50 BYTE),
  NOM_DIRECC       VARCHAR2(50 BYTE),
  NUM_TELEFO       NUMBER(10),
  IND_CONVEN       VARCHAR2(1 BYTE),
  IND_TIPO         VARCHAR2(1 BYTE),
  IND_ORDDET       VARCHAR2(1 BYTE),
  COD_USUARIO      VARCHAR2(60 BYTE),
  IND_ESTADO       VARCHAR2(1 BYTE),
  FEC_AUDITA       DATE,
  FEC_USRCREA      DATE,
  COD_USRCREA      VARCHAR2(60 BYTE),
  IND_SUCURSAL     VARCHAR2(1 BYTE),
  COD_EMPRESA      VARCHAR2(5 BYTE),
  COD_IFLINSEMP    VARCHAR2(3 BYTE),
  COD_PREVISION    VARCHAR2(3 BYTE),
  DES_INSTITUCION  VARCHAR2(50 BYTE),
  IND_HTEMUCO      NUMBER(3)
);

COMMIT;
/