ALTER SESSION SET CONTAINER         =  FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA    =  ADMIN;
ALTER SYSTEM SET NLS_DATE_FORMAT    =  'DD-MM-YYYY HH24:MI:SS' SCOPE=SPFILE;
ALTER SESSION SET NLS_DATE_FORMAT   = 'DD/MM/RR';

CREATE TABLE ADMIN.TABLA_PRUEBAS (
    ID              NUMBER, -- UN IDENTIFICADOR NUMÉRICO
    NOMBRE          VARCHAR2(50), -- UNA CADENA DE TEXTO CORTA
    DESCRIPCION     CLOB, -- UN TEXTO LARGO
    FECHA_CREACION  DATE, -- UNA FECHA
    HORA            TIMESTAMP, -- UNA MARCA DE TIEMPO CON FECHA Y HORA
    ES_ACTIVO       NUMBER(1), -- UN VALOR BOOLEANO REPRESENTADO COMO 0 O 1
    SALARIO         DECIMAL(10,2), -- UN NÚMERO DECIMAL PARA REPRESENTAR CANTIDADES, COMO DINERO
    IMAGEN          BLOB -- DATOS BINARIOS, COMO PODRÍA SER UNA IMAGEN O UN ARCHIVO
);
