ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = ADMIN;
/
CREATE TABLE ADMIN.GG_TGPACTE(
  NUM_FICHAE              NUMBER NOT NULL,
  COD_RUTPAC              NUMBER,
  COD_DIGVER              VARCHAR2(25 BYTE),
  NOM_NOMBRE              VARCHAR2(25 BYTE),
  NOM_APEPAT              VARCHAR2(20 BYTE),
  NOM_APEMAT              VARCHAR2(20 BYTE),
  FEC_NACIMI              DATE,
  IND_TISEXO              CHAR,
  IND_ESTCIV              CHAR,
  NOM_NPADRE              VARCHAR2(31 BYTE),
  NOM_NMADRE              VARCHAR2(31 BYTE),
  NOM_PAREJA              VARCHAR2(35 BYTE),
  IND_GRUCRO              CHAR,
  IND_TIPPAC              CHAR,
  COD_GRUSAN              VARCHAR2(10 BYTE),
  IND_ETN                 VARCHAR2(2 BYTE),
  OCUPACION               VARCHAR2(30 BYTE),
  LUGAR_TRAB              VARCHAR2(30 BYTE),
  NOM_DIRECC              VARCHAR2(100 BYTE),
  COD_COMUNA              VARCHAR2(15 BYTE),
  IND_URBRUR              VARCHAR2(1 BYTE),
  COD_PAIS                VARCHAR2(3 BYTE),
  COD_RUTTIT              NUMBER,
  COD_USRCREA             VARCHAR2(60 BYTE),
  FEC_USRCREA             DATE,
  COD_USUARI              VARCHAR2(60 BYTE),
  FEC_AUDITA              DATE,
  IND_ESTADO              CHAR,
  EMAIL                   VARCHAR2(65 BYTE),
  IND_FAX                 VARCHAR2(10 BYTE),
  IND_PERCETN             VARCHAR2(2 BYTE),
  COD_FACSAN              VARCHAR2(2 BYTE),
  IND_RECNAC              VARCHAR2(1 BYTE),
  COD_RUTREF              NUMBER,
  COD_DIGREF              VARCHAR2(1 BYTE),
  IND_REFER               VARCHAR2(1 BYTE),
  IND_RUT                 VARCHAR2(10 BYTE),
  IND_PERCAPITA           VARCHAR2(1 BYTE),
  EMP_PERCAPITA           VARCHAR2(3 BYTE),
  ALERGIAS                VARCHAR2(30 BYTE),
  CREDENCIAL              VARCHAR2(10 BYTE),
  INTG_PART_MULT          VARCHAR2(1 BYTE),
  NUM_TELEFO1_2           VARCHAR2(12 BYTE),
  NUM_TELEFO2_2           VARCHAR2(12 BYTE),
  NUM_CELULAR_2           VARCHAR2(12 BYTE),
  NUM_TELEFO1             VARCHAR2(12 BYTE),
  NUM_TELEFO2             VARCHAR2(12 BYTE),
  NUM_CELULAR             VARCHAR2(12 BYTE),
  COD_SISTEMA             VARCHAR2(10 BYTE),
  COD_SISTEMAUDITA        VARCHAR2(10 BYTE),
  COD_REGION              VARCHAR2(2 BYTE),
  COD_CIUDAD              VARCHAR2(15 BYTE),
  NUM_CASA                VARCHAR2(15 BYTE),
  COD_VIADIRECCION        VARCHAR2(2 BYTE),
  IND_CONDPRAIS           VARCHAR2(1 BYTE),
  NOM_RESTODIRECC         VARCHAR2(300 BYTE),
  CP_ID_CATOCUPAPAC       NUMBER             DEFAULT 0,
  IND_NIVELINSTRUC        NUMBER             DEFAULT 0,
  REP_LEGAL               VARCHAR2(300 BYTE),
  ID_EXTRANJERO           VARCHAR2(15 BYTE),
  IND_TIPOIDENTIFICA      NUMBER             DEFAULT 0,
  IND_EXTRANJERO          NUMBER             DEFAULT 0,
  NUM_IDENTIFICACION      VARCHAR2(30 BYTE),
  TIP_IDENTIFICACION      NUMBER,
  FEC_VENCEPASPORT        DATE,
  IND_CORTEINTERA         NUMBER             DEFAULT 0,
  COD_OCUPACION           VARCHAR2(5 BYTE),
  ID_FONASA               VARCHAR2(30 BYTE),
  FEC_IDFONASA            DATE,
  NOM_SOCIAL              VARCHAR2(50 BYTE),
  IND_TRANS               NUMBER,
  IND_SENAME              NUMBER             DEFAULT '0',
  COD_NACIONALIDAD        VARCHAR2(3 BYTE),
  EDAD_GESTA_SEMANA       NUMBER,
  EDAD_GESTA_DIAS         NUMBER,
  EDAD_CORREGIDA_SEMANA   NUMBER,
  EDAD_CORREGIDA_DIAS     NUMBER,
  IND_PREMATURO           NUMBER,
  ID_OCUPACION            NUMBER,
  IND_CATOCUPANEW         NUMBER,
  IND_NIVEL_EDUCACIONAL   NUMBER,
  IND_POBLACION_MIGRANTE  NUMBER,
  PESO                    NUMBER,
  TALLA                   NUMBER,
  IMC                     NUMBER,
  EDADGESTACIONAL         NUMBER,
  PRIMARY KEY (NUM_FICHAE)
);
COMMIT;
/

CREATE TABLE ADMIN.SO_TCPACTE (
  COD_RUTPAC              NUMBER,
  NUM_CORPAC              NUMBER,
  NUM_NFICHA              NUMBER,
  NUM_AFICHA              NUMBER,
  IND_ESTPAC              CHAR,
  COD_SERULA              VARCHAR2(7 BYTE),
  FEC_ULTASI              DATE,
  NUM_CORHOS              NUMBER,
  FEC_ULTSER              DATE,
  COD_ULTSER              VARCHAR2(3 BYTE),
  IND_ARCHIVO             VARCHAR2(1 BYTE),
  FEC_IMPRES              DATE,
  COD_USRCREA             VARCHAR2(60 BYTE),
  FEC_USRCREA             DATE,
  COD_USUARI              VARCHAR2(60 BYTE),
  FEC_AUDITA              DATE,
  IND_ESTADO              CHAR,
  COD_EMPRESA             VARCHAR2(5 BYTE),
  NOM_DIRECC              VARCHAR2(100 BYTE),
  NOM_CONTACTO            VARCHAR2(50 BYTE),
  DIRECC_CONTACTO         VARCHAR2(100 BYTE),
  NUM_FICHAE              NUMBER,
  IND_IMPRES              CHAR,
  NUM_TELEFO1_2           VARCHAR2(12 BYTE),
  TELEFO_CONTACTO_2       VARCHAR2(12 BYTE),
  NUM_TELEFO1             VARCHAR2(12 BYTE),
  TELEFO_CONTACTO         VARCHAR2(12 BYTE),
  COD_SISTEMA             VARCHAR2(10 BYTE),
  COD_SISTEMAUDITA        VARCHAR2(10 BYTE),
  COD_SECTOR              VARCHAR2(5 BYTE),
  COD_FAMILIA             VARCHAR2(15 BYTE),
  NUM_CASA                VARCHAR2(6 BYTE),
  COD_VIADIRECCION        VARCHAR2(2 BYTE),
  COD_COMUNAL             VARCHAR2(15 BYTE),
  COD_CIUDADL             VARCHAR2(15 BYTE),
  COD_REGIONL             VARCHAR2(2 BYTE)
);
COMMIT;
/

CREATE TABLE ADMIN.GG_TPACFALLECIDO (
  NUM_FICHAE              NUMBER NOT NULL,
  COD_RUTPAC              NUMBER,
  FEC_FALLECE             DATE,
  COD_USUARIINF           VARCHAR2(60 BYTE),
  FEC_INFORMA             DATE,
  COD_SISINFORMA          VARCHAR2(30 BYTE),
  COD_USRCREA             VARCHAR2(60 BYTE),
  FEC_USRCREA             DATE,
  COD_USUARI              VARCHAR2(60 BYTE),
  FEC_AUDITA              DATE,
  IND_ESTADO              VARCHAR2(1 BYTE)
);



CREATE TABLE ADMIN.GG_TSEXO (
  IND_SEXO                VARCHAR2(1 BYTE),
  NOM_SEXO                VARCHAR2(14 BYTE),
  IND_ESTADO              VARCHAR2(1 BYTE),
  IND_CODN820             VARCHAR2(2 BYTE)
);

Insert into ADMIN.GG_TSEXO (IND_SEXO, NOM_SEXO, IND_ESTADO, IND_CODN820) Values ('F', 'FEMENINO', 'V', '02');
Insert into ADMIN.GG_TSEXO (IND_SEXO, NOM_SEXO, IND_ESTADO, IND_CODN820) Values ('M', 'MASCULINO', 'V', '01');
Insert into ADMIN.GG_TSEXO (IND_SEXO, NOM_SEXO, IND_ESTADO, IND_CODN820) Values ('N', 'NO DETERMINADO', 'V', '03');
Insert into ADMIN.GG_TSEXO (IND_SEXO, NOM_SEXO, IND_ESTADO, IND_CODN820) Values ('D', 'DESCONOCIDO', 'V', '99');
COMMIT;
/

CREATE TABLE ADMIN.GG_TETNIA(
  IND_ETN               VARCHAR2(2 BYTE) NOT NULL,
  NOM_ETN               VARCHAR2(30 BYTE) NOT NULL,
  IND_ESTADO            VARCHAR2(1 BYTE) NOT NULL,
  IND_INSCRITO          VARCHAR2(2 BYTE),
  COD_IFLETN            VARCHAR2(2 BYTE),
  COD_ETNIAEGRESO       VARCHAR2(2 BYTE),
  COD_ETNIAEGRNUEVO     VARCHAR2(2 BYTE)
);

Insert into ADMIN.GG_TETNIA  (IND_ETN, NOM_ETN, IND_ESTADO, IND_INSCRITO, COD_IFLETN,   COD_ETNIAEGRESO, COD_ETNIAEGRNUEVO)
 Values ('0', 'NINGUNA', 'V', NULL, NULL,   '0', '00');

Insert into ADMIN.GG_TETNIA
   (IND_ETN, NOM_ETN, IND_ESTADO, IND_INSCRITO, COD_IFLETN,    COD_ETNIAEGRESO, COD_ETNIAEGRNUEVO)
 Values
   ('1', 'MAPUCHE', 'V', '04', '1',   '6', '06');
Insert into ADMIN.GG_TETNIA
   (IND_ETN, NOM_ETN, IND_ESTADO, IND_INSCRITO, COD_IFLETN, 
    COD_ETNIAEGRESO, COD_ETNIAEGRNUEVO)
 Values
   ('2', 'ATACAMEÑO', 'V', '05', '8', 
    '2', '02');
Insert into ADMIN.GG_TETNIA
   (IND_ETN, NOM_ETN, IND_ESTADO, IND_INSCRITO, COD_IFLETN, 
    COD_ETNIAEGRESO, COD_ETNIAEGRNUEVO)
 Values
   ('3', 'AYMARA', 'V', '01', '2', 
    '3', '03');
Insert into ADMIN.GG_TETNIA
   (IND_ETN, NOM_ETN, IND_ESTADO, IND_INSCRITO, COD_IFLETN, 
    COD_ETNIAEGRESO, COD_ETNIAEGRNUEVO)
 Values
   ('4', 'COLLAS', 'V', '06', '11', 
    '4', '04');
Insert into ADMIN.GG_TETNIA
   (IND_ETN, NOM_ETN, IND_ESTADO, IND_INSCRITO, COD_IFLETN, 
    COD_ETNIAEGRESO, COD_ETNIAEGRNUEVO)
 Values
   ('5', 'KAWASHKAR', 'V', '07', '12', 
    NULL, NULL);
Insert into ADMIN.GG_TETNIA
   (IND_ETN, NOM_ETN, IND_ESTADO, IND_INSCRITO, COD_IFLETN, 
    COD_ETNIAEGRESO, COD_ETNIAEGRNUEVO)
 Values
   ('6', 'PASCUENCE', 'V', '02', '3', 
    '8', '08');
Insert into ADMIN.GG_TETNIA
   (IND_ETN, NOM_ETN, IND_ESTADO, IND_INSCRITO, COD_IFLETN, 
    COD_ETNIAEGRESO, COD_ETNIAEGRNUEVO)
 Values
   ('7', 'QUECHUA', 'V', '03', '10', 
    '7', '07');
Insert into ADMIN.GG_TETNIA
   (IND_ETN, NOM_ETN, IND_ESTADO, IND_INSCRITO, COD_IFLETN, 
    COD_ETNIAEGRESO, COD_ETNIAEGRNUEVO)
 Values
   ('8', 'YAMANA/YAGAN/KAWASHKAR', 'V', NULL, '9', 
    '9', '09');
Insert into ADMIN.GG_TETNIA
   (IND_ETN, NOM_ETN, IND_ESTADO, IND_INSCRITO, COD_IFLETN, 
    COD_ETNIAEGRESO, COD_ETNIAEGRNUEVO)
 Values
   ('9', 'EXTRANJERO', 'E', NULL, NULL, 
    NULL, '00');
Insert into ADMIN.GG_TETNIA
   (IND_ETN, NOM_ETN, IND_ESTADO, IND_INSCRITO, COD_IFLETN, 
    COD_ETNIAEGRESO, COD_ETNIAEGRNUEVO)
 Values
   ('11', 'SIN ETNIA', 'V', '99', NULL, 
    NULL, '00');
Insert into ADMIN.GG_TETNIA
   (IND_ETN, NOM_ETN, IND_ESTADO, IND_INSCRITO, COD_IFLETN, 
    COD_ETNIAEGRESO, COD_ETNIAEGRNUEVO)
 Values
   ('12', 'NO INFORMADO', 'V', '00', NULL, 
    NULL, '00');
Insert into ADMIN.GG_TETNIA
   (IND_ETN, NOM_ETN, IND_ESTADO, IND_INSCRITO, COD_IFLETN, 
    COD_ETNIAEGRESO, COD_ETNIAEGRNUEVO)
 Values
   ('13', 'ALACALUFE', 'V', NULL, NULL, 
    '1', '01');
Insert into ADMIN.GG_TETNIA
   (IND_ETN, NOM_ETN, IND_ESTADO, IND_INSCRITO, COD_IFLETN, 
    COD_ETNIAEGRESO, COD_ETNIAEGRNUEVO)
 Values
   ('14', 'DIAGUITA', 'V', NULL, NULL, 
    '5', '05');
Insert into ADMIN.GG_TETNIA
   (IND_ETN, NOM_ETN, IND_ESTADO, IND_INSCRITO, COD_IFLETN, 
    COD_ETNIAEGRESO, COD_ETNIAEGRNUEVO)
 Values
   ('16', 'NO SABE', 'V', NULL, NULL, 
    NULL, '10');
Insert into ADMIN.GG_TETNIA
   (IND_ETN, NOM_ETN, IND_ESTADO, IND_INSCRITO, COD_IFLETN, 
    COD_ETNIAEGRESO, COD_ETNIAEGRNUEVO)
 Values
   ('17', 'NO RESPONDE', 'V', NULL, NULL, 
    NULL, '11');
COMMIT;
/

CREATE TABLE ADMIN.GG_TESTCIV (
  COD_ESTCIV            VARCHAR2(1 BYTE) NOT NULL,
  NOM_ESTCIV            VARCHAR2(11 BYTE) NOT NULL,
  IND_ESTADO            VARCHAR2(1 BYTE) NOT NULL
);
Insert into ADMIN.GG_TESTCIV
   (COD_ESTCIV, NOM_ESTCIV, IND_ESTADO)
 Values
   ('S', 'SOLTERO', 'V');
Insert into ADMIN.GG_TESTCIV
   (COD_ESTCIV, NOM_ESTCIV, IND_ESTADO)
 Values
   ('C', 'CASADO', 'V');
Insert into ADMIN.GG_TESTCIV
   (COD_ESTCIV, NOM_ESTCIV, IND_ESTADO)
 Values
   ('V', 'VIUDO', 'V');
Insert into ADMIN.GG_TESTCIV
   (COD_ESTCIV, NOM_ESTCIV, IND_ESTADO)
 Values
   ('O', 'CONVIVIENTE', 'V');
Insert into ADMIN.GG_TESTCIV
   (COD_ESTCIV, NOM_ESTCIV, IND_ESTADO)
 Values
   ('E', 'SEPARADO', 'V');
Insert into ADMIN.GG_TESTCIV
   (COD_ESTCIV, NOM_ESTCIV, IND_ESTADO)
 Values
   ('D', 'DIVORCIADO', 'V');
COMMIT;
/


CREATE TABLE ADMIN.GG_TPAIS (
  COD_PAIS              VARCHAR2(2 BYTE) NOT NULL,
  NOM_PAIS              VARCHAR2(25 BYTE) NOT NULL,
  IND_ESTADO            CHAR(1 BYTE)  NOT NULL,
  FEC_AUDITA            DATE NOT NULL,
  COD_USUARI            VARCHAR2(60 BYTE)  NOT NULL,
  COD_PAISEGR           NUMBER(3),
  IND_CODN820           VARCHAR2(3 BYTE),
  ID_PNTM               NUMBER
);


Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('AU', 'AUSTRALIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    502, '036', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('AT', 'AUSTRIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    404, '040', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('BE', 'BELGICA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    405, '056', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('BO', 'BOLIVIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    210, '068', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('BR', 'BRASIL', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    211, '076', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('BG', 'BULGARIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    408, '100', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('CA', 'CANADA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    212, '124', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('CL', 'CHILE', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    213, '152', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('CN', 'CHINA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    311, '156', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('CO', 'COLOMBIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    214, '170', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('CG', 'REPUBLICA DEL CONGO', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    139, NULL, NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('CR', 'COSTA RICA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    215, '188', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('HR', 'CROACIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    410, '191', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('CU', 'CUBA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    216, '192', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('CZ', 'REPUBLICA CHECA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    437, '203', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('DK', 'DINAMARCA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    411, '208', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('DO', 'REPUBLICA DOMINICANA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    244, '214', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('EC', 'ECUADOR', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    218, '218', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('EG', 'EGIPTO', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    113, '818', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('SV', 'EL SALVADOR', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    219, '222', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('ET', 'ETIOPIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    115, '231', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('FI', 'FINLANDIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    416, '246', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('FR', 'FRANCIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    417, '250', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('DE', 'ALEMANIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    402, '276', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('GR', 'GRECIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    419, '300', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('GN', 'GUINEA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    119, '324', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('HT', 'HAITI', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    227, '332', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('HN', 'HONDURAS', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    228, '340', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('HK', 'HONG KONG', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    315, '344', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('HG', 'HUNGRIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    421, '348', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('IS', 'ISLANDIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    423, '352', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('IN', 'INDIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    316, '356', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('ID', 'INDONESIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    317, '360', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('IR', 'IRAN', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    319, '364', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('IQ', 'IRAK', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    318, '368', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('IE', 'IRLANDA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    422, '372', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('IL', 'ISRAEL', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    320, '376', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('IT', 'ITALIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    425, '380', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('JM', 'JAMAICA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    235, '388', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('JP', 'JAPON', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    321, '392', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('KR', 'COREA DEL NORTE', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    338, '408', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('MX', 'MEXICO', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    237, '484', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('MA', 'MARRUECOS', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    130, '504', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('NI', 'NICARAGUA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    239, '558', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('NO', 'NORUEGA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    433, '578', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('PK', 'PAKISTAN', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    334, '586', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('PA', 'PANAMA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    240, '591', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('PY', 'PARAGUAY', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    241, '600', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('PE', 'PERU', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    242, '604', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('PL', 'POLONIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    434, '616', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('PT', 'PORTUGAL', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    435, '620', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('PR', 'PUERTO RICO', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    243, '630', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('RO', 'RUMANIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    439, '642', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('SA', 'ARABIA SAUDITA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    302, '682', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('SG', 'SINGAPUR', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    340, '702', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('ES', 'ESPAÑA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    414, '724', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('SE', 'SUIZA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    442, '756', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('CH', 'SUECIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    441, '752', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('TH', 'TAILANDIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    343, '764', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('GB', 'INGLATERRA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    436, NULL, NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('US', 'ESTADOS UNIDOS', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    220, '840', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('UY', 'URUGUAY', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    251, '858', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('VE', 'VENEZUELA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    252, '862', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('YU', 'YUGOSLAVIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    445, NULL, NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('UA', 'UCRANIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    443, '804', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('RU', 'RUSIA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    339, '643', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('FL', 'FILIPINAS', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    313, '608', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('KS', 'COREA DEL SUR', 'V', TO_DATE('08/30/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    337, '410', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('RC', 'R. DEMOCRATICA DEL CONGO', 'V', TO_DATE('08/30/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    140, NULL, NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('NL', 'HOLANDA', 'V', TO_DATE('11/09/2017 14:49:47', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    528, NULL, NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('AR', 'ARGENTINA', 'V', TO_DATE('09/14/2002 06:29:51', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    204, '032', NULL);
Insert into ADMIN.GG_TPAIS
   (COD_PAIS, NOM_PAIS, IND_ESTADO, FEC_AUDITA, COD_USUARI, 
    COD_PAISEGR, IND_CODN820, ID_PNTM)
 Values
   ('GH', 'GHANA', 'V', TO_DATE('08/06/2019 09:53:35', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN', 
    NULL, '288', NULL);
COMMIT;
/

CREATE TABLE ADMIN.GG_TREGION (
  COD_REGION  VARCHAR2(3 BYTE),
  NOM_REGION  VARCHAR2(30 BYTE),
  COD_USUARI  VARCHAR2(60 BYTE),
  FEC_AUDITA  DATE,
  IND_ESTADO  VARCHAR2(1 BYTE)
);


Insert into ADMIN.GG_TREGION
   (COD_REGION, NOM_REGION, COD_USUARI, FEC_AUDITA, IND_ESTADO)
 Values
   ('01', 'TARAPACA', 'ADMIN', TO_DATE('09/13/2002 12:48:39', 'MM/DD/YYYY HH24:MI:SS'), 'V');
Insert into ADMIN.GG_TREGION
   (COD_REGION, NOM_REGION, COD_USUARI, FEC_AUDITA, IND_ESTADO)
 Values
   ('02', 'ANTOFAGASTA', 'ADMIN', TO_DATE('09/13/2002 12:48:39', 'MM/DD/YYYY HH24:MI:SS'), 'V');
Insert into ADMIN.GG_TREGION
   (COD_REGION, NOM_REGION, COD_USUARI, FEC_AUDITA, IND_ESTADO)
 Values
   ('03', 'ATACAMA', 'ADMIN', TO_DATE('09/13/2002 12:48:39', 'MM/DD/YYYY HH24:MI:SS'), 'V');
Insert into ADMIN.GG_TREGION
   (COD_REGION, NOM_REGION, COD_USUARI, FEC_AUDITA, IND_ESTADO)
 Values
   ('04', 'COQUIMBO', 'ADMIN', TO_DATE('09/13/2002 12:48:39', 'MM/DD/YYYY HH24:MI:SS'), 'V');
Insert into ADMIN.GG_TREGION
   (COD_REGION, NOM_REGION, COD_USUARI, FEC_AUDITA, IND_ESTADO)
 Values
   ('05', 'VALPARAISO', 'ADMIN', TO_DATE('09/13/2002 12:48:39', 'MM/DD/YYYY HH24:MI:SS'), 'V');
Insert into ADMIN.GG_TREGION
   (COD_REGION, NOM_REGION, COD_USUARI, FEC_AUDITA, IND_ESTADO)
 Values
   ('06', 'LIB GRAL BDO O''HIGGINS', 'ADMIN', TO_DATE('09/13/2002 12:48:39', 'MM/DD/YYYY HH24:MI:SS'), 'V');
Insert into ADMIN.GG_TREGION
   (COD_REGION, NOM_REGION, COD_USUARI, FEC_AUDITA, IND_ESTADO)
 Values
   ('07', 'DEL MAULE', 'ADMIN', TO_DATE('09/13/2002 12:48:39', 'MM/DD/YYYY HH24:MI:SS'), 'V');
Insert into ADMIN.GG_TREGION
   (COD_REGION, NOM_REGION, COD_USUARI, FEC_AUDITA, IND_ESTADO)
 Values
   ('08', 'BIO-BIO', 'ADMIN', TO_DATE('09/13/2002 12:48:39', 'MM/DD/YYYY HH24:MI:SS'), 'V');
Insert into ADMIN.GG_TREGION
   (COD_REGION, NOM_REGION, COD_USUARI, FEC_AUDITA, IND_ESTADO)
 Values
   ('09', 'ARAUCANIA', 'ADMIN', TO_DATE('09/13/2002 12:48:39', 'MM/DD/YYYY HH24:MI:SS'), 'V');
Insert into ADMIN.GG_TREGION
   (COD_REGION, NOM_REGION, COD_USUARI, FEC_AUDITA, IND_ESTADO)
 Values
   ('10', 'DE LOS LAGOS', 'ADMIN', TO_DATE('09/13/2002 12:48:39', 'MM/DD/YYYY HH24:MI:SS'), 'V');
Insert into ADMIN.GG_TREGION
   (COD_REGION, NOM_REGION, COD_USUARI, FEC_AUDITA, IND_ESTADO)
 Values
   ('11', 'AISEN', 'ADMIN', TO_DATE('09/13/2002 12:48:39', 'MM/DD/YYYY HH24:MI:SS'), 'V');
Insert into ADMIN.GG_TREGION
   (COD_REGION, NOM_REGION, COD_USUARI, FEC_AUDITA, IND_ESTADO)
 Values
   ('12', 'MAGALLANES Y ANTARTICA', 'ADMIN', TO_DATE('09/13/2002 12:48:39', 'MM/DD/YYYY HH24:MI:SS'), 'V');
Insert into ADMIN.GG_TREGION
   (COD_REGION, NOM_REGION, COD_USUARI, FEC_AUDITA, IND_ESTADO)
 Values
   ('13', 'METROPOLITANA', 'ADMIN', TO_DATE('09/13/2002 12:48:39', 'MM/DD/YYYY HH24:MI:SS'), 'V');
Insert into ADMIN.GG_TREGION
   (COD_REGION, NOM_REGION, COD_USUARI, FEC_AUDITA, IND_ESTADO)
 Values
   ('99', 'IGNORADA', 'ADMIN', TO_DATE('09/13/2002 12:48:39', 'MM/DD/YYYY HH24:MI:SS'), 'V');
COMMIT;
/






CREATE TABLE ADMIN.GG_TGRUSAN (
  IND_GRUSAN  VARCHAR2(2 BYTE) NOT NULL,
  NOM_GRUSAN  VARCHAR2(7 BYTE) NOT NULL,
  IND_ESTADO  VARCHAR2(1 BYTE) NOT NULL
);

Insert into ADMIN.GG_TGRUSAN
   (IND_GRUSAN, NOM_GRUSAN, IND_ESTADO)
 Values
   ('NS', 'NO SABE', 'V');
Insert into ADMIN.GG_TGRUSAN
   (IND_GRUSAN, NOM_GRUSAN, IND_ESTADO)
 Values
   ('A', 'A', 'V');
Insert into ADMIN.GG_TGRUSAN
   (IND_GRUSAN, NOM_GRUSAN, IND_ESTADO)
 Values
   ('B', 'B', 'V');
Insert into ADMIN.GG_TGRUSAN
   (IND_GRUSAN, NOM_GRUSAN, IND_ESTADO)
 Values
   ('AB', 'AB', 'V');
Insert into ADMIN.GG_TGRUSAN
   (IND_GRUSAN, NOM_GRUSAN, IND_ESTADO)
 Values
   ('O', 'O', 'V');
COMMIT;
/

CREATE TABLE ADMIN.GG_TFACSAN (
  IND_FACSAN  VARCHAR2(2 BYTE) NOT NULL,
  NOM_FACSAN  VARCHAR2(7 BYTE) NOT NULL,
  IND_ESTADO  VARCHAR2(1 BYTE) NOT NULL
);

Insert into ADMIN.GG_TFACSAN  (IND_FACSAN, NOM_FACSAN, IND_ESTADO) Values ('NS', 'NO SABE', 'V');
Insert into ADMIN.GG_TFACSAN  (IND_FACSAN, NOM_FACSAN, IND_ESTADO) Values ('1', 'RH(+)', 'V');
Insert into ADMIN.GG_TFACSAN  (IND_FACSAN, NOM_FACSAN, IND_ESTADO) Values ('0', 'RH(-)', 'V');
COMMIT;
/

CREATE TABLE ADMIN.GG_TDATPREV (
  IND_PREVIS     VARCHAR2(4 BYTE),
  NOM_PREVIS     VARCHAR2(20 BYTE),
  NUM_PORCE      NUMBER(3),
  IND_ESTADO     VARCHAR2(1 BYTE),
  COD_USUARI     VARCHAR2(60 BYTE),
  FEC_AUDITA     DATE,
  COD_RUTINS     NUMBER(11),
  NOM_PREVISION  VARCHAR2(12 BYTE),
  IND_PREVISION  VARCHAR2(1 BYTE),
  IND_TIPCONT    VARCHAR2(4 BYTE),
  FAC_MEDIC      NUMBER(12,4),
  COD_EMPRESA    VARCHAR2(5 BYTE),
  COD_IFLPREVIS  VARCHAR2(1 BYTE),
  COD_PREVISION  VARCHAR2(3 BYTE),
  IND_CODN820    VARCHAR2(2 BYTE)
);

Insert into ADMIN.GG_TDATPREV
   (IND_PREVIS, NOM_PREVIS, NUM_PORCE, IND_ESTADO, COD_USUARI, 
    FEC_AUDITA, COD_RUTINS, NOM_PREVISION, IND_PREVISION, IND_TIPCONT, 
    FAC_MEDIC, COD_EMPRESA, COD_IFLPREVIS, COD_PREVISION, IND_CODN820)
 Values
   ('SP', 'SIN PREVISION', 0, 'V', 'ADMIN', 
    TO_DATE('04/29/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 61603000, 'NO DEFINIDO', NULL, NULL, 
    0, '100', '0', NULL, '96');
Insert into ADMIN.GG_TDATPREV
   (IND_PREVIS, NOM_PREVIS, NUM_PORCE, IND_ESTADO, COD_USUARI, 
    FEC_AUDITA, COD_RUTINS, NOM_PREVISION, IND_PREVISION, IND_TIPCONT, 
    FAC_MEDIC, COD_EMPRESA, COD_IFLPREVIS, COD_PREVISION, IND_CODN820)
 Values
   ('E', 'DESCONOCIDO', 0, 'V', 'ADMIN', 
    TO_DATE('04/10/2018 16:04:33', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'DESCONOCIDO', NULL, NULL, 
    NULL, '100', NULL, NULL, '99');
Insert into ADMIN.GG_TDATPREV
   (IND_PREVIS, NOM_PREVIS, NUM_PORCE, IND_ESTADO, COD_USUARI, 
    FEC_AUDITA, COD_RUTINS, NOM_PREVISION, IND_PREVISION, IND_TIPCONT, 
    FAC_MEDIC, COD_EMPRESA, COD_IFLPREVIS, COD_PREVISION, IND_CODN820)
 Values
   ('M', 'SISA', 100, 'V', 'ADMIN', 
    TO_DATE('04/10/2018 16:07:47', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'SISA', NULL, NULL, 
    NULL, '100', NULL, NULL, '05');
Insert into ADMIN.GG_TDATPREV
   (IND_PREVIS, NOM_PREVIS, NUM_PORCE, IND_ESTADO, COD_USUARI, 
    FEC_AUDITA, COD_RUTINS, NOM_PREVISION, IND_PREVISION, IND_TIPCONT, 
    FAC_MEDIC, COD_EMPRESA, COD_IFLPREVIS, COD_PREVISION, IND_CODN820)
 Values
   ('A', 'BENEFICIARIO A', 0, 'V', 'ADMIN', 
    TO_DATE('09/14/2002 06:31:02', 'MM/DD/YYYY HH24:MI:SS'), 61603000, 'LEY 18469', 'A', '04', 
    0, '100', '1', 'GA', '01');
Insert into ADMIN.GG_TDATPREV
   (IND_PREVIS, NOM_PREVIS, NUM_PORCE, IND_ESTADO, COD_USUARI, 
    FEC_AUDITA, COD_RUTINS, NOM_PREVISION, IND_PREVISION, IND_TIPCONT, 
    FAC_MEDIC, COD_EMPRESA, COD_IFLPREVIS, COD_PREVISION, IND_CODN820)
 Values
   ('B', 'BENEFICIARIO B', 0, 'V', 'ADMIN', 
    TO_DATE('09/14/2002 06:31:02', 'MM/DD/YYYY HH24:MI:SS'), 61603000, 'LEY 18469', 'B', '04', 
    0, '100', '2', 'GB', '01');
Insert into ADMIN.GG_TDATPREV
   (IND_PREVIS, NOM_PREVIS, NUM_PORCE, IND_ESTADO, COD_USUARI, 
    FEC_AUDITA, COD_RUTINS, NOM_PREVISION, IND_PREVISION, IND_TIPCONT, 
    FAC_MEDIC, COD_EMPRESA, COD_IFLPREVIS, COD_PREVISION, IND_CODN820)
 Values
   ('C', 'BENEFICIARIO C', 10, 'V', 'ADMIN', 
    TO_DATE('09/14/2002 06:31:02', 'MM/DD/YYYY HH24:MI:SS'), 61603000, 'LEY 18469', 'C', '04', 
    0.4, '100', '3', 'GC', '01');
Insert into ADMIN.GG_TDATPREV
   (IND_PREVIS, NOM_PREVIS, NUM_PORCE, IND_ESTADO, COD_USUARI, 
    FEC_AUDITA, COD_RUTINS, NOM_PREVISION, IND_PREVISION, IND_TIPCONT, 
    FAC_MEDIC, COD_EMPRESA, COD_IFLPREVIS, COD_PREVISION, IND_CODN820)
 Values
   ('D', 'BENEFICIARIO D', 20, 'V', 'ADMIN', 
    TO_DATE('09/14/2002 06:31:02', 'MM/DD/YYYY HH24:MI:SS'), 61603000, 'LEY 18469', 'D', '04', 
    0.65, '100', '4', 'GD', '01');
Insert into ADMIN.GG_TDATPREV
   (IND_PREVIS, NOM_PREVIS, NUM_PORCE, IND_ESTADO, COD_USUARI, 
    FEC_AUDITA, COD_RUTINS, NOM_PREVISION, IND_PREVISION, IND_TIPCONT, 
    FAC_MEDIC, COD_EMPRESA, COD_IFLPREVIS, COD_PREVISION, IND_CODN820)
 Values
   ('O', 'CONVENIADO', 100, 'V', 'ADMIN', 
    TO_DATE('09/14/2002 06:31:02', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'OTROS', 'O', '02', 
    1, '100', '5', NULL, '99');
Insert into ADMIN.GG_TDATPREV
   (IND_PREVIS, NOM_PREVIS, NUM_PORCE, IND_ESTADO, COD_USUARI, 
    FEC_AUDITA, COD_RUTINS, NOM_PREVISION, IND_PREVISION, IND_TIPCONT, 
    FAC_MEDIC, COD_EMPRESA, COD_IFLPREVIS, COD_PREVISION, IND_CODN820)
 Values
   ('R', 'PRAIS', 0, 'V', 'ADMIN', 
    TO_DATE('09/14/2002 06:31:02', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'PRAIS', 'R', '04', 
    0, '100', '5', NULL, '99');
Insert into ADMIN.GG_TDATPREV
   (IND_PREVIS, NOM_PREVIS, NUM_PORCE, IND_ESTADO, COD_USUARI, 
    FEC_AUDITA, COD_RUTINS, NOM_PREVISION, IND_PREVISION, IND_TIPCONT, 
    FAC_MEDIC, COD_EMPRESA, COD_IFLPREVIS, COD_PREVISION, IND_CODN820)
 Values
   ('I', 'ISAPRE', 100, 'V', 'ADMIN', 
    TO_DATE('09/14/2002 06:31:02', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'ISAPRE', 'I', '01', 
    1, '100', '5', NULL, '02');
Insert into ADMIN.GG_TDATPREV
   (IND_PREVIS, NOM_PREVIS, NUM_PORCE, IND_ESTADO, COD_USUARI, 
    FEC_AUDITA, COD_RUTINS, NOM_PREVISION, IND_PREVISION, IND_TIPCONT, 
    FAC_MEDIC, COD_EMPRESA, COD_IFLPREVIS, COD_PREVISION, IND_CODN820)
 Values
   ('P', 'PARTICULAR', 100, 'V', 'ADMIN', 
    TO_DATE('09/14/2002 06:31:02', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'PARTICULAR', 'P', '07', 
    1, '100', '5', NULL, '99');
Insert into ADMIN.GG_TDATPREV
   (IND_PREVIS, NOM_PREVIS, NUM_PORCE, IND_ESTADO, COD_USUARI, 
    FEC_AUDITA, COD_RUTINS, NOM_PREVISION, IND_PREVISION, IND_TIPCONT, 
    FAC_MEDIC, COD_EMPRESA, COD_IFLPREVIS, COD_PREVISION, IND_CODN820)
 Values
   ('V', 'VERIFICAR', 0, 'E', 'ADMIN', 
    TO_DATE('09/14/2002 06:31:02', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'OTROS', NULL, NULL, 
    0, '100', '5', NULL, '99');
Insert into ADMIN.GG_TDATPREV
   (IND_PREVIS, NOM_PREVIS, NUM_PORCE, IND_ESTADO, COD_USUARI, 
    FEC_AUDITA, COD_RUTINS, NOM_PREVISION, IND_PREVISION, IND_TIPCONT, 
    FAC_MEDIC, COD_EMPRESA, COD_IFLPREVIS, COD_PREVISION, IND_CODN820)
 Values
   ('U', 'PUENTE', 0, 'V', 'ADMIN', 
    TO_DATE('09/14/2002 06:31:02', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'PUENTE', NULL, '04', 
    0, '100', '5', NULL, '99');
Insert into ADMIN.GG_TDATPREV
   (IND_PREVIS, NOM_PREVIS, NUM_PORCE, IND_ESTADO, COD_USUARI, 
    FEC_AUDITA, COD_RUTINS, NOM_PREVISION, IND_PREVISION, IND_TIPCONT, 
    FAC_MEDIC, COD_EMPRESA, COD_IFLPREVIS, COD_PREVISION, IND_CODN820)
 Values
   ('F', 'CAPREDENA', 100, 'V', 'ADMIN', 
    TO_DATE('01/12/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 61108000, 'CAPREDENA', 'F', NULL, 
    NULL, '100', NULL, NULL, '03');
Insert into ADMIN.GG_TDATPREV
   (IND_PREVIS, NOM_PREVIS, NUM_PORCE, IND_ESTADO, COD_USUARI, 
    FEC_AUDITA, COD_RUTINS, NOM_PREVISION, IND_PREVISION, IND_TIPCONT, 
    FAC_MEDIC, COD_EMPRESA, COD_IFLPREVIS, COD_PREVISION, IND_CODN820)
 Values
   ('G', 'DIPRECA', 100, 'V', 'ADMIN', 
    TO_DATE('01/12/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 61513000, 'DIPRECA', 'G', NULL, 
    NULL, '100', NULL, NULL, '04');
COMMIT;
/

CREATE TABLE ADMIN.GG_TINSEMP (
  COD_RUTINS       NUMBER(10),
  COD_DIGVER       VARCHAR2(1 BYTE),
  NOM_INSEMP       VARCHAR2(50 BYTE),
  NOM_DIRECC       VARCHAR2(50 BYTE),
  NUM_TELEFO       NUMBER(10),
  IND_CONVEN       VARCHAR2(1 BYTE),
  IND_TIPO         VARCHAR2(1 BYTE),
  IND_ORDDET       VARCHAR2(1 BYTE),
  COD_USUARIO      VARCHAR2(60 BYTE),
  IND_ESTADO       VARCHAR2(1 BYTE),
  FEC_AUDITA       DATE,
  FEC_USRCREA      DATE,
  COD_USRCREA      VARCHAR2(60 BYTE),
  IND_SUCURSAL     VARCHAR2(1 BYTE),
  COD_EMPRESA      VARCHAR2(5 BYTE),
  COD_IFLINSEMP    VARCHAR2(3 BYTE),
  COD_PREVISION    VARCHAR2(3 BYTE),
  DES_INSTITUCION  VARCHAR2(50 BYTE),
  IND_HTEMUCO      NUMBER(3)
);

Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (61603000, '0', 'FONASA', NULL, NULL, 
    NULL, 'F', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '1', NULL, NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (96501450, '0', 'ISAPRE ING', NULL, NULL, 
    NULL, 'I', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '4', '78', 'ING SALUD', NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (96572800, '7', 'ISAPRE BANMEDICA S.A.', NULL, NULL, 
    NULL, 'I', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '3', '99', 'BANMEDICA', 8);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (96522500, '5', 'ISAPRE MAS VIDA S.A.', NULL, NULL, 
    NULL, 'I', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '15', '88', 'MAS VIDA', 17);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (96502530, '8', 'ISAPRE VIDA TRES S.A.', NULL, NULL, 
    NULL, 'I', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '21', '80', 'VIDA TRES', 20);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (96856780, '2', 'ISAPRE CONSALUD  S.A.', NULL, NULL, 
    NULL, 'I', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '9', '71', 'CONSALUD', 11);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (95000000, '7', 'ISAPRE CIGNA S.A.', NULL, NULL, 
    NULL, 'I', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '24', '66', 'CIGNA SALUD', NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (96504160, '5', 'ISAPRE FERROSALUD', NULL, NULL, 
    NULL, 'I', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '12', '81', 'FERROSALUD', NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (71235700, '2', 'ISPRE FUNDACIÓN BANCO ESTADO', NULL, NULL, 
    NULL, 'I', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '14', '76', 'BANCO DEL ESTADO', 15);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (94954000, '6', 'ISAPRE COLMENA GOLDEN CROSS S.A.', NULL, NULL, 
    NULL, 'I', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '2', '67', 'COLMENA GOLDEN CROSS', 10);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (79727230, '2', 'ISAPRE ISTEL LTDA.', NULL, NULL, 
    NULL, 'I', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '11', '85', 'ISTEL', NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (61103024, 'K', 'F.A.CH.', NULL, NULL, 
    'C', 'D', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, 'OO', NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (72504200, '0', 'CORP.  MUTUAL FERROVIARIA', NULL, NULL, 
    'C', 'E', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, 'OO', NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (61101032, 'K', 'FONDO DE SALUD PREV. DEL EJERCITO', NULL, NULL, 
    'C', 'D', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, 'OO', NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (99061000, '2', 'AGF ALLIANZ CHILE COMPAÑIA DE SEGUROS GRALES S.A.', 'HENDAYA Nº60 PISO 10 LAS CONDES STGO.', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (70360100, '6', 'ASCH  -  ASOCIACIÓN CHILENA DE SEGURIDAD', NULL, NULL, 
    NULL, 'T', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'OO', NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (61202016, '7', 'BIENESTAR M.O.P.', NULL, NULL, 
    'C', 'E', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, 'OO', NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (96579130, '2', 'BIENESTAR PERSONAL ESSAR', NULL, NULL, 
    'C', 'E', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, 'OO', NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (61308017, '1', 'BIENESTAR PERSONAL S.A.G.', NULL, NULL, 
    'C', 'E', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, 'OO', NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (61108000, 'K', 'CAPREDENA', NULL, NULL, 
    'C', 'D', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '23', 'FA', NULL, 7);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (70375900, '4', 'COOP. DE SERV. MÉDICOS SERMECOP LTDA.', NULL, NULL, 
    'C', 'E', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, 'OO', NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (72114200, '0', 'CORBAT', NULL, NULL, 
    'C', 'E', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, 'OO', NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (61513000, '1', 'DIPRECA', NULL, NULL, 
    'C', 'D', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '22', 'OO', NULL, 6);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (82733800, '1', 'FUNDACIÓN MAGISTERIO DE LA ARAUCANIA', NULL, NULL, 
    'C', 'E', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, 'OO', NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (61533000, '0', 'I.N.P.', NULL, NULL, 
    NULL, 'T', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, 'OO', NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (70285100, '9', 'MUTUAL DE SEGURIDAD C. CH. C.', NULL, NULL, 
    NULL, 'T', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, 'OO', NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (99147000, 'K', 'AXA SEGUROS GENERALES S.A.', 'HUERFANOS Nº1189 PISOS 2 - 3 - 4 STGO.', NULL, 
    NULL, 'A', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (99302000, '1', 'SEGUROS SECURITY PREVISION GENERALES S.A.', 'HENDAYA Nº60 PISO 7 LAS CONDES STGO.', NULL, 
    NULL, 'A', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (99001000, '5', 'ING SEGUROS GENERALES S.A.', 'SUECIA Nº211 PROVIDENCIA SANTIAGO', NULL, 
    NULL, 'A', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (96549050, '7', 'ING SEGUROS DE VIDA S.A.', 'SUECIA Nº211 PROVIDENCIA SANTIAGO', NULL, 
    NULL, 'A', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (99155000, '3', 'ABN AMRO CHILE SEGUROS GENERALES', 'APOQUINDO Nº1335 LOCAL 101 LAS CONDES', NULL, 
    NULL, 'A', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (99288000, '7', 'LA INTERAMERICANA CIA. DE SEGUROS GENERALES S.A.', 'AGUSTINAS Nº640 PISO 8 - 9 STGO.', NULL, 
    NULL, 'A', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (99289000, '2', 'LA INTERAMERICANA CIA DE SEGUROS DE VIDA S.A.', 'AGUSTINAS Nº640 PISO 16 STGO.', NULL, 
    NULL, 'A', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (96508210, '7', 'MAPFRE SEGUROS GRALES. DE CHILE S.A.', 'TEATINOS Nº 280 PISO 4 STGO.', NULL, 
    NULL, 'A', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (99010000, '4', 'CIA. NACIONAL DE SEGUROS GRALES. UNION ESPAÑOLA', 'MATIAS CAUSIÑO Nº 150 PISO 2 OF. 201 STGO.', NULL, 
    NULL, 'A', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (99225000, '3', 'CIGNA COMPAÑIAS DE SEGUROS (CHILE S.A.)', 'MIRAFLORES Nº222 PISO 17 STGO.', NULL, 
    NULL, 'A', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (99037000, '1', 'CHILENA CONSOLIDADA SEGUROS GRALES. S.A.', 'AVDA. PEDRO DE VALDIVIA Nº195 PROVIDENCIA STGO.', NULL, 
    NULL, 'A', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (96534940, '5', 'LE MANS ISE COMPAÑIA DE SEGUROS GRALES. S.A.', 'ENCOMENDEROS Nº113 LAS CONDES SANTIAGO', NULL, 
    NULL, 'A', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (99285000, '0', 'COMPAÑIA DE SEGUROS GENERALES CRUZ DEL SUR S.A.', 'AVDA. EL GOLF Nº150 LAS CONDES STGO.', NULL, 
    NULL, 'A', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (94510000, '1', 'RENTA NACIONAL CIA. DE SEGUROS GENERALES S.A.', 'AMUNATEGUI Nº178 PISO 2 STGO.', NULL, 
    NULL, 'A', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (96654180, '6', 'CIA. SEGUROS GRALES. CONSORCIO NAC. DE SEG. S.A.', 'EL BOSQUE SUR Nº130 PISO 6 LAS CONDES STGO.', NULL, 
    NULL, 'A', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (99017000, '2', 'ROYAL Y SUN ALLIANCE SEGUROS (CHILE) S.A.', 'AVDA. PROVIDENCIA 1760 PISO 4 STGO.', NULL, 
    NULL, 'A', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (96683120, '0', 'COMPAÑIA DE SEGUROS GRALES. LAS AMERICAS', 'AVDA. EL BOSQUE NORTE Nº0440 PISO 7 OF. 702 STGO.', NULL, 
    NULL, 'A', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (99048000, '1', 'COMPAÑIA DE SEGUROS ITALIA S.A.', 'COCHRANE Nº857 VALPARAISO', NULL, 
    NULL, 'A', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, NULL, NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (70015580, '3', 'I.S.T.', 'AVDA. COLON 3430 TALCAHUANO', NULL, 
    NULL, 'T', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, 'OO', NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (11111111, '1', 'ARMADA DE CHILE', 'NN', NULL, 
    'C', 'D', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    NULL, 'OO', NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (70905700, '6', 'FUNDACION DE SALUD EL TENIENTE', NULL, NULL, 
    NULL, 'I', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '13', '63', NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (81461700, '9', 'PROMEPART ISAPRE', NULL, NULL, 
    NULL, 'I', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '17', '57', NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (88497700, '4', 'SAN LORENZO LTDA.', NULL, NULL, 
    NULL, 'I', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '19', '62', NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (79566720, '2', 'CHUQUICAMATA LTDA.', NULL, NULL, 
    NULL, 'I', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '8', '65', NULL, 9);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (89441300, 'K', 'RIO BLANCO LTDA.', NULL, NULL, 
    NULL, 'I', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '18', '68', NULL, 18);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (95078000, '2', 'NORMEDICA S.A.', NULL, NULL, 
    NULL, 'I', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '16', '70', NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (79906120, '1', 'CRUZ DEL NORTE LTDA.', NULL, NULL, 
    NULL, 'I', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '10', '94', NULL, 13);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (96645500, '4', 'SFERA S.A.', NULL, NULL, 
    NULL, 'I', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '20', '04', NULL, NULL);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (96936100, '0', 'ALEMANA SALUD S.A.', NULL, NULL, 
    NULL, 'I', NULL, 'CAPACITA', 'V', 
    NULL, NULL, NULL, NULL, '100', 
    '7', 'OO', NULL, 21);
Insert into ADMIN.GG_TINSEMP
   (COD_RUTINS, COD_DIGVER, NOM_INSEMP, NOM_DIRECC, NUM_TELEFO, 
    IND_CONVEN, IND_TIPO, IND_ORDDET, COD_USUARIO, IND_ESTADO, 
    FEC_AUDITA, FEC_USRCREA, COD_USRCREA, IND_SUCURSAL, COD_EMPRESA, 
    COD_IFLINSEMP, COD_PREVISION, DES_INSTITUCION, IND_HTEMUCO)
 Values
   (61955100, '1', 'OTRA INSTITUCION', NULL, NULL, 
    NULL, 'A', NULL, 'ADMIN', 'V', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 0);


COMMIT;
/