ALTER SESSION SET CONTAINER         =  FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA    =  ADMIN;
    -- OBJECT TYPES
    CREATE OR REPLACE TYPE ADMIN.MYTYPE2 as object (a int,b varchar2(100));
    CREATE OR REPLACE TYPE ADMIN.OBJECT_PUNTOS_ENTREGA as object (
        V_ID_ROTULADO       INTEGER,
        V_COD_EMPRESA       varchar2(50),
        V_TXT_OBSERVACION   varchar2(255),
        V_IND_GESPAB        INTEGER,
        V_IND_ZONA_GESPAB   INTEGER
    );
    -- COLLECTIONS TYPES
    CREATE OR REPLACE TYPE ADMIN.LIST_OF_NAMES_T            IS VARRAY(10) OF VARCHAR2(100);
    CREATE OR REPLACE TYPE ADMIN.LISTA_HISTOPATOLOGICO      IS TABLE OF VARCHAR2(40 BYTE);
    CREATE OR REPLACE TYPE ADMIN.ARR_TYPE                   IS TABLE OF VARCHAR2(40 BYTE);
    CREATE OR REPLACE TYPE ADMIN.MYTABLE2                   AS TABLE OF myType2;
    CREATE OR REPLACE TYPE ADMIN.COLLECTION_PUNTOS_ENTREGA  AS TABLE OF OBJECT_PUNTOS_ENTREGA;

COMMIT;
/


