ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = ADMIN;

CREATE TABLE ADMIN.URG_TADMISION (
    AD_ID_ADMISION         NUMBER(10)             NOT NULL,
    COD_EMPRESA            VARCHAR2(3 BYTE)       NOT NULL,
    AD_NUMFOLIO            NUMBER(10),
    TI_ID_TIPINGRESO       NUMBER(10)             NOT NULL,
    TA_ID_TIPACCIDENTE     NUMBER(10)             NOT NULL,
    TA_ID_TIPATENCION      NUMBER(10)             NOT NULL,
    ES_ID_ESTADO           NUMBER(10)             NOT NULL,
    COD_TRANSPORTE         VARCHAR2(2 BYTE)       NOT NULL,
    COD_PROCED             VARCHAR2(2 BYTE)       NOT NULL,
    AD_PREVISION           VARCHAR2(2 BYTE),
    ES_ID_ESTAPROC         VARCHAR2(3 BYTE),
    AD_FHADMISION          TIMESTAMP(6)           NOT NULL,
    AD_ACOMPA              VARCHAR2(50 BYTE),
    AD_FONOACOMP           VARCHAR2(15 BYTE),
    AD_MOTIVOCONSUL        VARCHAR2(1000 BYTE),
    AD_NUMPAGARE           VARCHAR2(50 BYTE),
    PR_PROFREG             VARCHAR2(50 BYTE)      NOT NULL,
    AD_FHREGISTRO          TIMESTAMP(6),
    PR_PROFEDIT            VARCHAR2(50 BYTE),
    AD_FHEDIT              TIMESTAMP(6),
    AD_ID_ESTADOATENCION   NUMBER(20),
    PR_NOMBREPROFREG       VARCHAR2(100 BYTE),
    PR_NOMBREPROFEDIT      VARCHAR2(100 BYTE),
    AD_ESTADOCIERRETIEMPO  NUMBER(1)              DEFAULT 0,
    AD_PROCEDENCIA         NUMBER(10),
    AD_ACTIVA              NUMBER(1)              DEFAULT 1,
    AD_FHCREACION          TIMESTAMP(6),
    AD_HIPODIAGNO          VARCHAR2(3000 BYTE),
    COD_RUTPRO             NUMBER(10),
    AD_FECHORA_ATEN        DATE,
    NUM_FICHAE             NUMBER(10),
    AD_RUTTUTOR            VARCHAR2(15 BYTE),
    AN_REGCIERRE           NUMBER,
    IND_ESTADODERIVA       NUMBER(10)             DEFAULT 0,
    AD_ATENEFERMERIA       NUMBER(1),
    IND_HDIGITAL           NUMBER(1),
    ID_GRUPO               NUMBER(3),
    IND_PERTINENCIAIC      NUMBER(1),
    IND_NUMMOTIVOPERT      NUMBER(1),
    DES_MOTIVOPERT         VARCHAR2(1000 BYTE),
    IND_DONANTE            NUMBER(1),
    IND_NOTIFICLP          NUMBER,
    PRIMARY KEY (AD_ID_ADMISION)
);

COMMIT;
/

CREATE TABLE ADMIN.URG_TCIERRE (
    CI_ID_CIERRE         NUMBER(10)               NOT NULL,
    AD_ID_ADMISION       NUMBER(10)               NOT NULL,
    TD_ID_TIPDERICIERRE  NUMBER(10)               NOT NULL,
    TE_ID_TIPEGRESO      NUMBER(10)               NOT NULL,
    CI_FHEGRESO          VARCHAR2(100 BYTE)       NOT NULL,
    CI_INDIEGRESO        VARCHAR2(1000 BYTE)      NOT NULL,
    CI_FHCIERRE          TIMESTAMP(6)             NOT NULL,
    CI_FHREGISTRO        TIMESTAMP(6)             NOT NULL,
    PR_PROFREG           VARCHAR2(50 BYTE)        NOT NULL,
    CI_TIEMPOCONTROL     NUMBER(2),
    CI_INFODERIVACION    VARCHAR2(100 BYTE),
    PR_NOMBREPROFREG     VARCHAR2(100 BYTE),
    CI_MEDIOTRANSCIERRE  NUMBER,
    TD_ID_SERVICIO       NUMBER(4),
    CI_OBSDIAGNO         VARCHAR2(3000 BYTE),
    CI_MOTIVONSA         VARCHAR2(4 BYTE)         DEFAULT 0000,
    CI_INDREASIGNA       NUMBER(1)                DEFAULT 0,
    CI_FECATENCIONPROF   DATE,
    CI_CODDESTINM        VARCHAR2(100 BYTE),
    CI_CODVTRASLADO      NUMBER,
    CI_PROFEGRESO        NUMBER,
    CI_DATEUPDATE        DATE,
    CI_MOTIVTRASLADO     VARCHAR2(1000 BYTE),
    AD_RIESGOV           NUMBER(1),
    AD_SECUELAS          NUMBER(1),
    CI_DIAGENT           NUMBER,
    AD_DONANTE           NUMBER(1),
    PRIMARY KEY (CI_ID_CIERRE)
);


CREATE SEQUENCE ADMIN.SEQ_URG_TADMISION
    START WITH 0
    MAXVALUE 999999999999999999999999999
    MINVALUE 0
    NOCYCLE
    NOCACHE
    NOORDER;

COMMIT;
