ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = ADMIN;

CREATE TABLE ADMIN.URG_TADMISION (
    AD_ID_ADMISION         NUMBER(10) NOT NULL,
    COD_EMPRESA            VARCHAR2(3 BYTE) NOT NULL,
    AD_NUMFOLIO            NUMBER(10),
    TI_ID_TIPINGRESO       NUMBER(10) NOT NULL,
    TA_ID_TIPACCIDENTE     NUMBER(10) NOT NULL,
    TA_ID_TIPATENCION      NUMBER(10) NOT NULL,
    ES_ID_ESTADO           NUMBER(10) NOT NULL,
    COD_TRANSPORTE         VARCHAR2(2 BYTE) NOT NULL,
    COD_PROCED             VARCHAR2(2 BYTE) NOT NULL,
    AD_PREVISION           VARCHAR2(2 BYTE),
    ES_ID_ESTAPROC         VARCHAR2(3 BYTE),
    AD_FHADMISION          TIMESTAMP(6) NOT NULL,
    AD_ACOMPA              VARCHAR2(50 BYTE),
    AD_FONOACOMP           VARCHAR2(15 BYTE),
    AD_MOTIVOCONSUL        VARCHAR2(1000 BYTE),
    AD_NUMPAGARE           VARCHAR2(50 BYTE),
    PR_PROFREG             VARCHAR2(50 BYTE) NOT NULL,
    AD_FHREGISTRO          TIMESTAMP(6),
    PR_PROFEDIT            VARCHAR2(50 BYTE),
    AD_FHEDIT              TIMESTAMP(6),
    AD_ID_ESTADOATENCION   NUMBER(20),
    PR_NOMBREPROFREG       VARCHAR2(100 BYTE),
    PR_NOMBREPROFEDIT      VARCHAR2(100 BYTE),
    AD_ESTADOCIERRETIEMPO  NUMBER(1) DEFAULT 0,
    AD_PROCEDENCIA         NUMBER(10),
    AD_ACTIVA              NUMBER(1) DEFAULT 1,
    AD_FHCREACION          TIMESTAMP(6),
    AD_HIPODIAGNO          VARCHAR2(3000 BYTE),
    COD_RUTPRO             NUMBER(10),
    AD_FECHORA_ATEN        DATE,
    NUM_FICHAE             NUMBER(10),
    AD_RUTTUTOR            VARCHAR2(15 BYTE),
    AN_REGCIERRE           NUMBER,
    IND_ESTADODERIVA       NUMBER(10) DEFAULT 0,
    AD_ATENEFERMERIA       NUMBER(1),
    IND_HDIGITAL           NUMBER(1),
    ID_GRUPO               NUMBER(3),
    IND_PERTINENCIAIC      NUMBER(1),
    IND_NUMMOTIVOPERT      NUMBER(1),
    DES_MOTIVOPERT         VARCHAR2(1000 BYTE),
    IND_DONANTE            NUMBER(1),
    IND_NOTIFICLP          NUMBER,
    PRIMARY KEY (AD_ID_ADMISION)
);

COMMIT;
/

CREATE TABLE ADMIN.URG_TCIERRE (
    CI_ID_CIERRE         NUMBER(10)               NOT NULL,
    AD_ID_ADMISION       NUMBER(10)               NOT NULL,
    TD_ID_TIPDERICIERRE  NUMBER(10)               NOT NULL,
    TE_ID_TIPEGRESO      NUMBER(10)               NOT NULL,
    CI_FHEGRESO          VARCHAR2(100 BYTE)       NOT NULL,
    CI_INDIEGRESO        VARCHAR2(1000 BYTE)      NOT NULL,
    CI_FHCIERRE          TIMESTAMP(6)             NOT NULL,
    CI_FHREGISTRO        TIMESTAMP(6)             NOT NULL,
    PR_PROFREG           VARCHAR2(50 BYTE)        NOT NULL,
    CI_TIEMPOCONTROL     NUMBER(2),
    CI_INFODERIVACION    VARCHAR2(100 BYTE),
    PR_NOMBREPROFREG     VARCHAR2(100 BYTE),
    CI_MEDIOTRANSCIERRE  NUMBER,
    TD_ID_SERVICIO       NUMBER(4),
    CI_OBSDIAGNO         VARCHAR2(3000 BYTE),
    CI_MOTIVONSA         VARCHAR2(4 BYTE)         DEFAULT 0000,
    CI_INDREASIGNA       NUMBER(1)                DEFAULT 0,
    CI_FECATENCIONPROF   DATE,
    CI_CODDESTINM        VARCHAR2(100 BYTE),
    CI_CODVTRASLADO      NUMBER,
    CI_PROFEGRESO        NUMBER,
    CI_DATEUPDATE        DATE,
    CI_MOTIVTRASLADO     VARCHAR2(1000 BYTE),
    AD_RIESGOV           NUMBER(1),
    AD_SECUELAS          NUMBER(1),
    CI_DIAGENT           NUMBER,
    AD_DONANTE           NUMBER(1),
    PRIMARY KEY (CI_ID_CIERRE)
);


CREATE SEQUENCE ADMIN.SEQ_URG_TADMISION
    START WITH 0
    MAXVALUE 999999999999999999999999999
    MINVALUE 0
    NOCYCLE
    NOCACHE
    NOORDER;


CREATE TABLE ADMIN.SS_TEMPRESAS
(
  COD_EMPRESA    VARCHAR2(5 BYTE),
  NUM_RUTEMP     NUMBER(8),
  COD_DVEMP      CHAR(1 BYTE),
  NOM_RAZSOC     VARCHAR2(40 BYTE),
  NOM_DIRECC     VARCHAR2(40 BYTE),
  COD_COMUNA     VARCHAR2(5 BYTE),
  IND_CONSOLIDA  VARCHAR2(2 BYTE),
  IND_TIPEST     CHAR(1 BYTE),
  COD_SERSAL     VARCHAR2(5 BYTE),
  IND_DEPMUN     CHAR(1 BYTE),
  IND_URBRUR     CHAR(1 BYTE),
  IND_RED        CHAR(1 BYTE),
  COD_USUARI     VARCHAR2(60 BYTE),
  IND_ESTADO     CHAR(1 BYTE),
  FEC_AUDITA     DATE,
  COD_ESTABLRH   VARCHAR2(5 BYTE),
  NUM_TELEFONO   VARCHAR2(20 BYTE)
);

COMMIT;

/

Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('100', 61602222, '9', 'H. ANGOL', 'ILABACA 752', 
    '09201', NULL, NULL, '029', NULL, 
    NULL, NULL, NULL, 'V', TO_DATE('03/20/2003 10:02:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('029', 61955100, '1', 'DSSAN', 'PEDRO DE OÑA 387', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'CAPACITA', 'V', TO_DATE('12/27/2002 11:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('106', 61602229, '6', 'H. VICTORIA', 'PEDRO DARNEL S/N', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('07/10/2003 11:19:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('101', 61602224, '5', 'H. PUREN', 'IMPERIAL 1562', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('12/10/2004 09:06:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('303', NULL, NULL, 'CSF ALEMANIA', 'BAVIERA 445', 
    '09201', NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('03/04/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('302', NULL, NULL, 'CSF ERCILLA', 'CAUPOLICAN 451', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('03/04/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('301', NULL, NULL, 'CSF HUEQUEN', 'CAMINOS LOS SAUCES 071', 
    '09201', NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('03/04/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('102', NULL, NULL, 'CSF LOS SAUCES', 'ERCILLA 601', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, NULL, 'V', NULL, 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('105', NULL, NULL, 'CSF LUMACO', 'CONDELL S/N', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, NULL, 'V', NULL, 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('316', NULL, NULL, 'DSM COLLIPULLI', 'FREIRE 1110', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, NULL, 'V', NULL, 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('319', NULL, NULL, 'DSM CURACAUTIN', 'PRAT 837', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, NULL, 'V', NULL, 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('317', NULL, NULL, 'DSM TRAIGUEN', 'BALMACEDA  424', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, NULL, 'V', NULL, 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('104', 61602226, '1', 'H. TRAIGUEN', '21 DE MAYO 751', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, NULL, 'V', NULL, 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('103', NULL, NULL, 'H. COLLIPULLI', 'BULNES S/N', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, NULL, 'V', TO_DATE('03/13/2006 13:24:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('107', NULL, NULL, 'H. CURACAUTIN', 'SERRANO S/N', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, NULL, 'V', NULL, 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('108', NULL, NULL, 'H. LONQUIMAY', 'OHIGGINS 1060', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, NULL, 'V', NULL, 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('300', NULL, NULL, 'CSF RENAICO', 'CORNELIO OLSEN 398', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, NULL, 'V', NULL, 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('318', NULL, NULL, 'CSF VICTORIA', 'AVENIDA MUÑOZ VARGAS 730', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, NULL, 'V', NULL, 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('999', NULL, NULL, 'ESTABL. PRIVADO', 'S/N', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, NULL, 'V', NULL, 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('030', NULL, NULL, 'SS ARAUCANIA NORTE', 'PEDRO DE OÑA 387', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, NULL, 'V', TO_DATE('01/05/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('995', NULL, NULL, 'OTRO ESTABLECIMIENTO', 'S/N', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, NULL, 'V', NULL, 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('333', NULL, NULL, 'ACHS', 'ILABACA 752', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('02/18/2008 10:04:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('320', NULL, NULL, 'DSM LONQUIMAY', 'IGNACIO CARRERA PINTO 559', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('03/13/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('315', NULL, NULL, 'DSM  PUREN', 'DR. GARRIGA 1055', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('03/13/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('703', NULL, NULL, 'CECOF EL RETIRO', 'ANGOL', 
    '09201', NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('06/22/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('304', NULL, NULL, 'CSF  PIEDRA DEL AGUILA', 'ANGOL', 
    '09201', NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('06/22/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('035', NULL, NULL, 'DSM ANGOL', 'ANGOL', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('06/21/2010 16:52:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('451', NULL, NULL, 'POSTA ICALMA', 'ICALMA', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('05/08/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('718', NULL, NULL, 'CECOF BAJO TRAIGUEN', 'VICTORIA', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('05/30/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('705', NULL, NULL, 'CECOF CAPITAN PASTENES', 'CAPITAN PASTENES', 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('06/08/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('448', NULL, NULL, 'POSTA CONTRACO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('06/27/2012 16:19:35', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('449', NULL, NULL, 'POSTA LOLEN', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('06/27/2012 16:19:35', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('450', NULL, NULL, 'POSTA SIERRA NEVADA', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('06/27/2012 16:19:35', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('452', NULL, NULL, 'POSTA LIUCURA', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('06/27/2012 16:19:35', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('453', NULL, NULL, 'POSTA PEDREGOSO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('06/27/2012 16:19:35', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('454', NULL, NULL, 'POSTA PICHIPEHUENCO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('06/27/2012 16:19:35', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('455', NULL, NULL, 'POSTA TROYO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('06/27/2012 16:19:35', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('400', NULL, NULL, 'POSTA VEGAS BLANCAS', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('06/27/2012 16:50:01', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('403', NULL, NULL, 'POSTA COLONIA MANUEL RODRIGUEZ', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('06/27/2012 16:50:01', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('401', NULL, NULL, 'POSTA DE SALUD RURAL COYANCO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('06/27/2012 16:50:01', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('410', NULL, NULL, 'POSTA MAICA', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('411', NULL, NULL, 'POSTA MININCO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('412', NULL, NULL, 'POSTA LA BATALLA', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('413', NULL, NULL, 'POSTA AMARGO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('414', NULL, NULL, 'POSTA NIBLINTO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('587', NULL, NULL, 'POSTA ENCINAR', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('441', NULL, NULL, 'POSTA MALALCAHUELLO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('442', NULL, NULL, 'POSTA RIO BLANCO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('443', NULL, NULL, 'POSTA LA TEPA', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('444', NULL, NULL, 'POSTA SANTA ANA', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('445', NULL, NULL, 'POSTA RADALCO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('446', NULL, NULL, 'POSTA RARIRUCA', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('447', NULL, NULL, 'POSTA MANZANAR CURACAUTIN', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('588', NULL, NULL, 'POSTA SANTA JULIA', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('415', NULL, NULL, 'POSTA CHEQUENCO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('432', NULL, NULL, 'POSTA PAILAHUEQUE', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('438', NULL, NULL, 'POSTA CHACAICO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('439', NULL, NULL, 'POSTA TRICAUCO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('440', NULL, NULL, 'POSTA TEMOCUICUI', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('407', NULL, NULL, 'POSTA SAN RAMON DE LOS SAUCES', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('408', NULL, NULL, 'POSTA TRINTRE', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('419', NULL, NULL, 'POSTA SANTA ROSA', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('585', NULL, NULL, 'POSTA PIVADENCO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('423', NULL, NULL, 'POSTA PICHIPELLAHUEN', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('424', NULL, NULL, 'POSTA CURILEBU', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('425', NULL, NULL, 'POSTA MANZANAR LUMACO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('426', NULL, NULL, 'POSTA CHANCO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('427', NULL, NULL, 'POSTA LA HERRADURA', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('404', NULL, NULL, 'POSTA CUARTEL QUEMADO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('405', NULL, NULL, 'POSTA COYANCAHUIN', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('406', NULL, NULL, 'POSTA EL LINGUE', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('428', NULL, NULL, 'POSTA LONCOYAN', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('437', NULL, NULL, 'POSTA HUITRANLEBU', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('409', NULL, NULL, 'POSTA TIJERAL', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('416', NULL, NULL, 'POSTA ANIÑIR', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('417', NULL, NULL, 'POSTA MOLCO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('418', NULL, NULL, 'POSTA QUECHEREGUAS', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('420', NULL, NULL, 'POSTA TEMULEMU', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('421', NULL, NULL, 'POSTA QUILQUEN', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('586', NULL, NULL, 'POSTA DIDAICO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('429', NULL, NULL, 'POSTA SELVA OSCURA', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('430', NULL, NULL, 'POSTA PUA', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('431', NULL, NULL, 'POSTA QUINO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('433', NULL, NULL, 'POSTA ROSARIO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('434', NULL, NULL, 'POSTA CULLINCO', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('435', NULL, NULL, 'POSTA CALIFORNIA', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into ADMIN.SS_TEMPRESAS
   (COD_EMPRESA, NUM_RUTEMP, COD_DVEMP, NOM_RAZSOC, NOM_DIRECC, 
    COD_COMUNA, IND_CONSOLIDA, IND_TIPEST, COD_SERSAL, IND_DEPMUN, 
    IND_URBRUR, IND_RED, COD_USUARI, IND_ESTADO, FEC_AUDITA, 
    COD_ESTABLRH, NUM_TELEFONO)
 Values
   ('436', NULL, NULL, 'POSTA REDUCCION PAILAHUEQUE', NULL, 
    NULL, NULL, NULL, '029', NULL, 
    NULL, NULL, 'ADMIN', 'V', TO_DATE('08/30/2012 15:03:41', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
COMMIT;
