Insert into ADMIN.PB_TECNICASXMUESTRAS
   (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO)
 Values
   (1, 'DIFF', 1);
Insert into ADMIN.PB_TECNICASXMUESTRAS
   (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO)
 Values
   (2, 'PAS', 1);
Insert into ADMIN.PB_TECNICASXMUESTRAS
   (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO)
 Values
   (3, 'ACEN BLUE', 1);
Insert into ADMIN.PB_TECNICASXMUESTRAS
   (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO)
 Values
   (4, 'HE', 1);
Insert into ADMIN.PB_TECNICASXMUESTRAS
   (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO)
 Values
   (5, 'PAPANICOLAOU', 1);
Insert into ADMIN.PB_TECNICASXMUESTRAS
   (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO)
 Values
   (6, 'GRAM', 1);
Insert into ADMIN.PB_TECNICASXMUESTRAS
   (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO)
 Values
   (7, 'MASSON', 1);
Insert into ADMIN.PB_TECNICASXMUESTRAS
   (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO)
 Values
   (8, 'VAN GEISON', 1);
Insert into ADMIN.PB_TECNICASXMUESTRAS
   (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO)
 Values
   (9, 'OLI RED', 1);
Insert into ADMIN.PB_TECNICASXMUESTRAS
   (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO)
 Values
   (10, 'ZIEHL NELSEN', 1);
Insert into ADMIN.PB_TECNICASXMUESTRAS
   (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO)
 Values
   (11, 'GROCOTT', 1);
Insert into ADMIN.PB_TECNICASXMUESTRAS
   (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO)
 Values
   (12, 'RETÍCULO', 1);
Insert into ADMIN.PB_TECNICASXMUESTRAS
   (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO)
 Values
   (13, 'GORDON SWEET', 1);
Insert into ADMIN.PB_TECNICASXMUESTRAS
   (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO)
 Values
   (14, 'WARTHIN STARRY', 1);
Insert into ADMIN.PB_TECNICASXMUESTRAS
   (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO)
 Values
   (15, 'GIEMSA', 1);
Insert into ADMIN.PB_TECNICASXMUESTRAS
   (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO)
 Values
   (16, 'MAY GRUNWALD GIEMSA', 1);
Insert into ADMIN.PB_TECNICASXMUESTRAS
   (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO)
 Values
   (17, 'PERLS', 1);
Insert into ADMIN.PB_TECNICASXMUESTRAS
   (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO)
 Values
   (18, 'ROJO CONGO', 1);
Insert into ADMIN.PB_TECNICASXMUESTRAS
   (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO)
 Values
   (19, 'AZUL ALCIAN', 1);
Insert into ADMIN.PB_TECNICASXMUESTRAS
   (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO)
 Values
   (20, 'VERHOFFS', 1);
Insert into ADMIN.PB_TECNICASXMUESTRAS
   (ID_TECNICA_AP, TXT_TECNICA_AP, IND_ESTADO)
 Values
   (21, 'FONTANA MASSON', 1);
COMMIT;
/