ALTER SYSTEM SET NLS_DATE_FORMAT='DD-MM-YYYY HH24:MI:SS' SCOPE=SPFILE;

ALTER SYSTEM SET NLS_DATE_FORMAT = 'DD-MM-YYYY' SCOPE=SPFILE;

SELECT value FROM nls_database_parameters WHERE parameter = 'NLS_DATE_FORMAT';
